// yarn.lock exactly as yarn 1's stringify.js writes it: yarn's own reader takes
// more, and reads some of it unlike other readers.

import { LockfileError, quote } from '../error.js'

const HEADER = ['# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.', '# yarn lockfile v1']
const VERSION = /^# yarn lockfile v(\d+)$/u

const fail = (detail, number) => new LockfileError(`${detail} at line ${number + 1}`)

// Never written raw by yarn. A lone CR ends a line to yarn alone, and U+2028
// and U+2029 to some other readers.
const FORBIDDEN = /[\p{Cc}\p{Cs}\uFEFF\uFFFE\uFFFF\u2028\u2029]/u
const hex = (char) => `U+${char.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')}`

// yarn ends every line alike, as the file it rewrites did.
function advance(src) {
  const { text, pos } = src
  src.line = undefined
  if (pos >= text.length) return
  let end = text.indexOf('\n', pos)
  if (end === -1) end = text.length
  src.pos = end + 1
  src.number++
  const crlf = end < text.length && text[end - 1] === '\r'
  const line = text.slice(pos, crlf ? end - 1 : end)
  const char = FORBIDDEN.exec(line)?.[0]
  if (char !== undefined) throw fail(`${hex(char)} is not allowed`, src.number)
  if (end < text.length && crlf !== (src.crlf ??= crlf)) throw fail(`a ${crlf ? 'CRLF' : 'LF'} line end, after ${src.crlf ? 'CRLF' : 'LF'} ones`, src.number)
  src.line = line
}

// yarn's maybeWrap; a bare `true…` or `false…` reads back as a boolean.
const QUOTED = /[:\s\\",[\]]/u
const quoted = (value) => value.startsWith('true') || value.startsWith('false') || QUOTED.test(value) || !/^[A-Za-z]/u.test(value)
const BARE = /[A-Za-z][^\s:\\",[\]]*/uy

// yarn ends a quoted string at a quote after one backslash, not two, so a
// backslash before a quote in the value ends it early.
function readEscaped(raw, number) {
  let value
  try {
    value = JSON.parse(raw)
  } catch {
    throw fail(`${quote(raw)} is not a string as JSON writes it`, number)
  }
  if (JSON.stringify(value) !== raw) throw fail(`${quote(raw)} is not written as JSON writes ${quote(value)}`, number)
  if (value.includes('\\"')) throw fail(`${quote(value)} is a string yarn reads to another quote`, number)
  const char = FORBIDDEN.exec(value)?.[0]
  if (char !== undefined) throw fail(`an escape for ${hex(char)}, which is not allowed`, number)
  return value
}

// No backslash: the text is the value, as controls and lone surrogates are
// refused before.
function readQuoted(line, pos, number) {
  let end = pos + 1
  while (end < line.length && line[end] !== '"') end += line[end] === '\\' ? 2 : 1
  if (end >= line.length) throw fail('a string with no closing quote', number)
  const raw = line.slice(pos, ++end)
  const value = raw.includes('\\') ? readEscaped(raw, number) : raw.slice(1, -1)
  if (!quoted(value)) throw fail(`${quote(value)} is quoted, where yarn writes it bare`, number)
  return [value, end]
}

function readString(line, pos, number) {
  if (line[pos] === '"') return readQuoted(line, pos, number)
  BARE.lastIndex = pos
  const value = BARE.exec(line)?.[0]
  if (value === undefined) throw fail(`expected a string, found ${pos < line.length ? quote(line.slice(pos)) : 'the end of the line'}`, number)
  if (quoted(value)) throw fail(`${quote(value)} is bare, where yarn quotes it`, number)
  return [value, pos + value.length]
}

function readKey(line, pos, number) {
  const [key, end] = readString(line, pos, number)
  if (key === '') throw fail('an empty key, which yarn does not read', number)
  return [key, end]
}

// @yarnpkg/parsers, yarn 2+'s reader of v1, takes a bare `null…` as null.
function readValue(line, pos, number) {
  const [value, end] = readString(line, pos, number)
  if (value.startsWith('null') && line[pos] !== '"') throw fail(`${quote(value)} is bare, and read as null by some readers`, number)
  return [value, end]
}

function expectEnd(line, pos, number) {
  if (pos !== line.length) throw fail(`expected the end of the line, found ${quote(line.slice(pos))}`, number)
}

function indentOf(line) {
  let indent = 0
  while (line[indent] === ' ') indent++
  return indent
}

function expectHeader(src, expected) {
  if (src.line !== expected) throw fail(`expected yarn's header, ${quote(expected)}`, Math.max(src.number, 0))
  advance(src)
}

// Below the header yarn may write its and Node's versions, other tools theirs.
function readHeader(src) {
  expectHeader(src, HEADER[0])
  const version = VERSION.exec(src.line ?? '')?.[1]
  if (version !== undefined && version !== '1') throw fail(`unsupported version: expected "1", found ${quote(version)}`, src.number)
  expectHeader(src, HEADER[1])
  for (; src.line?.startsWith('#'); advance(src)) {
    if (/^yarn lockfile v\d+$/u.test(src.line.slice(1).trim())) throw fail('a second lockfile version', src.number)
    if (src.line === '#') throw fail('a comment of "#" alone, which @yarnpkg/parsers does not read', src.number)
  }
}

function readMap(src, field, number) {
  const map = Object.create(null)
  for (let line = src.line; line?.startsWith(' '); line = src.line) {
    const indent = indentOf(line)
    if (indent <= 2) break
    if (indent !== 4) throw fail(`expected 4 spaces of indentation, found ${indent}`, src.number)
    const [name, end] = readKey(line, 4, src.number)
    if (line[end] !== ' ') throw fail(`expected a space and a range after ${quote(name)}`, src.number)
    const [range, after] = readValue(line, end + 1, src.number)
    expectEnd(line, after, src.number)
    if (name in map) throw fail(`${quote(name)} is in ${quote(field)} twice`, src.number)
    map[name] = range
    advance(src)
  }
  if (Object.keys(map).length === 0) throw fail(`expected what ${quote(field)} holds below it`, number)
  return map
}

function readFields(src, number) {
  const fields = Object.create(null)
  for (let line = src.line; line?.startsWith(' '); line = src.line) {
    const indent = indentOf(line)
    if (indent !== 2) throw fail(`expected 2 spaces of indentation, found ${indent}`, src.number)
    const here = src.number
    const [field, end] = readKey(line, 2, here)
    if (field in fields) throw fail(`the field ${quote(field)} twice`, here)
    if (line[end] === ':') {
      expectEnd(line, end + 1, here)
      advance(src)
      fields[field] = readMap(src, field, here)
      continue
    }
    if (line[end] !== ' ') throw fail(`expected a space and a value, or ":", after ${quote(field)}`, here)
    const [value, after] = readValue(line, end + 1, here)
    expectEnd(line, after, here)
    fields[field] = value
    advance(src)
  }
  if (Object.keys(fields).length === 0) throw fail('expected the fields of the entry below it', number)
  return fields
}

function readEntry(src, seen) {
  const { line, number } = src
  const keys = []
  for (let pos = 0; ;) {
    const [key, end] = readKey(line, pos, number)
    if (seen.has(key)) throw fail(`${quote(key)} is a key ${seen.get(key) === number ? 'twice' : `at line ${seen.get(key) + 1} too`}`, number)
    seen.set(key, number)
    keys.push(key)
    if (line[end] === ':') {
      expectEnd(line, end + 1, number)
      break
    }
    if (!line.startsWith(', ', end)) throw fail(`expected ", " and a pattern, or ":", after ${quote(key)}`, number)
    pos = end + 2
  }
  advance(src)
  return { keys, fields: readFields(src, number) }
}

const CONFLICT = ['<<<<<<<', '=======', '>>>>>>>']

// Each entry: its patterns, and fields that are strings or null-prototype maps.
export function readEntries(text) {
  if (CONFLICT.every((marker) => text.includes(marker))) throw new LockfileError(`yarn reads a file with ${CONFLICT.map((marker) => quote(marker)).join(', ')} in it as a merge conflict`)
  const src = { text, pos: 0, number: -1, line: undefined, crlf: undefined }
  advance(src)
  readHeader(src)
  const entries = []
  const seen = new Map()
  let blank
  for (let line = src.line; line !== undefined; line = src.line) {
    if (line === '') {
      if (entries.length > 0) blank ??= src.number
      advance(src)
      continue
    }
    if (line.startsWith(' ')) throw blank === undefined ? fail('expected an entry, at column 0', src.number) : fail('a blank line within an entry', blank)
    if (line.startsWith('#')) throw fail('a comment, which yarn writes in the header alone', src.number)
    blank = undefined
    entries.push(readEntry(src, seen))
  }
  return entries
}
