allowBuilds:
  esbuild: false

autoInstallPeers: false

enableGlobalVirtualStore: false

linkWorkspacePackages: true

lockfileIncludeTarballUrl: true

minimumReleaseAgeExclude:
  - "@chalker/*"
  - "@preventive/*"
  - "@rray/*"

modulesCacheMaxAge: 0

packages:
  - "ai"
  - "diff"
  - "archive"
  - "deptree"
  - "lockfile"
  - "upstream"
  - "vfs"
  - "report"
  - "sourcemap"

preferWorkspacePackages: true
