// yarn.lock as yarn 1 writes it (its lockfile/stringify.js): two lines of
// header, then an entry for each package, blank lines between. An entry is
// its patterns, `, ` between them, and a `:`; below it, two spaces in, a
// field and its value, or a field, a `:`, and below that, two spaces further
// in, a name and its range on each line. A string is bare where yarn writes
// it bare, and in double quotes, as JSON writes it, where yarn quotes it.
//
// That is what is read, and nothing looser. yarn's own reader takes more,
// and reads some of it as no other reader does: a bare `1.0` is a number to
// it and a bare `true` a boolean, a string with `\\\"` in it ends at the
// wrong quote, a blank line within an entry ends it and drops the rest of
// the file, a comment is dropped wherever it is, a file with the three
// markers of a merge conflict is merged, and what it cannot read at all it
// reads again as YAML. Each of these is refused.

import { LockfileError, quote } from '../error.js'

const HEADER = ['# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.', '# yarn lockfile v1']
const VERSION = /^# yarn lockfile v(\d+)$/u

const fail = (detail, number) => new LockfileError(`${detail} at line ${number + 1}`)

// Tabs and other controls are refused everywhere, as yarn never writes them
// raw, and a lone carriage return is a line end to yarn alone; so are a byte
// order mark, which yarn drops, lone surrogates, U+FFFE and U+FFFF, and
// U+2028 and U+2029, which end a line to some readers.
const FORBIDDEN = /[\p{Cc}\p{Cs}\uFEFF\uFFFE\uFFFF\u2028\u2029]/u

// Moves `src.line` on to the next line, without its `\n` or `\r\n`, and
// undefined past the last.
function advance(src) {
  const { text, pos } = src
  src.line = undefined
  if (pos >= text.length) return
  let end = text.indexOf('\n', pos)
  if (end === -1) end = text.length
  src.pos = end + 1
  src.number++
  const line = text.slice(pos, end < text.length && text[end - 1] === '\r' ? end - 1 : end)
  const char = FORBIDDEN.exec(line)?.[0]
  if (char !== undefined) throw fail(`U+${char.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')} is not allowed`, src.number)
  src.line = line
}

// yarn's maybeWrap: what it quotes. The rest starts with a letter and
// holds nothing that ends a bare string to yarn's reader, which reads a bare
// `true…` and `false…` as a boolean and the rest of the string after it.
const QUOTED = /[:\s\\",[\]]/u
const quoted = (value) => value.startsWith('true') || value.startsWith('false') || QUOTED.test(value) || !/^[A-Za-z]/u.test(value)
const BARE = /[A-Za-z][^\s:\\",[\]]*/uy

// A quoted string with a backslash in it, as JSON reads it and writes it
// back. yarn's reader ends a quoted string at the first quote with no
// backslash before it, or with two: at a quote after a backslash the string
// holds, which is early.
function readEscaped(raw, number) {
  let value
  try {
    value = JSON.parse(raw)
  } catch {
    throw fail(`${quote(raw)} is not a string as JSON writes it`, number)
  }
  if (JSON.stringify(value) !== raw) throw fail(`${quote(raw)} is not written as JSON writes ${quote(value)}`, number)
  if (value.includes('\\"')) throw fail(`${quote(value)} is a string yarn reads to another quote`, number)
  return value
}

// One with none is its text, as no control or lone surrogate is let past.
function readQuoted(line, pos, number) {
  let end = pos + 1
  while (end < line.length && line[end] !== '"') end += line[end] === '\\' ? 2 : 1
  if (end >= line.length) throw fail('a string with no closing quote', number)
  const raw = line.slice(pos, ++end)
  const value = raw.includes('\\') ? readEscaped(raw, number) : raw.slice(1, -1)
  if (!quoted(value)) throw fail(`${quote(value)} is quoted, where yarn writes it bare`, number)
  return [value, end]
}

// A string at `pos`, and where it ends.
function readString(line, pos, number) {
  if (line[pos] === '"') return readQuoted(line, pos, number)
  BARE.lastIndex = pos
  const value = BARE.exec(line)?.[0]
  if (value === undefined) throw fail(`expected a string, found ${pos < line.length ? quote(line.slice(pos)) : 'the end of the line'}`, number)
  if (quoted(value)) throw fail(`${quote(value)} is bare, where yarn quotes it`, number)
  return [value, pos + value.length]
}

// A pattern, a field or a name: yarn's reader takes no empty one.
function readKey(line, pos, number) {
  const [key, end] = readString(line, pos, number)
  if (key === '') throw fail('an empty key, which yarn does not read', number)
  return [key, end]
}

// A value after a name: a bare `null` is a string to yarn, and null to
// @yarnpkg/parsers, which yarn 2 and later and other tools read a yarn.lock
// of v1 with, and which reads no further than `null` in `nullish`.
function readValue(line, pos, number) {
  const [value, end] = readString(line, pos, number)
  if (value.startsWith('null') && line[pos] !== '"') throw fail(`${quote(value)} is bare, and read as null by some readers`, number)
  return [value, end]
}

function expectEnd(line, pos, number) {
  if (pos !== line.length) throw fail(`expected the end of the line, found ${quote(line.slice(pos))}`, number)
}

function indentOf(line) {
  let indent = 0
  while (line[indent] === ' ') indent++
  return indent
}

function expectHeader(src, expected) {
  if (src.line !== expected) throw fail(`expected yarn's header, ${quote(expected)}`, Math.max(src.number, 0))
  advance(src)
}

// yarn's header, and the comments it may add below it: the versions of
// yarn and Node that wrote the file, where it is set to, or another tool's.
function readHeader(src) {
  expectHeader(src, HEADER[0])
  const version = VERSION.exec(src.line ?? '')?.[1]
  if (version !== undefined && version !== '1') throw fail(`unsupported version: expected "1", found ${quote(version)}`, src.number)
  expectHeader(src, HEADER[1])
  for (; src.line?.startsWith('#'); advance(src)) {
    if (/^yarn lockfile v\d+$/u.test(src.line.slice(1).trim())) throw fail('a second lockfile version', src.number)
    if (src.line === '#') throw fail('a comment of "#" alone, which @yarnpkg/parsers does not read', src.number)
  }
}

// The names and ranges below a field, four spaces in.
function readMap(src, field, number) {
  const map = Object.create(null)
  for (let line = src.line; line?.startsWith(' '); line = src.line) {
    const indent = indentOf(line)
    if (indent <= 2) break
    if (indent !== 4) throw fail(`expected 4 spaces of indentation, found ${indent}`, src.number)
    const [name, end] = readKey(line, 4, src.number)
    if (line[end] !== ' ') throw fail(`expected a space and a range after ${quote(name)}`, src.number)
    const [range, after] = readValue(line, end + 1, src.number)
    expectEnd(line, after, src.number)
    if (name in map) throw fail(`${quote(name)} is in ${quote(field)} twice`, src.number)
    map[name] = range
    advance(src)
  }
  if (Object.keys(map).length === 0) throw fail(`expected what ${quote(field)} holds below it`, number)
  return map
}

// An entry's fields, two spaces in: a string each, or a map.
function readFields(src, number) {
  const fields = Object.create(null)
  for (let line = src.line; line?.startsWith(' '); line = src.line) {
    const indent = indentOf(line)
    if (indent !== 2) throw fail(`expected 2 spaces of indentation, found ${indent}`, src.number)
    const here = src.number
    const [field, end] = readKey(line, 2, here)
    if (field in fields) throw fail(`the field ${quote(field)} twice`, here)
    if (line[end] === ':') {
      expectEnd(line, end + 1, here)
      advance(src)
      fields[field] = readMap(src, field, here)
      continue
    }
    if (line[end] !== ' ') throw fail(`expected a space and a value, or ":", after ${quote(field)}`, here)
    const [value, after] = readValue(line, end + 1, here)
    expectEnd(line, after, here)
    fields[field] = value
    advance(src)
  }
  if (Object.keys(fields).length === 0) throw fail('expected the fields of the entry below it', number)
  return fields
}

// An entry's patterns, each a key of one entry alone.
function readEntry(src, seen) {
  const { line, number } = src
  const keys = []
  for (let pos = 0; ;) {
    const [key, end] = readKey(line, pos, number)
    if (seen.has(key)) throw fail(`${quote(key)} is a key ${seen.get(key) === number ? 'twice' : `at line ${seen.get(key) + 1} too`}`, number)
    seen.set(key, number)
    keys.push(key)
    if (line[end] === ':') {
      expectEnd(line, end + 1, number)
      break
    }
    if (!line.startsWith(', ', end)) throw fail(`expected ", " and a pattern, or ":", after ${quote(key)}`, number)
    pos = end + 2
  }
  advance(src)
  return { keys, fields: readFields(src, number) }
}

const CONFLICT = ['<<<<<<<', '=======', '>>>>>>>']

// The entries, in order: each with its patterns, and its fields, where a
// field is a string or a mapping of strings, with a null prototype.
export function readEntries(text) {
  if (CONFLICT.every((marker) => text.includes(marker))) throw new LockfileError(`yarn reads a file with ${CONFLICT.map((marker) => quote(marker)).join(', ')} in it as a merge conflict`)
  const src = { text, pos: 0, number: -1, line: undefined }
  advance(src)
  readHeader(src)
  const entries = []
  const seen = new Map()
  let blank
  for (let line = src.line; line !== undefined; line = src.line) {
    if (line === '') {
      if (entries.length > 0) blank ??= src.number
      advance(src)
      continue
    }
    if (line.startsWith(' ')) throw blank === undefined ? fail('expected an entry, at column 0', src.number) : fail('a blank line within an entry', blank)
    if (line.startsWith('#')) throw fail('a comment, which yarn writes in the header alone', src.number)
    blank = undefined
    entries.push(readEntry(src, seen))
  }
  return entries
}
