import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { LockfileError, TomlError, parseCargoLock } from '../../cargo.js'

// One small lockfile with a package of every kind — path, registry, sparse
// registry, git — and itoa three times over, two versions of it and one
// version from two sources, so that its edges need their versions and
// sources; then one edit at a time, each of which is refused with a message
// that says where and why.

const SUM = 'b'.repeat(64)
const COMMIT = 'c'.repeat(40)
const CRATES = 'registry+https://github.com/rust-lang/crates.io-index'
const GIT = `git+https://github.com/dtolnay/itoa?tag=1.0.18#${COMMIT}`

const BASE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app"
version = "0.1.0"
dependencies = [
 "itoa 0.4.8",
 "itoa 1.0.18 (git+https://github.com/dtolnay/itoa?tag=1.0.18)",
 "itoa 1.0.18 (${CRATES})",
 "lib",
 "memchr",
]

[[package]]
name = "itoa"
version = "0.4.8"
source = "${CRATES}"
checksum = "${SUM}"

[[package]]
name = "itoa"
version = "1.0.18"
source = "${GIT}"

[[package]]
name = "itoa"
version = "1.0.18"
source = "${CRATES}"
checksum = "${SUM}"

[[package]]
name = "lib"
version = "0.2.0"
dependencies = [
 "memchr",
]

[[package]]
name = "memchr"
version = "2.8.3"
source = "sparse+https://index.example.com/"
checksum = "${SUM}"
`

const edit = (from, to) => {
  assert.ok(BASE.includes(from), from)
  return BASE.replace(from, to)
}

describe('parseCargoLock', () => {
  it('reads every package, by its key, with its edges resolved', () => {
    const lock = parseCargoLock(BASE)
    assert.equal(lock.version, 4)
    assert.deepEqual(Object.keys(lock.packages), [
      'app 0.1.0',
      `itoa 0.4.8 (${CRATES})`,
      `itoa 1.0.18 (${GIT})`,
      `itoa 1.0.18 (${CRATES})`,
      'lib 0.2.0',
      'memchr 2.8.3 (sparse+https://index.example.com/)',
    ])
    assert.deepEqual(lock.packages['app 0.1.0'], {
      name: 'app',
      version: '0.1.0',
      source: undefined,
      checksum: undefined,
      dependencies: [`itoa 0.4.8 (${CRATES})`, `itoa 1.0.18 (${GIT})`, `itoa 1.0.18 (${CRATES})`, 'lib 0.2.0', 'memchr 2.8.3 (sparse+https://index.example.com/)'],
    })
    assert.equal(lock.packages[`itoa 0.4.8 (${CRATES})`].checksum, SUM)
    assert.equal(Object.getPrototypeOf(lock.packages), null)
    assert.deepEqual(lock.unusedPatches, [])
  })

  it('reads version 3 alike', () => {
    assert.equal(parseCargoLock(edit('version = 4', 'version = 3')).version, 3)
  })

  it('reads [[patch.unused]]', () => {
    const lock = parseCargoLock(`${BASE}\n[[patch.unused]]\nname = "regex"\nversion = "1.0.0"\nsource = "git+https://example.com/regex#${COMMIT}"\n`)
    assert.deepEqual(lock.unusedPatches, [{ name: 'regex', version: '1.0.0', source: `git+https://example.com/regex#${COMMIT}`, checksum: undefined }])
  })

  it('takes an edge that says more than it needs to', () => {
    const lock = parseCargoLock(edit(' "lib",', ` "lib 0.2.0",`))
    assert.ok(lock.packages['app 0.1.0'].dependencies.includes('lib 0.2.0'))
  })

  it('throws a TypeError for anything but a string', () => {
    assert.throws(() => parseCargoLock(Buffer.from(BASE)), TypeError)
  })

  it('throws a TomlError where the text is not TOML', () => {
    assert.throws(() => parseCargoLock(edit('version = 4', 'version = ')), TomlError)
  })

  const refused = [
    ['no version, as lockfile versions 1 and 2 have', edit('version = 4\n', ''), 'version: no `version`: this is lockfile version 1 or 2, which is not read here, where 3 and 4 are'],
    ['version 5, which only a nightly cargo reads', edit('version = 4', 'version = 5'), 'version: lockfile version 5 is only read by a nightly cargo, with -Znext-lockfile-bump'],
    ['version 2 written out', edit('version = 4', 'version = 2'), 'version: unsupported version: expected 3 or 4, found the integer 2'],
    ['a version as a string', edit('version = 4', 'version = "4"'), 'version: unsupported version: expected 3 or 4, found the string "4"'],
    ['a [metadata] table', `${BASE}\n[metadata]\n"checksum x" = "y"\n`, 'metadata: a [metadata] table holds checksums in lockfile version 1 and nothing cargo writes after'],
    ['a [root] table', `${BASE}\n[root]\nname = "x"\n`, 'root: a [root] table is lockfile version 1, which is not read here'],
    ['a field it does not know', `${BASE}\n[other]\n`, 'unsupported key "other"'],
    ['a package field it does not know', edit('name = "lib"', 'name = "lib"\nyanked = true'), 'package[4]: unsupported key "yanked"'],
    ['a replaced package', edit('name = "lib"', `name = "lib"\nreplace = "lib 0.2.0 (${CRATES})"`), 'package[4].replace: [replace] is not supported'],
    ['a name that is not a package name', edit('name = "lib"', 'name = "l/b"'), 'package[4].name: "l/b" is not a package name'],
    ['a version that is not SemVer', edit('version = "0.2.0"', 'version = "0.2"'), 'package[4].version: "0.2" is not a version'],
    ['a path source', edit('source = "sparse+https://index.example.com/"', 'source = "path+file:///x"'), 'package[5].source: "path+file:///x" is not a source: expected registry+, sparse+ or git+ and a URL'],
    ['a registry URL not in normal form', edit(`source = "${CRATES}"\nchecksum = "${SUM}"\n\n[[package]]\nname = "itoa"\nversion = "1.0.18"\nsource = "${GIT}"`, `source = "registry+HTTPS://github.com/rust-lang/crates.io-index"\nchecksum = "${SUM}"\n\n[[package]]\nname = "itoa"\nversion = "1.0.18"\nsource = "${GIT}"`), 'package[1].source: "registry+HTTPS://github.com/rust-lang/crates.io-index" is not a source: expected a URL in normal form, without a query or a fragment'],
    ['a git source without its commit', edit(`source = "${GIT}"`, 'source = "git+https://github.com/dtolnay/itoa?tag=1.0.18"'), 'package[2].source: "git+https://github.com/dtolnay/itoa?tag=1.0.18" is not a source: expected "#" and the commit it resolved to'],
    ['a git source asking for two things', edit(`source = "${GIT}"`, `source = "git+https://github.com/dtolnay/itoa?tag=1.0.18&branch=x#${COMMIT}"`), `package[2].source: "git+https://github.com/dtolnay/itoa?tag=1.0.18&branch=x#${COMMIT}" is not a source: expected at most one of branch=, tag= or rev=`],
    ['a checksum on a git package', edit(`source = "${GIT}"`, `source = "${GIT}"\nchecksum = "${SUM}"`), 'package[2].checksum: a git package has no checksum'],
    ['a checksum on a path package', edit('name = "lib"', `name = "lib"\nchecksum = "${SUM}"`), 'package[4].checksum: a path package has no checksum'],
    ['a checksum that is not a sha256', edit('source = "sparse+https://index.example.com/"\nchecksum = "b', 'source = "sparse+https://index.example.com/"\nchecksum = "B'), `package[5].checksum: "B${SUM.slice(1)}" is not a sha256 checksum`],
    ['a package listed twice', `${BASE}\n[[package]]\nname = "lib"\nversion = "0.2.0"\n`, 'package[6]: "lib 0.2.0" is listed twice, first as package[4]'],
    ['one source spelled two ways', `${BASE}\n[[package]]\nname = "itoa"\nversion = "1.0.18"\nsource = "git+https://github.com/DTolnay/itoa.git?tag=1.0.18#${COMMIT}"\n`, `package[6]: "itoa 1.0.18 (git+https://github.com/DTolnay/itoa.git?tag=1.0.18#${COMMIT})" is listed twice, first as package[2]`],
    ['an edge to nothing', edit(' "lib",', ' "lob",'), 'package[0].dependencies[3]: "lob" names no package in the lockfile'],
    ['an edge that could be either version', edit(' "itoa 0.4.8",', ' "itoa",'), 'package[0].dependencies[0]: "itoa" could be any of 2 versions'],
    ['an edge to a version not there', edit(' "itoa 0.4.8",', ' "itoa 0.4.9",'), 'package[0].dependencies[0]: "itoa 0.4.9" names a version the lockfile does not hold'],
    ['an edge that could be either source', edit(` "itoa 1.0.18 (${CRATES})",`, ' "itoa 1.0.18",'), 'package[0].dependencies[2]: "itoa 1.0.18" could be any of 2 sources'],
    ['an edge to a source not there', edit(` "itoa 1.0.18 (${CRATES})",`, ' "itoa 1.0.18 (sparse+https://index.example.com/)",'), 'package[0].dependencies[2]: "itoa 1.0.18 (sparse+https://index.example.com/)" names a source the lockfile does not hold'],
    ['an edge with a commit', edit(' "itoa 1.0.18 (git+https://github.com/dtolnay/itoa?tag=1.0.18)",', ` "itoa 1.0.18 (${GIT})",`), `package[0].dependencies[1]: "${GIT}" is not a source: a dependency names no commit`],
    ['an edge spelled with two spaces', edit(' "lib",', ' "lib  0.2.0",'), 'package[0].dependencies[3]: "lib  0.2.0" is not `name`, `name version` or `name version (source)`'],
    ['an edge listed twice', edit(' "lib",', ' "lib",\n "lib 0.2.0",'), 'package[0].dependencies: "lib 0.2.0" is listed twice'],
    ['a package nothing reaches', `${BASE}\n[[package]]\nname = "regex"\nversion = "1.0.0"\nsource = "${CRATES}"\n`, `package: nothing in the workspace depends on "regex 1.0.0 (${CRATES})", directly or not`],
  ]
  for (const [title, text, message] of refused) {
    it(`refuses ${title}`, () => {
      assert.throws(() => parseCargoLock(text), (error) => error instanceof LockfileError && error.message === message)
    })
  }
})
