import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { compress } from '@preventive/archive/compression.js'
import { pack } from '@preventive/archive/tar.js'
import { createVfs } from '@preventive/vfs'
import { DeptreeError, LockfileError, TomlError, buildCargoTree } from '../cargo.js'
import { vendoredPackages } from '../src/cargo/registry.js'
import { rawTar, sha256, slowed, stubRegistry } from './registry.js'

const HOST = Object.freeze({ cargo: '1.97.0', os: 'linux' })
const CRATES_IO = 'registry+https://github.com/rust-lang/crates.io-index'
const encoder = new TextEncoder()

// As cargo package normalizes a manifest, with `extra` after it.
const published = (name, version, extra = '') => `[package]\nedition = "2021"\nname = "${name}"\nversion = "${version}"\nbuild = false\nautobins = false\nautoexamples = false\nautotests = false\nautobenches = false\n\n[lib]\nname = "${name.replaceAll('-', '_')}"\npath = "src/lib.rs"\n${extra}`

// A .crate as cargo package packs one, a GNU tar gzipped: every entry under
// `<name>-<version>/`. `files` maps a path there to text, or to an entry's
// fields; `entries` are entries as given, by their full names.
async function crate(name, version, files = {}, { extra, entries = [] } = {}) {
  const top = `${name}-${version}`
  const list = [
    { name: `${top}/Cargo.toml`, data: encoder.encode(published(name, version, extra)) },
    { name: `${top}/src/lib.rs`, data: new Uint8Array() },
    ...Object.entries(files).map(([path, file]) => {
      const { data = '', ...fields } = typeof file === 'string' ? { data: file } : file
      return { name: `${top}/${path}`, ...fields, ...(fields.type === undefined || fields.type === 'file' ? { data: encoder.encode(data) } : {}) }
    }),
    ...entries,
  ]
  return gzipped(name, version, await compress(pack(list, { format: 'gnu' }), 'gzip'))
}

const gzipped = (name, version, bytes) => ({ name, version, bytes, checksum: sha256(bytes), key: `${name} ${version} (${CRATES_IO})` })

const crateUrl = (name, version) => `https://static.crates.io/crates/${name}/${name}-${version}.crate`

const stubCrates = (crates) => stubRegistry(crates, crateUrl)

// As cargo writes Cargo.lock: a path package where there is no checksum, each
// dependency by name alone where the lockfile has one package of that name.
function lockOf(packages, tail = '') {
  const entry = ({ name, version, checksum, deps = [] }) => [
    '[[package]]', `name = "${name}"`, `version = "${version}"`,
    ...(checksum === undefined ? [] : [`source = "${CRATES_IO}"`, `checksum = "${checksum}"`]),
    ...(deps.length === 0 ? [] : ['dependencies = [', ...deps.toSorted().map((dep) => ` "${dep}",`), ']']),
  ].join('\n')
  return `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n${packages.map(entry).join('\n\n')}\n${tail}`
}

const rootOf = (crates) => `[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n${crates.map((c, i) => `d${i} = { package = "${c.name}", version = "=${c.version}" }\n`).join('')}`
const appOf = (crates) => ({ name: 'app', version: '0.1.0', deps: crates.map(({ name, version }) => (crates.filter((c) => c.name === name).length > 1 ? `${name} ${version}` : name)) })
// A root package depending on each crate, given as text.
const givenOf = (crates) => ({ lockfile: lockOf([appOf(crates), ...crates]), manifests: { '.': rootOf(crates) }, host: HOST })

async function build(crates, options = {}) {
  stubCrates(crates)
  return await buildCargoTree({ ...givenOf(crates), ...options })
}

// The same, read from a project of `files`.
async function read(crates, files) {
  stubCrates(crates)
  return await buildCargoTree({ project: createVfs(files), host: HOST })
}

function listing(vfs, at) {
  const out = {}
  for (const { path, type } of vfs.walk(at)) {
    const { mode } = vfs.lstat(path)
    out[path.slice(at.length + 1) || '.'] = type === 'directory' ? `dir ${mode.toString(8)}` : `${mode.toString(8)} ${path.endsWith('.cargo-checksum.json') ? '' : vfs.readText(path)}`.trimEnd()
  }
  return out
}

// The entries of a crate cargo 1.97 was recorded vendoring, and the
// checksum of each file it wrote.
const WEIRD = {
  '': { type: 'directory', mode: 0o750 },
  'run.sh': { data: 'run', mode: 0o755 },
  secret: { data: 's', mode: 0o600 },
  group: { data: 'g', mode: 0o664 },
  all: { data: 'a', mode: 0o777 },
  suid: { data: 'u', mode: 0o4755 },
  '.gitignore': 'gi',
  '.gitattributes': 'ga',
  'sub/.gitignore': 'nested gi',
  'sub/.gitattributes': 'nested ga',
  '.git/config': 'c',
  'sub/.git/x': 'x',
  '.GIT/y': 'y',
  '.cargo-ok': 'ok',
  'sub/.cargo-ok': 'nested ok',
  'Cargo.toml.orig': 'orig',
  'x.rej': 'rej',
  '.cargo_vcs_info.json': '{}',
  '.hidden/file': 'h',
  only: { type: 'directory', mode: 0o700 },
  'deep/er/f': 'f',
  'ünï cödé': 'n',
  '\uFF61': 'bmp',
  '\u{1F600}': 'astral',
}
const WEIRD_SUMS = '".GIT/y":"a1fce4363854ff888cff4b8e7875d600c2682390412a8cf79b37d0b11148b0fa",".cargo_vcs_info.json":"44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",".hidden/file":"aaa9402664f1a41f40ebbc52c9993eb66aeb366602958fdfaa283b71e64db123","Cargo.toml":"081661433931b8d1143e77c0d196c1fbd138ffff29e458950f1e872429da563e","Cargo.toml.orig":"14e0ffdc8215c81da0cde40f581237ee35177ddac4f1fc7613cad3004798d25f","all":"ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb","deep/er/f":"252f10c83610ebca1a059c0bae8255eba2f95be4d1d7bcfa89d7248a82d9f111","group":"cd0aa9856147b6c5b4ff2b7dfee5da20aa38253099ef1b4a64aced233c9afe29","run.sh":"acba25512100f80b56fc3ccd14c65be55d94800cda77585c5f41a887e398f9be","secret":"043a718774c572bd8a25adbeb1bfcd5c0256ae11cecf9f9c3f925d0e52beaf89","src/lib.rs":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","suid":"0bfe935e70c321c7ca3afc75ce0d0ca2f98b5422e008bb31c00c6d7f1f1c0ad6","x.rej":"bac5c8d4a50988972986f26a62a540e651884ae279aa418e851f77024f5ac409","ünï cödé":"1b16b1df538ba12dc3f97edbb85caa7050d46c148134290feba80f8236c83db9","｡":"7685a5cb2b57c5026f3bcb223275c917ffcaf8c7a89262d68689e0c84802f230","😀":"2e9f768344ff39ac7c1e41218b0a488a0fb666992777f7bfe03d09450df4f5b1"'
const COMMENT = '"$comment":"This file only protects against accidental modifications. It is not a security mechanism and does not protect against malicious changes.",'

describe('buildCargoTree', () => {
  it('unpacks each .crate as cargo vendor does', async () => {
    const weird = await crate('weird', '1.0.0', WEIRD)
    const { vfs, stats } = await build([weird])
    // Cargo passes over what is under a `.git` and the rest before it makes
    // any directory on the way, so `sub` is not made.
    assert.deepEqual(listing(vfs, '/vendor/weird'), {
      '.': 'dir 750',
      '.GIT': 'dir 755',
      '.GIT/y': '644 y',
      '.cargo-checksum.json': '644',
      '.cargo_vcs_info.json': '644 {}',
      '.hidden': 'dir 755',
      '.hidden/file': '644 h',
      'Cargo.toml': `644 ${published('weird', '1.0.0').trimEnd()}`,
      'Cargo.toml.orig': '644 orig',
      all: '755 a',
      deep: 'dir 755',
      'deep/er': 'dir 755',
      'deep/er/f': '644 f',
      group: '644 g',
      only: 'dir 700',
      'run.sh': '755 run',
      secret: '600 s',
      src: 'dir 755',
      'src/lib.rs': '644',
      suid: '755 u',
      'x.rej': '644 rej',
      'ünï cödé': '644 n',
      '\uFF61': '644 bmp',
      '\u{1F600}': '644 astral',
    })
    assert.equal(vfs.lstat('/vendor').mode, 0o755)
    assert.equal(vfs.readText('/vendor/weird/.cargo-checksum.json'), `{${COMMENT}"files":{${WEIRD_SUMS}},"package":"${weird.checksum}"}`)
    assert.deepEqual(stats, { packages: 2, vendored: 1, files: 17, bytes: vfs.readFile('/vendor/weird/.cargo-checksum.json').length + 29 + published('weird', '1.0.0').length })
  })

  it('writes the $comment from cargo 1.97 on, as cargo does', async () => {
    const leaf = await crate('leaf', '1.0.0')
    const text = async (cargo) => (await build([leaf], { host: { ...HOST, cargo } })).vfs.readText('/vendor/leaf/.cargo-checksum.json')
    const files = `"files":{"Cargo.toml":"${sha256(published('leaf', '1.0.0'))}","src/lib.rs":"${sha256('')}"},"package":"${leaf.checksum}"}`
    for (const cargo of ['1.94.0', '1.94.1', '1.95.0', '1.96.0']) assert.equal(await text(cargo), `{${files}`)
    for (const cargo of ['1.97.0', '1.98.1', '1.99.0']) assert.equal(await text(cargo), `{${COMMENT}${files}`)
  })

  it('names each directory after the package, and after its version but for the greatest of a name', async () => {
    const crates = [await crate('dup', '0.1.0'), await crate('dup', '0.2.0'), await crate('dup', '0.10.0-rc.1'), await crate('leaf', '1.0.0')]
    const { vfs, installed } = await build(crates)
    assert.deepEqual(vfs.readdir('/vendor').sort(), ['dup', 'dup-0.1.0', 'dup-0.2.0', 'leaf'])
    assert.equal(vfs.readText('/vendor/dup/Cargo.toml'), published('dup', '0.10.0-rc.1'))
    assert.deepEqual(installed, crates.map((c, i) => ({ path: `vendor/${['dup-0.1.0', 'dup-0.2.0', 'dup', 'leaf'][i]}`, name: c.name, version: c.version, source: CRATES_IO, checksum: c.checksum, commit: undefined })))
  })

  it('lists the commit its .cargo_vcs_info.json names, where cargo found the checkout clean', async () => {
    const sha = 'a'.repeat(40)
    const commitOf = async (text) => (await build([await crate('leaf', '1.0.0', { '.cargo_vcs_info.json': text })])).installed[0].commit
    assert.equal(await commitOf(`{\n  "git": {\n    "sha1": "${sha}"\n  },\n  "path_in_vcs": "leaf"\n}`), sha)
    assert.equal(await commitOf(JSON.stringify({ git: { sha1: 'b'.repeat(64), dirty: false } })), 'b'.repeat(64))
    const none = [{ git: { sha1: sha, dirty: true } }, { git: { sha1: sha, dirty: 'no' } }, { git: { sha1: sha.slice(1) } }, { git: { sha1: sha.toUpperCase() } }, { git: { sha1: [sha] } }, { git: sha }, { sha1: sha }, {}, null]
    for (const text of [...none.map((info) => JSON.stringify(info)), `{"git":{"sha1":"${sha}"`, '']) assert.equal(await commitOf(text), undefined, text)
  })

  it('refuses a package from git or another registry, before anything is fetched', async () => {
    const leaf = await crate('leaf', '1.0.0')
    const other = (source) => `\n[[package]]\nname = "other"\nversion = "1.0.0"\nsource = "${source}"\n${source.startsWith('git') ? '' : `checksum = "${'0'.repeat(64)}"\n`}`
    const refused = async (source, message) => {
      const calls = stubCrates([leaf])
      const app = { ...appOf([leaf]), deps: ['leaf', 'other'] }
      await assert.rejects(buildCargoTree({ lockfile: lockOf([app, leaf], other(source)), manifests: { '.': rootOf([leaf]) }, host: HOST }), message)
      assert.deepEqual(calls, [])
    }
    await refused(`git+https://github.com/o/other?tag=v1#${'a'.repeat(40)}`, /^DeptreeError: packages\["other 1\.0\.0 \(git\+https:\/\/github\.com\/o\/other\?tag=v1#a{40}\)"\]: a git dependency, which cargo vendor checks out with git, is not supported$/u)
    await refused('registry+https://example.com/index', /^DeptreeError: packages\["other 1\.0\.0 \(registry\+https:\/\/example\.com\/index\)"\]: a package from a registry other than crates\.io is not supported$/u)
    await refused('sparse+https://index.crates.io/', /: a package from a registry other than crates\.io is not supported$/u)
  })
})

// A workspace cargo was recorded locking and vendoring: a member a glob takes
// and one a member's path dependency is, an excluded path dependency, fields
// and a dependency inherited, a [patch] from a path, and a dev-dependency of a
// package that is no member, which cargo does not read.
async function workspace() {
  const crates = [await crate('dup', '0.1.0'), await crate('dup', '0.2.0')]
  const files = {
    'Cargo.toml': '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[workspace]\nmembers = ["crates/*"]\nexclude = ["crates/extra", "patched"]\n\n[workspace.package]\nversion = "0.2.0"\nedition = "2021"\n\n[workspace.dependencies]\ndup = "0.2"\n\n[dependencies]\nlib = { path = "crates/lib" }\ndup = { workspace = true }\n\n[patch.crates-io]\nleaf = { path = "patched" }\n',
    'crates/lib/Cargo.toml': '[package]\nname = "lib"\nversion.workspace = true\nedition.workspace = true\n\n[dependencies]\nextra = { path = "../extra" }\ninner = { path = "inner" }\n\n[dev-dependencies]\ndup01 = { package = "dup", version = "0.1" }\n',
    'crates/lib/inner/Cargo.toml': '[package]\nname = "inner"\nversion = "0.0.1"\nedition.workspace = true\n',
    'crates/extra/Cargo.toml': '[package]\nname = "extra"\nversion = "0.3.0"\nedition = "2021"\n\n[dependencies]\nleaf = "1"\n\n[dev-dependencies]\nnowhere = { path = "../nowhere" }\n',
    'patched/Cargo.toml': '[package]\nname = "leaf"\nversion = "1.0.5"\nedition = "2021"\n',
  }
  const packages = [
    { name: 'app', version: '0.1.0', deps: ['dup 0.2.0', 'lib'] }, crates[0], crates[1],
    { name: 'extra', version: '0.3.0', deps: ['leaf'] }, { name: 'inner', version: '0.0.1' }, { name: 'leaf', version: '1.0.5' },
    { name: 'lib', version: '0.2.0', deps: ['dup 0.1.0', 'extra', 'inner'] },
  ]
  return { crates, files, packages, lockfile: lockOf(packages) }
}

const manifestsOf = (files) => Object.fromEntries(Object.entries(files).filter(([path]) => path.endsWith('Cargo.toml')).map(([path, text]) => [path === 'Cargo.toml' ? '.' : path.slice(0, -'/Cargo.toml'.length), text]))

describe('a workspace', () => {
  it('is read as cargo reads it, from the project or as given', async () => {
    const { crates, files, lockfile } = await workspace()
    const project = await read(crates, { ...files, 'Cargo.lock': lockfile, 'crates/lib/src/lib.rs': '' })
    assert.deepEqual(project.installed.map(({ path }) => path), ['vendor/dup-0.1.0', 'vendor/dup'])
    assert.deepEqual(project.stats, { packages: 7, vendored: 2, files: 6, bytes: project.stats.bytes })
    const given = await build(crates, { lockfile, manifests: manifestsOf(files) })
    assert.deepEqual(listing(given.vfs, '/vendor'), listing(project.vfs, '/vendor'))
  })

  it('is held to the lockfile, as cargo would resolve anew one out of date', async () => {
    const { crates, files, packages, lockfile } = await workspace()
    const refused = (lock, changed, message) => assert.rejects(build(crates, { lockfile: lock, manifests: manifestsOf({ ...files, ...changed }) }), message)
    await refused(lockfile, { 'crates/lib/inner/Cargo.toml': '[package]\nname = "inner"\nversion = "0.0.1"\nedition.workspace = true\n\n[dependencies]\ndup = "0.1"\n' }, LockfileError)
    await refused(lockfile, { 'crates/lib/inner/Cargo.toml': '[package]\nname = "inner"\nversion = "0.0.2"\nedition.workspace = true\n' }, /^DeptreeError: crates\/lib\/inner\/Cargo\.toml: the lockfile has no member "inner 0\.0\.2": is it out of date\?$/u)
    await refused(lockOf(packages, '\n[[package]]\nname = "ghost"\nversion = "1.0.0"\n'), {}, /^DeptreeError: packages\["ghost 1\.0\.0"\]: a path package that no manifest cargo reads here is: is the lockfile out of date\?$/u)
    // Two packages of one name: the lockfile ties each path dependency to the
    // package its path leads to, not the other.
    const swapped = [...packages.filter((p) => p.name !== 'app' && p.name !== 'lib'), { name: 'app', version: '0.1.0', deps: ['dup 0.2.0', 'inner 0.0.1', 'lib'] }, { name: 'inner', version: '0.0.2' }, { name: 'lib', version: '0.2.0', deps: ['dup 0.1.0', 'extra', 'inner 0.0.2'] }]
    const app = files['Cargo.toml'].replace('"patched"]', '"patched", "other"]').replace('[dependencies]\n', '[dependencies]\nother = { package = "inner", path = "other" }\n')
    await refused(lockOf(swapped), { 'Cargo.toml': app, 'other/Cargo.toml': '[package]\nname = "inner"\nversion = "0.0.2"\nedition = "2021"\n' }, /^DeptreeError: crates\/lib\/Cargo\.toml: dependencies\.inner: the lockfile resolves it to "inner 0\.0\.2", not "inner 0\.0\.1", which its path leads to$/u)
  })

  it('refuses what cargo refuses of one, and what it reads otherwise than this', async () => {
    const { crates, files, lockfile } = await workspace()
    const refused = (changed, message) => assert.rejects(read(crates, { ...files, ...changed, 'Cargo.lock': lockfile }), message)
    const root = files['Cargo.toml']
    await refused({ 'Cargo.toml': root.replace('crates/*', 'crates/*x') }, /^DeptreeError: Cargo\.toml: workspace\.members\[0\]: "crates\/\*x" takes nothing, which cargo fails on$/u)
    await refused({ 'crates/.cache/notes': '' }, /^DeptreeError: Cargo\.toml: workspace\.members: "crates\/\.cache\/Cargo\.toml" is not there, which cargo fails on$/u)
    for (const glob of ['crates/**', 'crates/[a-z]*']) await refused({ 'Cargo.toml': root.replace('crates/*', glob) }, /^DeptreeError: Cargo\.toml: workspace\.members\[0\]: ".*" has a `\*\*` or a `\[`, which is not supported$/u)
    await refused({ 'Cargo.toml': root.replace('crates/*', '../crates/*') }, /leads out of the root, which is not read$/u)
    await refused({ 'Cargo.toml': root.replace('crates/*', '/crates/*') }, /is not a relative path within the project, which is all that is read$/u)
    await refused({ 'crates/lib/inner/Cargo.toml': `${files['crates/lib/inner/Cargo.toml']}\n[workspace]\n` }, /^DeptreeError: crates\/lib\/inner\/Cargo\.toml: a member with a \[workspace\] of its own, which cargo refuses$/u)
    await refused({ 'crates/Cargo.toml': '[workspace]\n' }, /^DeptreeError: crates\/Cargo\.toml: a \[workspace\] between a package and the root, one workspace in another, is not supported$/u)
    await refused({ 'patched/Cargo.toml': `${files['patched/Cargo.toml'].replace('[package]\n', '[package]\nworkspace = "../crates"\n')}` }, /^DeptreeError: patched\/Cargo\.toml: package\.workspace: a package\.workspace pointing elsewhere than the root is not supported$/u)
    await refused({ 'Cargo.toml': root.replace('[package]\n', '[package]\nworkspace = ".."\n') }, /^DeptreeError: Cargo\.toml: package\.workspace: a root that points to a workspace above it/u)
    await refused({ 'Cargo.toml': root.replace('exclude = [', 'exclude = ["", ') }, /^DeptreeError: Cargo\.toml: workspace\.exclude: the root is excluded from its own workspace, which cargo refuses$/u)
    await refused({ 'Cargo.toml': root.replace('[workspace.package]', 'default-members = ["crates/extra", "patched"]\n\n[workspace.package]') }, /^DeptreeError: Cargo\.toml: workspace\.default-members: "patched" is no member, which cargo refuses$/u)
    await refused({ 'Cargo.toml': root.replace('crates/lib', '../lib') }, /^DeptreeError: Cargo\.toml: dependencies\.lib: "\.\.\/lib" leads out of the project, which is not read$/u)
    await refused({ 'Cargo.toml': root.replace('"crates/lib"', '"crates/extra/../lib"') }, /^DeptreeError: Cargo\.toml: dependencies\.lib: "crates\/extra\/\.\.\/lib" has a `\.\.` after a name, which is not supported$/u)
    await refused({ 'patched/Cargo.toml': files['patched/Cargo.toml'].replace('"leaf"', '"leafy"') }, /^DeptreeError: Cargo\.toml: patch\."crates-io"\.leaf: "patched\/Cargo\.toml" is of "leafy", not "leaf", which cargo fails on$/u)
    await refused({ 'crates/extra/Cargo.toml': '[workspace]\n' }, /^DeptreeError: crates\/extra\/Cargo\.toml: a manifest with no \[package\], which cargo fails on as a path dependency$/u)
    await refused({ 'crates/lib/Cargo.toml': files['crates/lib/Cargo.toml'].replace('"inner"', '"gone"') }, /^DeptreeError: crates\/lib\/Cargo\.toml: dependencies\.inner: "crates\/lib\/gone\/Cargo\.toml" is not there, which cargo fails on$/u)
    await refused({ 'crates/lib/Cargo.toml': `${files['crates/lib/Cargo.toml']}x = \n` }, /^DeptreeError: crates\/lib\/Cargo\.toml: /u)
    await refused({ 'crates/link': { type: 'symlink', target: 'lib' } }, /^DeptreeError: "crates\/link": a link where cargo looks for members is not supported$/u)
    await refused({ 'crates/lib/real.toml': files['crates/lib/Cargo.toml'], 'crates/lib/Cargo.toml': { type: 'symlink', target: 'real.toml' } }, /^DeptreeError: "crates\/lib\/Cargo\.toml": a link where cargo reads a manifest is not supported$/u)
    await assert.rejects(read(crates, { ...files, 'real.lock': lockfile, 'Cargo.lock': { type: 'symlink', target: 'real.lock' } }), /^DeptreeError: "Cargo\.lock": a link where cargo reads its lockfile is not supported$/u)
    // The default member excluded but taken by `members` is one cargo takes.
    const defaults = root.replace('[workspace.package]', 'default-members = ["crates/extra", "crates/lib"]\n\n[workspace.package]')
    assert.equal((await read(crates, { ...files, 'Cargo.toml': defaults, 'Cargo.lock': lockfile })).stats.vendored, 2)
  })

  it('reads a [patch] from .cargo/config.toml, or .cargo/config where it is', async () => {
    const { crates, files, lockfile } = await workspace()
    const root = files['Cargo.toml'].replace('\n[patch.crates-io]\nleaf = { path = "patched" }\n', '')
    const patch = '[patch.crates-io]\nleaf = { path = "patched" }\n'
    const run = (extra) => read(crates, { ...files, 'Cargo.toml': root, 'Cargo.lock': lockfile, ...extra })
    assert.equal((await run({ '.cargo/config.toml': patch })).stats.vendored, 2)
    assert.equal((await run({ '.cargo/config': patch, '.cargo/config.toml': '[patch.crates-io]\nleaf = { path = "nowhere" }\n' })).stats.vendored, 2)
    await assert.rejects(run({}), /^DeptreeError: packages\["leaf 1\.0\.5"\]: a path package that no manifest cargo reads here is: is the lockfile out of date\?$/u)
    await assert.rejects(run({ '.cargo/config.toml': `paths = ["x"]\n${patch}` }), /^DeptreeError: \.cargo\/config\.toml: paths: not supported$/u)
    await assert.rejects(run({ '.cargo/config.toml': `include = ["x.toml"]\n${patch}` }), /^DeptreeError: \.cargo\/config\.toml: include: not supported$/u)
    await assert.rejects(run({ '.cargo/config.toml': 'x = \n' }), /^DeptreeError: \.cargo\/config\.toml: /u)
    await assert.rejects(run({ '.cargo/real.toml': patch, '.cargo/config.toml': { type: 'symlink', target: 'real.toml' } }), /^DeptreeError: "\.cargo\/config\.toml": a link where cargo reads its config is not supported$/u)
    await assert.rejects(run({ 'cfg/config.toml': patch, '.cargo': { type: 'symlink', target: 'cfg' } }), /^DeptreeError: "\.cargo": a link where cargo reads its config is not supported$/u)
    stubCrates(crates)
    assert.equal((await buildCargoTree({ lockfile, manifests: manifestsOf({ ...files, 'Cargo.toml': root }), config: patch, host: HOST })).stats.vendored, 2)
  })
})

// A .crate of a Cargo.toml and src/lib.rs, then `raw` entries as they are,
// which pack would not write.
async function rawCrate(name, version, raw) {
  const top = `${name}-${version}`
  return gzipped(name, version, await compress(rawTar([{ name: `${top}/Cargo.toml`, data: published(name, version) }, { name: `${top}/src/lib.rs`, data: '' }, ...raw]), 'gzip'))
}

describe('a .crate', () => {
  const refused = async (made, message) => assert.rejects(build([await made]), message)

  it('refuses what cargo refuses or fails on, or reads otherwise than the archive reader', async () => {
    await refused(crate('bad', '1.0.0', {}, { entries: [{ name: 'bad-1.0.0x/a', data: new Uint8Array() }] }), /^DeptreeError: packages\["bad 1\.0\.0 \(registry\+https:\/\/github\.com\/rust-lang\/crates\.io-index\)"\]: "bad-1\.0\.0x\/a": not under "bad-1\.0\.0", which cargo refuses$/u)
    await refused(rawCrate('bad', '1.0.1', [{ name: './bad-1.0.1/a', data: 'a' }]), /: "\.\/bad-1\.0\.1\/a": not under "bad-1\.0\.1", which cargo refuses$/u)
    await refused(crate('bad', '1.0.2', { link: { type: 'symlink', linkname: 'src/lib.rs' } }), /: "bad-1\.0\.2\/link": a symlink, which cargo refuses$/u)
    await refused(crate('bad', '1.0.3', { hard: { type: 'hardlink', linkname: 'bad-1.0.3/src/lib.rs' } }), /: "bad-1\.0\.3\/hard": a hardlink, which cargo refuses$/u)
    await refused(crate('bad', '1.0.4', { cont: { type: 'contiguous-file', data: 'c' } }), /: "bad-1\.0\.4\/cont": a contiguous-file, which cargo refuses$/u)
    await refused(crate('bad', '1.0.5', { '.cargo-checksum.json': '{}' }), /: "bad-1\.0\.5\/\.cargo-checksum\.json": a \.cargo-checksum\.json of its own, which cargo vendor lists and then writes over, so that cargo cannot build from it$/u)
    await refused(gzipped('bad', '1.0.8', await compress(rawTar([{ name: 'bad-1.0.8', data: 'x' }]), 'gzip')), /: "bad-1\.0\.8": the package's directory is not a directory$/u)
    await refused(rawCrate('bad', '1.0.9', [{ name: 'bad-1.0.9/a\\b', data: 'x' }]), /: the \.crate cannot be read: /u)
  })

  // As cargo 1.97 was recorded vendoring each, run as a user but root: an
  // empty directory of any mode, and one whose mode comes after what is in it,
  // are as root has them; one that cannot be listed is left out of the
  // checksums, and one written into after its mode is set fails, as does a
  // package's directory that cannot be written into.
  it('takes a directory\'s mode where it keeps cargo from nothing, as any user but root', async () => {
    const modes = async (version, files) => {
      const { vfs } = await build([await crate('modes', version, files)])
      return Object.fromEntries(Object.entries(listing(vfs, '/vendor/modes')).filter(([path]) => !/^(?:src|Cargo\.toml|\.cargo-checksum\.json)/u.test(path)))
    }
    assert.deepEqual(await modes('1.0.0', { ro: { type: 'directory', mode: 0o555 }, none: { type: 'directory', mode: 0o000 } }), { '.': 'dir 755', ro: 'dir 555', none: 'dir 0' })
    assert.deepEqual(await modes('1.0.1', { 'ro/x': 'x', ro: { type: 'directory', mode: 0o555 } }), { '.': 'dir 755', ro: 'dir 555', 'ro/x': '644 x' })
    assert.deepEqual(await modes('1.0.2', { '': { type: 'directory', mode: 0o700 } }), { '.': 'dir 700' })
    await refused(crate('modes', '1.0.3', { 'd/x': 'x', d: { type: 'directory', mode: 0o311 } }), /: "modes-1\.0\.3\/d\/": mode 311, which keeps cargo from listing what is in it as any user but root, is not supported$/u)
    await refused(crate('modes', '1.0.4', { '': { type: 'directory', mode: 0o555 } }), /: "modes-1\.0\.4\/": mode 555, which keeps cargo from writing into it what comes after it as any user but root, is not supported$/u)
    await refused(crate('modes', '1.0.5', { ro: { type: 'directory', mode: 0o555 }, 'ro/x': 'x' }), /: "modes-1\.0\.5\/ro\/": mode 555, which keeps cargo from writing into it what comes after it as any user but root, is not supported$/u)
    await refused(crate('modes', '1.0.6', { wo: { data: 'w', mode: 0o200 } }), /: "modes-1\.0\.6\/wo": mode 200, which keeps cargo from reading it back to checksum it as any user but root, is not supported$/u)
  })

  it('passes over what cargo vendor passes over before it looks at its type', async () => {
    const files = { '.git/link': { type: 'symlink', linkname: '../src/lib.rs' }, '.cargo-ok': { type: 'symlink', linkname: 'src/lib.rs' }, '.gitignore': { type: 'symlink', linkname: 'src/lib.rs' }, 'sub/.cargo-ok/f': 'f' }
    const { vfs } = await build([await crate('skips', '1.0.0', files)])
    assert.deepEqual(Object.keys(listing(vfs, '/vendor/skips')).sort(), ['.', '.cargo-checksum.json', 'Cargo.toml', 'src', 'src/lib.rs', 'sub', 'sub/.cargo-ok', 'sub/.cargo-ok/f'])
    await assert.rejects(build([await crate('skips', '1.0.1', { 'sub/.cargo-ok': { type: 'symlink', linkname: '../src/lib.rs' } })]), /: "skips-1\.0\.1\/sub\/\.cargo-ok": a symlink, which cargo refuses$/u)
  })

  it('refuses a gzip cargo reads otherwise than the platform: more than one member, a header CRC, a pax size', async () => {
    const one = await crate('gz', '1.0.0')
    const second = await compress(pack([{ name: 'gz-1.0.0/more', data: encoder.encode('more') }]), 'gzip')
    const refusedBytes = (bytes, message) => assert.rejects(build([gzipped('gz', '1.0.0', bytes)]), message)
    await refusedBytes(new Uint8Array([...one.bytes, ...second]), /: the \.crate is not one gzip member, which cargo reads the first of alone$/u)
    await refusedBytes(new Uint8Array([...one.bytes, 0, 0, 0, 0]), /: the \.crate is not one gzip member/u)
    const crc = new Uint8Array(one.bytes)
    crc[3] |= 0x02
    await refusedBytes(crc, /: a gzip header with a header CRC or a reserved flag is not supported$/u)
    for (const at of [8, 1]) {
      const trailer = new Uint8Array(one.bytes)
      trailer[trailer.length - at] ^= 1
      await refusedBytes(trailer, /: the \.crate's gzip trailer does not match its data$/u)
    }
    await refusedBytes(encoder.encode('not gzip at all, not at all'), /: the \.crate is not gzipped$/u)
    // A pax size, even one the header agrees with, which tar 0.4.44 reads
    // where the header's is 0 alone.
    const sized = await rawCrate('gz', '1.0.0', [{ name: 'PaxHeader/p', data: '9 size=1\n', type: 'x' }, { name: 'gz-1.0.0/p', data: 'p' }])
    await refusedBytes(sized.bytes, /: "gz-1\.0\.0\/p": a pax size, which cargo 1\.94\.0 reads otherwise, is not supported$/u)
    // A long name is a pax path, which cargo reads alike.
    const long = await crate('gz', '1.0.1', { [`${'n'.repeat(120)}`]: 'n' })
    assert.equal((await build([long])).vfs.readText(`/vendor/gz/${'n'.repeat(120)}`), 'n')
  })

  it('is held to the lockfile\'s checksum', async () => {
    const leaf = await crate('leaf', '1.0.0')
    const other = await crate('leaf', '1.0.0', { more: 'x' })
    await assert.rejects(build([{ ...leaf, served: other.bytes }]), /^DeptreeError: packages\["leaf 1\.0\.0 \(registry\+https:\/\/github\.com\/rust-lang\/crates\.io-index\)"\]: /u)
  })

  it('refuses on macOS two names that are one there', async () => {
    const cased = await crate('cased', '1.0.0', { 'A.rs': 'a', 'a.rs': 'b' })
    await build([cased])
    await assert.rejects(build([cased], { host: { ...HOST, os: 'darwin' } }), /^DeptreeError: "\/vendor\/cased": "A\.rs" and "a\.rs" are one name on macOS$/u)
  })
})

describe('fetching', () => {
  it('fetches eight .crates at a time', async () => {
    const crates = await Promise.all(Array.from({ length: 12 }, (_, i) => crate(`pkg-${String.fromCodePoint(108 - i)}`, '1.0.0', { a: String(i) })))
    stubCrates(crates)
    const count = slowed(5)
    const { stats } = await buildCargoTree(givenOf(crates))
    assert.equal(count.most, 8)
    assert.equal(stats.vendored, 12)
  })

  it('refuses once every fetch started has ended', async () => {
    const crates = [await crate('aaa', '1.0.0'), await crate('bbb', '1.0.0')]
    stubCrates(crates)
    const count = slowed(20, (input) => (input.includes('/aaa/') ? Response.json({ errors: [] }, { status: 404 }) : undefined))
    await assert.rejects(buildCargoTree(givenOf(crates)), /^DeptreeError: packages\["aaa 1\.0\.0 /u)
    assert.equal(count.open, 0)
  })
})

describe('buildCargoTree\'s options', () => {
  it('takes the host, the files and the Vfs it is given, and nothing else', async () => {
    const leaf = await crate('leaf', '1.0.0')
    for (const cargo of ['1.93.0', '1.100.0', '1.97', '1.97.0-nightly']) await assert.rejects(build([leaf], { host: { ...HOST, cargo } }), /^DeptreeError: host\.cargo: cargo ".*" is not supported: only cargo 1\.94\.0 to 1\.99\.x are$/u)
    await assert.rejects(build([leaf], { host: { ...HOST, os: 'win32' } }), /^DeptreeError: host\.os: Windows is not supported/u)
    await assert.rejects(buildCargoTree({ host: HOST }), TypeError)
    await assert.rejects(buildCargoTree({ lockfile: lockOf([appOf([leaf]), leaf]), host: HOST }), TypeError)
    await assert.rejects(build([leaf], { config: 1 }), TypeError)
    await assert.rejects(build([leaf], { manifests: { '.': rootOf([leaf]), '../x': '' } }), /^DeptreeError: manifests\["\.\.\/x"\]: not a directory below the root, as it is named here$/u)
    await assert.rejects(build([leaf], { manifests: { '.': rootOf([leaf]), unread: '[package]\nname = "unread"\nversion = "1.0.0"\n' } }), /^DeptreeError: manifests\["unread"\]: given, but no manifest cargo reads$/u)
    await assert.rejects(build([leaf], { lockfile: 'version = 9\n' }), LockfileError)
    await assert.rejects(build([leaf], { lockfile: 'x = ' }), TomlError)
    await assert.rejects(build([leaf], { manifests: { '.': 'x = ' } }), /^DeptreeError: Cargo\.toml: /u)

    const project = createVfs({ 'Cargo.toml': rootOf([leaf]), 'Cargo.lock': lockOf([appOf([leaf]), leaf]), src: { type: 'directory' } })
    stubCrates([leaf])
    const { vfs } = await buildCargoTree({ project, host: HOST, vfs: project })
    assert.equal(vfs, project)
    assert.deepEqual(project.readdir('/').sort(), ['Cargo.lock', 'Cargo.toml', 'src', 'vendor'])
    assert.equal(project.readText('/vendor/leaf/Cargo.toml'), published('leaf', '1.0.0'))
    await assert.rejects(buildCargoTree({ project, host: HOST, vfs: project }), /^DeptreeError: vfs\["\/vendor"\]: a vendor directory is there already, which is neither kept beside the tree nor removed$/u)
    await assert.rejects(buildCargoTree({ project: createVfs({ 'Cargo.toml': rootOf([leaf]), 'Cargo.lock': lockOf([appOf([leaf]), leaf]) }), host: { ...HOST, os: 'darwin' }, vfs: createVfs({ Vendor: { type: 'directory' } }) }), /^DeptreeError: vfs\["\/Vendor"\]: a vendor directory is there already/u)
    project.unlink('/Cargo.lock')
    await assert.rejects(buildCargoTree({ project, host: HOST }), /^DeptreeError: the project has no Cargo\.lock, without which cargo resolves every dependency anew$/u)
  })

  it('makes no vendor directory where every package is a path one, as cargo makes none', async () => {
    const calls = stubCrates([])
    const { vfs, stats, installed } = await buildCargoTree(givenOf([]))
    assert.deepEqual([vfs.readdir('/'), stats, installed, calls], [[], { packages: 1, vendored: 0, files: 0, bytes: 0 }, [], []])
  })
})

// The semver crate's order, which picks the version a name alone is for.
describe('vendoredPackages', () => {
  const greatest = (versions) => {
    const packages = Object.fromEntries(versions.map((version) => [`x ${version} (${CRATES_IO})`, { name: 'x', version, source: CRATES_IO, checksum: '0'.repeat(64) }]))
    return vendoredPackages({ packages }).find((pkg) => pkg.directory === 'x').version
  }

  it('gives the name alone to the greatest version, a pre-release as the semver crate orders it', () => {
    const ordered = ['1.0.0-alpha', '1.0.0-alpha.1', '1.0.0-alpha.beta', '1.0.0-beta', '1.0.0-beta.2', '1.0.0-beta.11', '1.0.0-rc.1', '1.0.0']
    for (let i = 1; i <= ordered.length; i++) {
      assert.equal(greatest(ordered.slice(0, i).toReversed()), ordered[i - 1])
      assert.equal(greatest(ordered.slice(0, i)), ordered[i - 1])
    }
    assert.equal(greatest(['0.2.0', '0.10.0-rc.1', '0.9.9']), '0.10.0-rc.1')
    assert.equal(greatest(['18446744073709551615.0.0', '18446744073709551614.9.9']), '18446744073709551615.0.0')
    assert.equal(greatest(['1.0.0-2', '1.0.0-10', '1.0.0-a']), '1.0.0-a')
    assert.equal(greatest(['1.0.0-10', '1.0.0-9']), '1.0.0-10')
    assert.throws(() => greatest(['1.0.0+a', '1.0.0+b']), (error) => error instanceof DeptreeError && /differ only in build metadata/u.test(error.message))
  })
})
