import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { afterEach, describe, it } from 'node:test'
import { compress, decompress } from '@preventive/archive/compression.js'
import { createVfs } from '@preventive/vfs'
import { DeptreeError, LockfileError, buildYarn1Tree, findYarn1Workspaces } from '../yarn1.js'
import { paths, sri, stubFailingRegistry, stubRegistry, tarball } from './registry.js'

// Small projects whose yarn.lock real yarn 1.22.22 wrote, and whose trees
// it installed as the first tests expect, from the tarballs made here;
// then one change at a time, each refused with where and why.

const realFetch = globalThis.fetch
afterEach(() => { globalThis.fetch = realFetch })

const HOST = Object.freeze({ yarn: '1.22.22', node: '24.15.0', os: 'linux', cpu: 'x64' })

// As some packers write one, with a `.` segment pack() would clean: the
// `_` in `name` made `.` in place, and the header's checksum made again.
async function dotted(packed, name) {
  const tar = await decompress(packed.bytes, 'gzip', { limit: 1 << 24 })
  const encoded = new TextEncoder().encode(name)
  let at = 0
  while (!encoded.every((byte, i) => tar[at + i] === byte)) at += 512
  tar[at + name.indexOf('_')] = 0x2e
  tar.fill(0x20, at + 148, at + 156)
  const sum = tar.subarray(at, at + 512).reduce((a, b) => a + b, 0)
  tar.set(new TextEncoder().encode(`${sum.toString(8).padStart(6, '0')}\0 `), at + 148)
  const bytes = await compress(tar, 'gzip')
  return { ...packed, bytes, integrity: sri(bytes) }
}

const TARBALLS = await Promise.all([
  tarball('a', '1.0.0', { 'bin/a.js': { data: '#!/usr/bin/env node\n', mode: 0o644 }, 'x.sh': { data: 'x', mode: 0o700 }, '.bin/hidden': 'hidden' }, { manifest: { dependencies: { b: '^1.0.0' }, bin: { a: 'bin/a.js' } } }),
  tarball('b', '1.0.0', { 'index.js': 'b1' }),
  tarball('b', '2.0.0', { 'index.js': 'b2' }),
  tarball('c', '1.0.0', { 'cli.js': { data: 'c', mode: 0o600 } }, { manifest: { bin: 'cli.js' } }),
  tarball('d', '1.0.0'),
  tarball('eng', '1.0.0', {}, { manifest: { engines: { node: '>=100' } } }),
  tarball('@s/e', '1.0.0'),
  tarball('x', '1.0.0', {}, { manifest: { dependencies: { mac: 'latest' } } }),
  dotted(await tarball('fix', '1.0.0', { '_/lib/x.js': 'x', 'test/node_modules/fixture.js': 'f' }), 'package/_/lib/x.js'),
  tarball('mac', '1.0.0', {}, { manifest: { os: ['darwin'] } }),
  tarball('loop1', '2.0.0', { 'run.js': { data: 'r', mode: 0o600 }, 'more.js': { data: 'm', mode: 0o600 } }, { manifest: { bin: { loop1: 'run.js', more: 'more.js/' }, dependencies: { loop2: '1.1.0' } } }),
  tarball('loop2', '1.1.0', {}, { manifest: { dependencies: { loop1: '^2.0.0' } } }),
  tarball('dotbin', '1.0.0', { '.bin': 'x', 'cli.js': 'c' }, { manifest: { bin: 'cli.js' } }),
  tarball('inner', '1.0.0', {}, { manifest: { bin: 'node_modules/b/index.js', dependencies: { b: '^1.0.0' } } }),
  tarball('shadow', '1.0.0', { 'Node_Modules/b/index.js': 'b' }, { manifest: { dependencies: { b: '^1.0.0' } } }),
  tarball('p', '1.0.0', {}, { manifest: { peerDependencies: { b: '^2.0.0' } } }),
  tarball('q', '1.0.0', {}, { manifest: { dependencies: { b: '^1.0.0' } } }),
  tarball('aab', '1.0.0'),
  tarball('ab', '1.0.0'),
])
const T = Object.fromEntries(TARBALLS.map((t) => [`${t.name}@${t.version}`, t]))
const sha1 = (bytes) => createHash('sha1').update(bytes).digest('hex')

const yarnpkg = (name, version) => `https://registry.yarnpkg.com/${name}/-/${name.split('/').at(-1)}-${version}.tgz`
const entry = (keys, id, dependencies = '', { hash = sha1(T[id].bytes), url = yarnpkg } = {}) => {
  const { name, version, integrity } = T[id]
  return `${keys}:
  version "${version}"
  resolved "${url(name, version)}#${hash}"
  integrity ${integrity}
${dependencies}`
}
// An entry as yarn writes one where the registry had no sha512: a sha1 of
// its shasum for the integrity; `of` the tarball whose hashes it has.
const sha1Entry = (keys, id, of = id) => entry(keys, id, '', { hash: sha1(T[of].bytes) }).replace(T[id].integrity, sri(T[of].bytes, 'sha1'))
// The registry, `id` published at `time`, or at no time it gives.
const publishedAt = (time, id = 'b@1.0.0', more = []) => stubRegistry([...TARBALLS.map((t) => (t === T[id] ? { ...t, published: time } : t)), ...more])
const OLD = '2017-09-12T19:21:59.050Z'
const exactly = (message) => new RegExp(`^${RegExp.escape(message)}$`, 'u')
const lockfile = (...entries) => `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


${entries.join('\n')}`

const A = entry('a@^1.0.0', 'a@1.0.0', '  dependencies:\n    b "^1.0.0"\n')
const LOCKFILE = lockfile(
  A,
  entry('b@^1.0.0', 'b@1.0.0'),
  entry('b@^2.0.0', 'b@2.0.0'),
  entry('d@latest', 'd@1.0.0'),
  entry('mac@1.0.0', 'mac@1.0.0'),
  entry('"my-c@npm:c@1.0.0"', 'c@1.0.0'),
  entry('p@1.0.0', 'p@1.0.0'),
)
const ROOT = {
  name: 'root',
  version: '1.0.0',
  dependencies: { a: '^1.0.0', b: '^2.0.0', 'my-c': 'npm:c@1.0.0', p: '1.0.0' },
  devDependencies: { d: 'latest' },
  optionalDependencies: { mac: '1.0.0' },
}

const projectOf = (files) => createVfs(Object.fromEntries(Object.entries(files).map(([path, text]) => [path, typeof text === 'string' ? text : JSON.stringify(text)])))
const project = (files = {}) => projectOf({ 'yarn.lock': LOCKFILE, 'package.json': ROOT, ...files })
const build = (options = {}) => buildYarn1Tree({ project: project(), host: HOST, ...options })
// b@^1.0.0, by sha1Entry's.
const sha1Project = (of) => ({ project: projectOf({ 'yarn.lock': lockfile(sha1Entry('b@^1.0.0', 'b@1.0.0', of)), 'package.json': { name: 'root', version: '1.0.0', dependencies: { b: '^1.0.0' } } }) })

// The root asks for a tag, and its workspace w for another.
const twoTagsManifests = ([top, nested], root = {}) => ({
  '.': { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { [top]: 'latest' }, ...root },
  'packages/w': { name: 'w', version: '1.0.0', dependencies: { [nested]: 'latest' } },
})
const twoTags = (names, lock, root, files = {}) => {
  const { '.': manifest, 'packages/w': w } = twoTagsManifests(names, root)
  return { project: projectOf({ 'yarn.lock': lock, 'package.json': manifest, 'packages/w/package.json': w, ...files }) }
}
const TAGS_APART = lockfile(entry('d@latest', 'd@1.0.0'), entry('p@latest', 'p@1.0.0'))

// q asks for d@next beside the root's d@latest: two entries of d, which
// share a uid, and so a place in yarn's cache.
const Q = await tarball('q', '1.0.0', {}, { manifest: { dependencies: { d: 'next' } } })
const Q_ENTRY = `q@1.0.0:\n  version "1.0.0"\n  resolved "${yarnpkg('q', '1.0.0')}#${sha1(Q.bytes)}"\n  integrity ${Q.integrity}\n  dependencies:\n    d next\n`
const dEntry = (keys, integrity, hash = '') => `${keys}:\n  version "1.0.0"\n  uid "1.0.0-u"\n  resolved "${yarnpkg('d', '1.0.0')}${hash}"\n  integrity ${integrity}\n`
const withQ = (latest, next) => ({ project: project({ 'yarn.lock': LOCKFILE.replace(entry('d@latest', 'd@1.0.0'), [latest, next, Q_ENTRY].join('\n')), 'package.json': { ...ROOT, dependencies: { ...ROOT.dependencies, q: '1.0.0' } } }) })
const mode = (vfs, path) => vfs.stat(path).mode

describe('buildYarn1Tree', () => {
  it('builds the tree yarn 1.22 installs', async () => {
    const calls = stubRegistry(TARBALLS)
    const { vfs, stats } = await build()
    assert.equal(calls.length, 7, 'every package, the one the host cannot run among them, as yarn fetches all before it checks any')
    assert.deepEqual(vfs.readdir('/node_modules'), ['a', 'b', 'd', 'my-c', 'p'])
    assert.deepEqual(vfs.readdir('/node_modules/a'), ['bin', 'node_modules', 'package.json', 'x.sh'])
    assert.deepEqual(vfs.readdir('/node_modules/a/node_modules'), ['b'])
    assert.equal(vfs.readText('/node_modules/a/node_modules/b/index.js'), 'b1')
    assert.equal(vfs.readText('/node_modules/b/index.js'), 'b2')
    assert.equal(mode(vfs, '/node_modules/a/bin/a.js'), 0o755)
    assert.equal(mode(vfs, '/node_modules/a/x.sh'), 0o744)
    assert.equal(mode(vfs, '/node_modules/my-c/cli.js'), 0o755)
    assert.equal(mode(vfs, '/node_modules/a/package.json'), 0o644)
    assert.ok(stats.bytes > 0)
    assert.deepEqual({ ...stats, bytes: 0 }, { packages: 7, skipped: 1, installed: 6, files: 11, bytes: 0, links: 0 })
  })

  it('lists what it installs, as an SBOM would take it', async () => {
    stubRegistry(TARBALLS)
    const listed = (path, id, { dev = false, optional = false } = {}) => ({ path, name: T[id].name, version: T[id].version, integrity: T[id].integrity, dev, optional })
    const { installed } = await build()
    assert.deepEqual(installed, [
      listed('node_modules/a', 'a@1.0.0'),
      listed('node_modules/a/node_modules/b', 'b@1.0.0'),
      listed('node_modules/b', 'b@2.0.0'),
      listed('node_modules/d', 'd@1.0.0', { dev: true }),
      listed('node_modules/my-c', 'c@1.0.0'),
      listed('node_modules/p', 'p@1.0.0'),
    ])
    const ignored = await buildYarn1Tree({ project: project({ '.yarnrc': '--ignore-platform true\n' }), host: HOST })
    assert.deepEqual(ignored.installed.find(({ name }) => name === 'mac'), listed('node_modules/mac', 'mac@1.0.0', { optional: true }))
  })

  // d is w's devDependency alone; b 1.0.0 is copied beneath a, for a, and
  // beneath w's link, where it really is in w's own node_modules, for w's
  // devDependency alone.
  it('lists as dev only what dev dependencies alone reach, a workspace\'s among them', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { b: '^2.0.0' } }
    const w = { name: 'w', version: '1.0.0', dependencies: { a: '1.0.0' }, devDependencies: { b: '^1.0.0', d: 'latest' } }
    const lock = lockfile(entry('a@1.0.0', 'a@1.0.0', '  dependencies:\n    b "^1.0.0"\n'), entry('b@^1.0.0', 'b@1.0.0'), entry('b@^2.0.0', 'b@2.0.0'), entry('d@latest', 'd@1.0.0'))
    const { installed } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root, 'packages/w/package.json': w }), host: HOST })
    assert.deepEqual(installed.map(({ path, dev }) => [path, dev]), [
      ['node_modules/a', false],
      ['node_modules/a/node_modules/b', false],
      ['node_modules/b', false],
      ['node_modules/d', true],
      ['packages/w/node_modules/b', true],
    ])
  })

  // b 2.0.0 takes the top, so b 1.0.0 is copied beneath a, a dependency,
  // and beneath q: each copy is listed as what reaches it from where it is.
  it('lists each copy of one package as what reaches that copy', async () => {
    stubRegistry(TARBALLS)
    const lock = lockfile(A, entry('b@^1.0.0', 'b@1.0.0'), entry('b@^2.0.0', 'b@2.0.0'), entry('q@1.0.0', 'q@1.0.0', '  dependencies:\n    b "^1.0.0"\n'))
    for (const kind of ['devDependencies', 'optionalDependencies']) {
      const root = { name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0', b: '^2.0.0' }, [kind]: { q: '1.0.0' } }
      const { installed } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
      const flag = kind === 'devDependencies' ? 'dev' : 'optional'
      assert.deepEqual(installed.map((copy) => [copy.path, copy[flag]]), [
        ['node_modules/a', false],
        ['node_modules/a/node_modules/b', false],
        ['node_modules/b', false],
        ['node_modules/q', true],
        ['node_modules/q/node_modules/b', true],
      ], kind)
    }
  })

  // yarn's linker sorts where each package goes with localeCompare, in the
  // locale Node runs in, and so does this; in Danish, `aa` sorts after `z`.
  it('builds one tree, and lists it in one order, whatever the locale', async (t) => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { aab: '1.0.0', ab: '1.0.0', d: 'latest' } }
    const lock = lockfile(entry('aab@1.0.0', 'aab@1.0.0'), entry('ab@1.0.0', 'ab@1.0.0'), entry('d@latest', 'd@1.0.0'))
    const built = () => buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
    const danish = new Intl.Collator('da')
    t.mock.method(String.prototype, 'localeCompare', function (that) { return danish.compare(this, that) })
    const da = await built()
    t.mock.restoreAll()
    const en = await built()
    assert.deepEqual(da.installed.map(({ path }) => path), ['node_modules/aab', 'node_modules/ab', 'node_modules/d'])
    assert.deepEqual(da.installed, en.installed)
    assert.deepEqual(paths(da.vfs), paths(en.vfs))
  })

  it('refuses once every fetch started has ended', async () => {
    const open = stubFailingRegistry(TARBALLS, 'd', '1.0.0')
    await assert.rejects(build(), /^DeptreeError: "d@/u)
    assert.equal(open(), 0)
  })

  it('builds the same tree from the files given', async () => {
    stubRegistry(TARBALLS)
    const read = await build()
    const given = await buildYarn1Tree({ lockfile: LOCKFILE, manifests: { '.': JSON.stringify(ROOT) }, project: projectOf({}), host: HOST })
    assert.deepEqual(paths(given.vfs), paths(read.vfs))
  })

  it('links a workspace, and installs what yarn hoists beneath it in its own node_modules', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { b: '^2.0.0' } }
    const w = { name: 'w', version: '1.0.0', dependencies: { a: '1.0.0', b: '^1.0.0' } }
    const lock = lockfile(entry('a@1.0.0', 'a@1.0.0', '  dependencies:\n    b "^1.0.0"\n'), entry('b@^1.0.0', 'b@1.0.0'), entry('b@^2.0.0', 'b@2.0.0'))
    const files = projectOf({ 'yarn.lock': lock, 'package.json': root, 'packages/w/package.json': w, 'packages/w/index.js': 'w' })
    assert.deepEqual(findYarn1Workspaces({ project: files }), ['.', 'packages/w'])
    const { vfs, stats } = await buildYarn1Tree({ project: files, host: HOST, vfs: files })
    assert.equal(vfs.readlink('/node_modules/w'), '../packages/w')
    assert.equal(vfs.readText('/node_modules/w/index.js'), 'w')
    assert.equal(vfs.readText('/packages/w/node_modules/b/index.js'), 'b1')
    assert.equal(vfs.readText('/node_modules/a/node_modules/b/index.js'), 'b1')
    assert.equal(vfs.readText('/node_modules/b/index.js'), 'b2')
    assert.equal(stats.links, 1)
  })

  // node-glob's `**` takes no name as well as several, so a glob may spell
  // a dot directory right below where it starts.
  it('finds a workspace in a dot directory a glob spells, as yarn does', () => {
    const root = { name: 'root', version: '1.0.0', private: true, workspaces: ['**/.packages/*'] }
    const files = projectOf({ 'package.json': root, '.packages/w/package.json': '{}', 'x/.packages/v/package.json': '{}', '.other/.packages/u/package.json': '{}' })
    assert.deepEqual(findYarn1Workspaces({ project: files }), ['.', '.packages/w', 'x/.packages/v'])
  })

  it('gives a dependency a resolution applies to the resolution\'s package', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0', b: '^2.0.0' }, resolutions: { 'a/b': '2.0.0' } }
    const lock = lockfile(A, entry('b@2.0.0, b@^1.0.0, b@^2.0.0', 'b@2.0.0'))
    const { vfs } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
    assert.deepEqual(vfs.readdir('/node_modules/a'), ['bin', 'package.json', 'x.sh'])
  })

  // yarn copies a directory whole, each file's mode as it is, into its cache,
  // makes each bin's target executable there, and copies that, but for .bin
  // and its own metadata, wherever they are.
  it('installs a file: directory a resolution or the root names, as yarn copies it', async () => {
    stubRegistry(TARBALLS)
    const local = { 'local/b/package.json': { name: 'b', version: '1.5.0', bin: { b: 'cli.js' } }, 'local/b/cli.js': '#!/usr/bin/env node\n', 'local/b/secret': 's', 'local/b/.gitignore': 'secret\n', 'local/b/sub/.bin/tool': 't', 'local/b/.yarn-metadata.json': '{}' }
    const at = (root, lock) => {
      const files = projectOf({ 'yarn.lock': lock, 'package.json': root, ...local })
      files.chmod('/local/b/secret', 0o600)
      files.mkdir('/local/b/empty')
      return files
    }
    const resolved = at({ name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0' }, resolutions: { b: 'file:./local/b' } }, lockfile(A, 'b@^1.0.0, "b@file:./local/b":\n  version "1.5.0"\n'))
    const asked = at({ name: 'root', version: '1.0.0', dependencies: { b: 'file:./local/b' } }, lockfile('"b@file:./local/b":\n  version "1.5.0"\n'))
    for (const files of [resolved, asked]) {
      const { vfs, installed } = await buildYarn1Tree({ project: files, host: HOST })
      assert.deepEqual(vfs.readdir('/node_modules/b'), ['.gitignore', 'cli.js', 'empty', 'package.json', 'secret', 'sub'])
      assert.deepEqual(vfs.readdir('/node_modules/b/sub'), [])
      assert.deepEqual(['cli.js', 'secret', '.gitignore'].map((name) => mode(vfs, `/node_modules/b/${name}`)), [0o755, 0o600, 0o644])
      assert.deepEqual(installed.find(({ path }) => path === 'node_modules/b'), { path: 'node_modules/b', name: 'b', version: '1.5.0', directory: 'local/b', dev: false, optional: false })
    }
    const modeless = { readdir: (path) => asked.readdir(path), lstat: (path) => ({ type: asked.lstat(path).type }), stat: (path) => asked.stat(path), readFile: (path) => asked.readFile(path) }
    await assert.rejects(buildYarn1Tree({ project: modeless, host: HOST }), /^TypeError: project\.lstat must give a file's mode, and gives undefined for "\/local\/b\/\.gitignore"$/u)
  })

  // yarn writes no integrity for a pattern that names a tarball's URL, but the
  // sha1 after its `#`; the registry's sha512 is taken beside it.
  it('installs the registry\'s own tarball a resolution or the root names by its URL', async () => {
    const calls = stubRegistry(TARBALLS)
    const byUrl = (keys, id) => entry(keys, id).replace(/\n {2}integrity .*/u, '')
    const b2 = yarnpkg('b', '2.0.0')
    const resolved = { project: projectOf({ 'yarn.lock': lockfile(A, byUrl(`b@^1.0.0, "b@${b2}"`, 'b@2.0.0')), 'package.json': { name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0' }, resolutions: { b: b2 } } }) }
    const asked = { project: projectOf({ 'yarn.lock': lockfile(byUrl(`"b@${b2}"`, 'b@2.0.0')), 'package.json': { name: 'root', version: '1.0.0', dependencies: { b: b2 } } }) }
    for (const options of [resolved, asked]) {
      const { vfs, installed } = await buildYarn1Tree({ ...options, host: HOST })
      assert.equal(vfs.readText('/node_modules/b/index.js'), 'b2')
      assert.equal(installed.find(({ path }) => path === 'node_modules/b').integrity, T['b@2.0.0'].integrity)
    }
    assert.ok(calls.includes('https://registry.npmjs.org/b/2.0.0'), 'the registry\'s document, for its sha512')
    const wrong = lockfile(byUrl(`"b@${b2}"`, 'b@2.0.0').replace(sha1(T['b@2.0.0'].bytes), sha1(T['b@1.0.0'].bytes)))
    await assert.rejects(buildYarn1Tree({ project: projectOf({ 'yarn.lock': wrong, 'package.json': { name: 'root', version: '1.0.0', dependencies: { b: b2 } } }), host: HOST }), /^DeptreeError: "b@https:\/\/registry\.yarnpkg\.com\/b\/-\/b-2\.0\.0\.tgz": the tarball's sha1 is not [\da-f]{40}$/u)
  })

  // jsonfile 4.0.0 was published by npm 3.10.3, before the registry made a
  // sha512 for every version: yarn wrote a sha1 for it until the registry
  // made one for it too, which it is fetched by.
  it('installs a tarball whose entry has a sha1 integrity alone, published before the registry made a sha512 for every version', async () => {
    const calls = publishedAt(OLD)
    const { vfs, installed } = await buildYarn1Tree({ ...sha1Project(), host: HOST })
    assert.equal(vfs.readText('/node_modules/b/index.js'), 'b1')
    assert.equal(installed[0].integrity, T['b@1.0.0'].integrity)
    assert.deepEqual(calls.filter((call) => !call.endsWith('.tgz')), ['https://registry.npmjs.org/b', 'https://registry.npmjs.org/b/1.0.0'])
  })

  // yarn's workspace aggregator asks again for what the root does: for a
  // directory, it takes the one it read; for a tarball URL, it makes the
  // package anew, which is one package with the first.
  it('installs the root\'s file: directory and tarball URL beside workspaces', async () => {
    stubRegistry(TARBALLS)
    const byUrl = (keys, id) => entry(keys, id).replace(/\n {2}integrity .*/u, '')
    const b2 = yarnpkg('b', '2.0.0')
    const at = (dependencies, ...entries) => projectOf({
      'yarn.lock': lockfile(...entries, '"l@file:./local/l":\n  version "1.5.0"\n'),
      'package.json': { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { l: 'file:./local/l', ...dependencies } },
      'packages/w/package.json': { name: 'w', version: '1.0.0' },
      'local/l/package.json': { name: 'l', version: '1.5.0' },
      'local/l/i.js': 'l',
    })
    const { vfs, stats } = await buildYarn1Tree({ project: at({ b: b2 }, byUrl(`"b@${b2}"`, 'b@2.0.0')), host: HOST })
    assert.equal(vfs.readText('/node_modules/l/i.js'), 'l')
    assert.equal(vfs.readText('/node_modules/b/index.js'), 'b2')
    assert.equal(vfs.readlink('/node_modules/w'), '../packages/w')
    assert.equal(stats.packages, 2)
    // A tag's, as the aggregator asks for it again too, waits on the
    // filesystem beside the directory's.
    await assert.rejects(buildYarn1Tree({ project: at({ d: 'latest' }, entry('d@latest', 'd@1.0.0')), host: HOST }), /^DeptreeError: yarn resolves these in the order the filesystem answers it, which is not set: "d@latest", "l@file:\.\/local\/l"$/u)
  })

  it('installs a package the host cannot run where the settings say to ignore its platform', async () => {
    stubRegistry(TARBALLS)
    const { vfs } = await buildYarn1Tree({ project: project({ '.yarnrc': '--ignore-platform true\n' }), host: HOST })
    assert.equal(vfs.isDirectory('/node_modules/mac'), true)
    const option = await buildYarn1Tree({ project: project({ '.yarnrc': 'ignore-platform true\n' }), host: HOST })
    assert.equal(option.vfs.isDirectory('/node_modules/mac'), false, 'yarn does not act on the option')
  })

  it('unpacks a tarball as tar-fs does for yarn, a `.` folded, and a node_modules below its own copied', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { fix: '1.0.0' } }
    const { vfs } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lockfile(entry('fix@1.0.0', 'fix@1.0.0')), 'package.json': root }), host: HOST })
    assert.equal(vfs.readText('/node_modules/fix/lib/x.js'), 'x')
    assert.equal(vfs.readText('/node_modules/fix/test/node_modules/fixture.js'), 'f')
  })

  it('reads a dependency listed twice as yarn does, in the first list, at the first range that is not "*"', async () => {
    stubRegistry(TARBALLS)
    const root = { ...ROOT, dependencies: { ...ROOT.dependencies, b: '*' }, devDependencies: { ...ROOT.devDependencies, b: '^2.0.0', '//': 'b is for tests' } }
    const { vfs } = await build({ project: project({ 'package.json': root }) })
    assert.equal(vfs.readText('/node_modules/b/index.js'), 'b2')
  })

  // A tag never finds the package of its version resolved, so mac@latest
  // makes a second reference of mac 1.0.0. yarn's fetcher fetches the
  // first of two its cache keeps in one place, and leaves the second its
  // lockfile entry for a package.json, with no os: that one is installed,
  // and the first, which the host cannot run, is installed where it is.
  it('installs a package the host cannot run where a second reference of it is its lockfile entry, as yarn does', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', optionalDependencies: { mac: '1.0.0', x: '1.0.0' } }
    const lock = lockfile(entry('mac@1.0.0, mac@latest', 'mac@1.0.0'), entry('x@1.0.0', 'x@1.0.0', '  dependencies:\n    mac latest\n'))
    const { vfs, stats } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
    assert.deepEqual(vfs.readdir('/node_modules'), ['mac', 'x'])
    assert.equal(stats.packages, 2)
  })

  // loop1@latest makes a second reference of loop1 2.0.0, placed where
  // the first would go, which has no bins, so yarn links none of loop1's;
  // its fetcher has made their targets executable all the same, a `/`
  // after one dropped.
  it('makes each bin\'s target executable as yarn\'s fetcher does, where yarn links none', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { loop2: '^1.0.0' }, devDependencies: { loop1: 'latest' } }
    const lock = lockfile(
      entry('loop1@^2.0.0, loop1@latest', 'loop1@2.0.0', '  dependencies:\n    loop2 "1.1.0"\n'),
      entry('loop2@1.1.0, loop2@^1.0.0', 'loop2@1.1.0', '  dependencies:\n    loop1 "^2.0.0"\n'),
    )
    const { vfs } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
    assert.equal(mode(vfs, '/node_modules/loop1/run.js'), 0o755)
    assert.equal(mode(vfs, '/node_modules/loop1/more.js'), 0o755)
  })

  // The aggregator asks for d@latest and the workspace's p@latest at once:
  // the filesystem answers them in an order not set, and each resolves all
  // beneath it before the next, which changes nothing where they share none.
  it('two tags at once where the order the filesystem answers them changes nothing', async () => {
    stubRegistry(TARBALLS)
    const { vfs, stats } = await buildYarn1Tree({ ...twoTags(['d', 'p'], TAGS_APART), host: HOST })
    assert.deepEqual(vfs.readdir('/node_modules'), ['d', 'p', 'w'])
    assert.equal(stats.packages, 2)
  })

  it('passes over settings that only move where yarn fetches from', async () => {
    stubRegistry(TARBALLS)
    const files = {
      '.yarnrc': 'registry "https://registry.npmjs.org/"\n--install.frozen-lockfile true\nlastUpdateCheck 1700000000000\n',
      '.npmrc': '//registry.npmjs.org/:_authToken=${TOKEN}\npackage-lock=false\nlegacy-peer-deps=true\n',
    }
    await buildYarn1Tree({ project: project(files), host: HOST })
  })
})

describe('buildYarn1Tree refuses', () => {
  const refuses = (options, pattern) => assert.rejects(buildYarn1Tree({ host: HOST, ...options }), pattern)

  it('a tag at the top without the project, or where the project has a directory of its name', async () => {
    stubRegistry(TARBALLS)
    await refuses({ lockfile: LOCKFILE, manifests: { '.': JSON.stringify(ROOT) } }, /^DeptreeError: "d@latest": yarn installs the directory "latest" for it where the project has one, which is known only with the project read$/u)
    await refuses({ project: project({ 'latest/package.json': '{}' }) }, /^DeptreeError: "d@latest": yarn installs the directory "latest" for it, which is not supported$/u)
  })

  // yarn 1.22 installs a directory as a copy of all of it, whatever
  // package.json's `files` and an ignore file say, which is not built here.
  it('a dependency on a directory by link:', async () => {
    const files = { 'yarn.lock': lockfile('"foo@link:./vendor/foo":\n  version "0.0.0"\n'), 'package.json': { name: 'root', version: '1.0.0', dependencies: { foo: 'link:./vendor/foo' } }, 'vendor/foo/package.json': { name: 'foo', version: '1.5.0' } }
    await refuses({ project: projectOf(files) }, /^DeptreeError: "foo@link:\.\/vendor\/foo": only a semver range, an npm: alias, a tag, a file: directory or the registry's own tarball URL is supported$/u)
  })

  // What yarn reads anew at every install, and installs whatever it says, is
  // held to the lockfile; what it would copy beside what it installs, or as
  // two packages, is refused.
  it('a file: directory not as its lockfile entry has it, or not one yarn installs alone', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { b: 'file:./local/b' } }
    const lock = lockfile('"b@file:./local/b":\n  version "1.5.0"\n')
    const at = (local, edit = () => {}, options = {}) => {
      const files = projectOf({ 'yarn.lock': lock, 'package.json': root, ...local })
      edit(files)
      return { project: files, ...options }
    }
    const manifest = (fields) => ({ 'local/b/package.json': { name: 'b', version: '1.5.0', ...fields } })
    const where = '^DeptreeError: "b@file:\\./local/b": '
    const cases = [
      [at(manifest({ version: '1.6.0' })), 'package.json is for "b@1\\.6\\.0", not the lockfile\'s "b@1\\.5\\.0", which yarn reads anew, installing what it says$'],
      [at(manifest({ name: 'c' })), 'package.json is for "c@1\\.5\\.0", not the lockfile\'s "b@1\\.5\\.0", which yarn reads anew, installing what it says$'],
      [at(manifest({ dependencies: { d: '^1.0.0' } })), 'package.json\'s dependencies are not the lockfile\'s, which yarn reads anew, installing what it says$'],
      [at({ 'local/b/index.js': 'b' }), '"local/b" has no package\\.json, where yarn makes one up$'],
      [at({}), '"local/b" is not a directory of the project$'],
      [at({ ...manifest(), 'local/b/node_modules/x/index.js': 'x' }), '"local/b/node_modules" is its own node_modules, which yarn copies beside what it installs there, and which is not supported$'],
      [at(manifest(), (files) => files.symlink('package.json', '/local/b/again')), '"local/b/again" is a symlink, which is not supported$'],
      [{ lockfile: lock, manifests: { '.': JSON.stringify(root) } }, 'a file: directory is read from the project, which is not given$'],
    ]
    for (const [options, detail] of cases) await refuses(options, new RegExp(`${where}${detail}`, 'u'))
  })

  it('a file: directory outside the project, at its root, or asked for beneath the top level', async () => {
    stubRegistry(TARBALLS)
    const buildAt = (range, lock, local = {}) => buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': { name: 'root', version: '1.0.0', dependencies: { b: range } }, ...local }), host: HOST })
    await assert.rejects(buildAt('file:../b', lockfile('"b@file:../b":\n  version "1.5.0"\n')), /^DeptreeError: "b@file:\.\.\/b": "\.\.\/b" is outside the project, which is not supported$/u)
    await assert.rejects(buildAt('file:.', lockfile('"b@file:.":\n  version "1.0.0"\n')), /^DeptreeError: "b@file:\.": the project's own directory is not supported$/u)
    const nested = { 'local/b/package.json': { name: 'b', version: '1.5.0', dependencies: { c: 'file:./c' } } }
    const lock = lockfile('"b@file:./local/b":\n  version "1.5.0"\n  dependencies:\n    c "file:./c"\n', '"c@file:./c":\n  version "1.0.0"\n')
    await assert.rejects(buildAt('file:./local/b', lock, nested), /^DeptreeError: "c@file:\.\/c": a file: directory asked for beneath the top level, and not by the root or a resolution first, is not supported$/u)
  })

  // The aggregator asks for the root's tag and the workspace's at once, and
  // the filesystem answers them in an order not set: refused where that order
  // could change the tree.
  it('two tags yarn would resolve in the order the filesystem answers, where that order could change the tree', async () => {
    stubRegistry(TARBALLS)
    const b = '  dependencies:\n    b "^1.0.0"\n'
    const race = /^DeptreeError: yarn resolves these in the order the filesystem answers it, which is not set: "a@latest", "q@latest"$/u
    // Whichever resolves first makes b 1.0.0, with its own chain of names.
    const shared = lockfile(entry('a@latest', 'a@1.0.0', b), entry('b@^1.0.0', 'b@1.0.0'), entry('q@latest', 'q@1.0.0', b))
    await refuses(twoTags(['a', 'q'], shared), race)
    // Each adds a pattern of b 1.0.0, resolved already, in that order.
    const resolved = lockfile(entry('a@latest', 'a@1.0.0', b), entry('b@1.0.0, b@^1.0.0', 'b@1.0.0'), entry('q@latest', 'q@1.0.0', b))
    await refuses(twoTags(['a', 'q'], resolved, { devDependencies: { b: '1.0.0' } }), race)
    // A resolution diverts a request where its package is resolved already,
    // and else once all are.
    const ruled = lockfile(entry('a@latest', 'a@1.0.0', b), entry('b@^1.0.0', 'b@1.0.0'), entry('p@latest', 'p@1.0.0'))
    await refuses(twoTags(['a', 'p'], ruled, { resolutions: { '**/b': '^1.0.0' } }), /^DeptreeError: yarn resolves these in the order the filesystem answers it, which is not set: "a@latest", "p@latest"$/u)
    await refuses(twoTags(['d', 'p'], TAGS_APART, {}, { 'latest/package.json': '{}' }), /^DeptreeError: "d@latest": yarn installs the directory "latest" for it, which is not supported$/u)
    const manifests = Object.fromEntries(Object.entries(twoTagsManifests(['d', 'p'])).map(([dir, manifest]) => [dir, JSON.stringify(manifest)]))
    await refuses({ lockfile: TAGS_APART, manifests }, /^DeptreeError: "d@latest": yarn installs the directory "latest" for it where the project has one, which is known only with the project read$/u)
  })

  // A tarball on the project's disk, as yarn's tarball resolver takes a path
  // ending in .tgz, among them.
  it('a package from anywhere but the registry or the project, before fetching anything', async () => {
    const calls = stubRegistry(TARBALLS)
    const only = 'only a semver range, an npm: alias, a tag, a file: directory or the registry\'s own tarball URL is supported$'
    for (const range of ['https://example.com/d/-/d-1.0.0.tgz', 'file:./d-1.0.0.tgz', `${yarnpkg('d', '1.0.0')}#${sha1(T['d@1.0.0'].bytes)}`]) {
      const root = { name: 'root', version: '1.0.0', dependencies: { d: range } }
      const lock = lockfile(entry(`"d@${range}"`, 'd@1.0.0', '', { url: () => range.split('#')[0] }))
      await refuses({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }) }, new RegExp(`^DeptreeError: "d@${range.replaceAll(/[.?]/gu, '\\$&')}": ${only}`, 'u'))
    }
    const url = 'https://example.com/b/-/b-1.0.0.tgz'
    const root = { name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0' }, resolutions: { b: url } }
    const lock = lockfile(A, entry(`b@^1.0.0, "b@${url}"`, 'b@1.0.0', '', { url: () => url }))
    await refuses({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }) }, new RegExp(`^DeptreeError: manifests\\["\\."\\]\\.resolutions\\["b"\\]: ${only}`, 'u'))
    assert.equal(calls.length, 0)
  })

  it('a tarball by any URL but the registry\'s own, or yarn\'s mirror of it', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { '@s/e': '1.0.0' } }
    const at = (url) => ({ project: projectOf({ 'yarn.lock': lockfile(entry('"@s/e@1.0.0"', '@s/e@1.0.0', '', { url })), 'package.json': root }) })
    for (const url of [yarnpkg, (name, version) => yarnpkg(name, version).replace('yarnpkg.com', 'npmjs.org')]) {
      const { vfs } = await buildYarn1Tree({ ...at(url), host: HOST })
      assert.equal(vfs.isFile('/node_modules/@s/e/package.json'), true)
    }
    const refused = /^DeptreeError: "@s\/e@1\.0\.0": only the registry's own tarball of @s\/e@1\.0\.0, https:\/\/registry\.npmjs\.org\/@s\/e\/-\/e-1\.0\.0\.tgz, is supported$/u
    for (const url of [
      (name, version) => yarnpkg(name, version).replace('/@s/', '/@s%2f'),
      (name, version) => yarnpkg(name, version).replace('https://registry.yarnpkg.com', 'https://registry.npmmirror.com'),
      (name, version) => yarnpkg(name, version).replace('https:', 'http:'),
      (name, version) => yarnpkg(name, version).replace('npmjs.org', 'npmjs.org:444').replace('yarnpkg.com', 'npmjs.org:444'),
      (name, version) => yarnpkg(name, version).replace('yarnpkg.com', 'yarnpkg.com:443'),
    ]) await refuses(at(url), refused)
  })

  // More packages before it than are fetched at once, so that one would be
  // fetched before its turn came.
  it('a tarball\'s URL before fetching any', async () => {
    const calls = stubRegistry(TARBALLS)
    const root = { ...ROOT, dependencies: { ...ROOT.dependencies, eng: '1.0.0', fix: '1.0.0' }, optionalDependencies: { mac: '1.0.0', '@s/e': '1.0.0' } }
    const http = (name, version) => yarnpkg(name, version).replace('https:', 'http:')
    const lock = LOCKFILE.replace('\n"my-c', `\n${entry('eng@1.0.0', 'eng@1.0.0')}\n${entry('fix@1.0.0', 'fix@1.0.0')}\n"my-c`) + `\n${entry('"@s/e@1.0.0"', '@s/e@1.0.0', '', { url: http })}`
    await refuses({ project: project({ 'yarn.lock': lock, 'package.json': root }) }, /^DeptreeError: "@s\/e@1\.0\.0": only the registry's own tarball/u)
    assert.deepEqual(calls, [])
  })

  it('a tarball that is not the one the lockfile pins', async () => {
    stubRegistry(TARBALLS)
    const lock = LOCKFILE.replace(sha1(T['d@1.0.0'].bytes), sha1(T['p@1.0.0'].bytes))
    await refuses({ project: project({ 'yarn.lock': lock }) }, /^DeptreeError: "d@latest": the tarball's sha1 is not [\da-f]{40}$/u)
    publishedAt(OLD)
    await refuses(sha1Project('b@2.0.0'), exactly(`DeptreeError: "b@^1.0.0": the tarball's sha1 is not ${sha1(T['b@2.0.0'].bytes)}`))
  })

  // yarn writes a sha1 integrity alone only where the registry has no sha512
  // for the version, as it has had for every one published since the time
  // it made one for each: none is fetched for one published since.
  it('a sha1 integrity alone, for a version published since the registry made a sha512 for every one, or at no time it gives', async () => {
    for (const time of ['2018-08-05T14:58:16.253Z', '2021-03-04T05:06:07.890Z', undefined]) {
      const calls = publishedAt(time)
      const detail = time === undefined ? 'where the registry gives no time b@1.0.0 was published at' : `which yarn does not write for b@1.0.0, published at ${time}: the registry has given every version a sha512 since 2018-08-05T14:58:16.253Z`
      await refuses(sha1Project(), exactly(`DeptreeError: "b@^1.0.0": a sha1 integrity alone, ${detail}`))
      assert.deepEqual(calls, ['https://registry.npmjs.org/b'])
    }
  })

  // Two entries of one tarball and one uid are one place in yarn's cache,
  // which it fetches once: the sha1 of each is held to the bytes, whichever
  // is fetched.
  it('a tarball that is not the one another entry of it pins', async () => {
    const wrong = sha1(T['p@1.0.0'].bytes)
    for (const hashed of ['d@latest', 'd@next']) {
      const [latest, next] = ['d@latest', 'd@next'].map((keys) => dEntry(keys, T['d@1.0.0'].integrity, keys === hashed ? `#${wrong}` : ''))
      stubRegistry([...TARBALLS, Q])
      await refuses(withQ(latest, next), new RegExp(`^DeptreeError: "${hashed}": the tarball's sha1 is not ${wrong}$`, 'u'))
    }
  })

  // q asks for d@next before the root's devDependencies are resolved, so it
  // is the one fetched; d@latest, in the same place, is held to its tarball:
  // its integrity, and for a sha1 alone when its version was published.
  it('an entry in one place with another whose integrity is not the tarball\'s, or a sha1 alone of a version published since', async () => {
    const D = T['d@1.0.0']
    const options = (next, latest, published) => {
      publishedAt(published, 'd@1.0.0', [Q])
      return withQ(dEntry('d@latest', ...latest), dEntry('d@next', ...next))
    }
    const pinned = [D.integrity, `#${sha1(D.bytes)}`]
    const { vfs } = await buildYarn1Tree({ ...options(pinned, [sri(D.bytes, 'sha1')], OLD), host: HOST })
    assert.equal(vfs.isDirectory('/node_modules/d'), true)
    const cases = [
      [pinned, [sri(D.bytes, 'sha1')], '2021-03-04T05:06:07.890Z', 'a sha1 integrity alone, which yarn does not write for d@1.0.0, published at 2021-03-04T05:06:07.890Z: the registry has given every version a sha512 since 2018-08-05T14:58:16.253Z'],
      [pinned, [sri(T['p@1.0.0'].bytes, 'sha1')], OLD, `the tarball's sha1 is not ${sha1(T['p@1.0.0'].bytes)}`],
      [[sri(D.bytes, 'sha1')], [T['p@1.0.0'].integrity, `#${sha1(D.bytes)}`], OLD, `the tarball is not ${T['p@1.0.0'].integrity}`],
    ]
    for (const [next, latest, published, detail] of cases) await refuses(options(next, latest, published), exactly(`DeptreeError: "d@latest": ${detail}`))
  })

  it('a package with bins and a .bin file, or a bin in its own node_modules', async () => {
    stubRegistry(TARBALLS)
    const at = (name, lock) => ({ project: projectOf({ 'yarn.lock': lockfile(...lock), 'package.json': { name: 'root', version: '1.0.0', dependencies: { [name]: '1.0.0' } } }) })
    await refuses(at('dotbin', [entry('dotbin@1.0.0', 'dotbin@1.0.0')]), /^DeptreeError: "dotbin@1\.0\.0": \.bin is a file, where yarn fails to make a directory for the bins$/u)
    await refuses(at('inner', [entry('inner@1.0.0', 'inner@1.0.0', '  dependencies:\n    b "^1.0.0"\n'), entry('b@^1.0.0', 'b@1.0.0')]), /^DeptreeError: "inner@1\.0\.0": its bin "node_modules\/b\/index\.js" is in its own node_modules, where yarn installs its dependencies, which is not supported$/u)
    // macOS takes Node_Modules for node_modules.
    await refuses(at('shadow', [entry('shadow@1.0.0', 'shadow@1.0.0', '  dependencies:\n    b "^1.0.0"\n'), entry('b@^1.0.0', 'b@1.0.0')]), /^DeptreeError: "shadow@1\.0\.0": "package\/Node_Modules\/b\/index\.js" is in the package's own node_modules, where yarn installs its dependencies, which is not supported$/u)
  })

  it('a package the host cannot run, where it is not optional', async () => {
    stubRegistry(TARBALLS)
    const root = { ...ROOT, dependencies: { ...ROOT.dependencies, mac: '1.0.0' }, optionalDependencies: undefined }
    await refuses({ project: project({ 'package.json': root }) }, /^DeptreeError: "mac@1\.0\.0": its os, \["darwin"\], does not take "linux", and it is not optional, which yarn fails on$/u)
  })

  it('a package whose engines the host does not take, unless the settings say to ignore them', async () => {
    stubRegistry(TARBALLS)
    const files = (rc) => ({ 'yarn.lock': lockfile(entry('eng@1.0.0', 'eng@1.0.0')), 'package.json': { name: 'root', version: '1.0.0', dependencies: { eng: '1.0.0' } }, ...rc })
    await refuses({ project: projectOf(files({})) }, /^DeptreeError: "eng@1\.0\.0": its engines\.node, ">=100", does not take 24\.15\.0, and it is not optional, which yarn fails on$/u)
    await refuses({ project: projectOf(files({ '.yarnrc': 'ignore-engines false\n', '.npmrc': 'ignore-engines=true\n' })) }, /does not take 24\.15\.0/u)
    for (const rc of [{ '.yarnrc': 'ignore-engines true\n' }, { '.yarnrc': 'ignore-engines "false"\n' }, { '.yarnrc': '--install.ignore-engines true\n' }, { '.npmrc': 'ignore-engines=true\n' }]) {
      const { vfs } = await buildYarn1Tree({ project: projectOf(files(rc)), host: HOST })
      assert.equal(vfs.isDirectory('/node_modules/eng'), true, JSON.stringify(rc))
    }
    await refuses({ project: projectOf(files({ '.yarnrc': '--ignore-engines yes\n' })) }, /^DeptreeError: \.yarnrc:1: expected true or false for "--ignore-engines"$/u)
  })

  // yarn checks an engine against process.versions of the Node it runs
  // on, which host.node alone does not tell; one Node never reports, such
  // as npm, it passes over.
  it('an engine yarn checks against the Node it runs on, one this Node reports among them', async () => {
    const engines = (name) => project({ 'package.json': { ...ROOT, engines: { [name]: '>=0' } } })
    for (const name of Object.keys(process.versions).filter((key) => key !== 'node')) {
      await refuses({ project: engines(name) }, new RegExp(`^DeptreeError: manifests\\["\\."\\]: yarn checks engines\\.${name} against the Node it runs on, which is not known here$`, 'u'))
    }
    stubRegistry(TARBALLS)
    await buildYarn1Tree({ project: engines('npm'), host: HOST })
  })

  it('a setting that may change what yarn installs', async () => {
    await refuses({ project: project({ '.yarnrc': '--install.production true\n' }) }, /^DeptreeError: \.yarnrc:1: "--install\.production" is a setting not supported here/u)
    await refuses({ project: project({ '.npmrc': 'ignore-optional=true\n' }) }, /^DeptreeError: \.npmrc:1: "ignore-optional" is a setting not supported here/u)
    await refuses({ project: project({ '.yarnrc': 'yarn-path ".yarn/releases/yarn-1.22.19.js"\n' }) }, /^DeptreeError: \.yarnrc:1: "yarn-path" is a setting not supported here/u)
    await refuses({ project: project({ '.yarnrc': '--add.modules-folder lib\n' }) }, /^DeptreeError: \.yarnrc:1: "--add\.modules-folder" is a setting not supported here/u)
    for (const key of ['--no-lockfile', '--install.no-lockfile', '--global-folder']) {
      await refuses({ project: project({ '.yarnrc': `${key} true\n` }) }, new RegExp(`^DeptreeError: \\.yarnrc:1: "${key.replace('.', '\\.')}" is a setting not supported here`, 'u'))
    }
    await refuses({ project: project({ '.yarnrc': 'global-folder "."\n' }) }, /^DeptreeError: \.yarnrc:1: "global-folder" is a setting not supported here/u)
  })

  it('a yarn this does not build for, or another than the project pins', async () => {
    await refuses({ project: project(), host: { ...HOST, yarn: '1.21.1' } }, /^DeptreeError: host\.yarn: yarn "1\.21\.1" is not supported: only yarn 1\.22\.x is$/u)
    await refuses({ project: project(), host: { ...HOST, os: 'win32' } }, /^DeptreeError: host\.os: Windows is not supported/u)
    await refuses({ project: project({ 'package.json': { ...ROOT, packageManager: 'yarn@1.22.19' } }) }, /^DeptreeError: manifests\["\."\]\.packageManager: the project is installed by yarn 1\.22\.19, which corepack runs, not 1\.22\.22$/u)
    await assert.rejects(buildYarn1Tree({ project: project(), host: { ...HOST, yarn: undefined } }), TypeError)
  })

  it('a lockfile the lockfile reader refuses', async () => {
    await refuses({ project: project({ 'yarn.lock': LOCKFILE.replace('  version "2.0.0"', '  version "1.0.0"') }) }, LockfileError)
  })

  it('what yarn would read beyond the files given', async () => {
    await refuses({ project: project({ 'yarn.json': '{}' }) }, /^DeptreeError: yarn\.json: a yarn\.json, which yarn reads as a manifest too, is not supported$/u)
    await refuses({ project: project({ '.yarnrc.yml': 'yarnPath: .yarn/releases/yarn.cjs\n' }) }, /^DeptreeError: \.yarnrc\.yml: a \.yarnrc\.yml, whose yarnPath yarn 1\.22 runs in its stead, is not supported$/u)
    const root = { ...ROOT, private: true, workspaces: ['packages/*'] }
    await refuses({ project: project({ 'package.json': root, 'packages/node_modules/package.json': '{}' }) }, /^DeptreeError: "packages\/node_modules": yarn would read this node_modules as a workspace/u)
  })

  it('a root that is not the files of one install', async () => {
    await refuses({ project: project({ 'node_modules/x': '' }), vfs: projectOf({ 'node_modules/x': '' }) }, DeptreeError)
    await refuses({ project: project({ 'package.json': { ...ROOT, name: '.root' } }) }, /^DeptreeError: manifests\["\."\]\.name: "\.root" is a name yarn fails on$/u)
    await refuses({ project: project({ 'package.json': { ...ROOT, workspaces: { packages: [], nohoist: ['**'] } } }) }, /nohoist is not supported/u)
  })
})
