import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { afterEach, describe, it } from 'node:test'
import { createVfs } from '@preventive/vfs'
import { DeptreeError, LockfileError, buildYarn1Tree, findYarn1Workspaces } from '../yarn1.js'
import { stubRegistry, tarball } from './registry.js'

// Small projects whose yarn.lock real yarn 1.22.22 wrote, and whose trees
// it installed as the first tests expect, against a registry stubbed with
// the same tarballs made here; then one change at a time, each refused with
// where and why.

const realFetch = globalThis.fetch
afterEach(() => { globalThis.fetch = realFetch })

const HOST = Object.freeze({ yarn: '1.22.22', node: '24.15.0', os: 'linux', cpu: 'x64' })

const TARBALLS = await Promise.all([
  tarball('a', '1.0.0', { 'bin/a.js': { data: '#!/usr/bin/env node\n', mode: 0o644 }, 'x.sh': { data: 'x', mode: 0o700 }, '.bin/hidden': 'hidden' }, { manifest: { dependencies: { b: '^1.0.0' }, bin: { a: 'bin/a.js' } } }),
  tarball('b', '1.0.0', { 'index.js': 'b1' }),
  tarball('b', '2.0.0', { 'index.js': 'b2' }),
  tarball('c', '1.0.0', { 'cli.js': { data: 'c', mode: 0o600 } }, { manifest: { bin: 'cli.js' } }),
  tarball('d', '1.0.0'),
  tarball('mac', '1.0.0', {}, { manifest: { os: ['darwin'] } }),
  tarball('p', '1.0.0', {}, { manifest: { peerDependencies: { b: '^2.0.0' } } }),
])
const T = Object.fromEntries(TARBALLS.map((t) => [`${t.name}@${t.version}`, t]))
const sha1 = (bytes) => createHash('sha1').update(bytes).digest('hex')

// An entry as yarn writes it: its patterns, then the package's version,
// tarball and integrity, then its dependencies.
const entry = (keys, id, dependencies = '', { hash = sha1(T[id].bytes) } = {}) => {
  const { name, version, integrity } = T[id]
  return `${keys}:
  version "${version}"
  resolved "https://registry.yarnpkg.com/${name}/-/${name}-${version}.tgz#${hash}"
  integrity ${integrity}
${dependencies}`
}
const lockfile = (...entries) => `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


${entries.join('\n')}`

const A = entry('a@^1.0.0', 'a@1.0.0', '  dependencies:\n    b "^1.0.0"\n')
const LOCKFILE = lockfile(
  A,
  entry('b@^1.0.0', 'b@1.0.0'),
  entry('b@^2.0.0', 'b@2.0.0'),
  entry('d@latest', 'd@1.0.0'),
  entry('mac@1.0.0', 'mac@1.0.0'),
  entry('"my-c@npm:c@1.0.0"', 'c@1.0.0'),
  entry('p@1.0.0', 'p@1.0.0'),
)
const ROOT = {
  name: 'root',
  version: '1.0.0',
  dependencies: { a: '^1.0.0', b: '^2.0.0', 'my-c': 'npm:c@1.0.0', p: '1.0.0' },
  devDependencies: { d: 'latest' },
  optionalDependencies: { mac: '1.0.0' },
}

const projectOf = (files) => createVfs(Object.fromEntries(Object.entries(files).map(([path, text]) => [path, typeof text === 'string' ? text : JSON.stringify(text)])))
const project = (files = {}) => projectOf({ 'yarn.lock': LOCKFILE, 'package.json': ROOT, ...files })
const build = (options = {}) => buildYarn1Tree({ project: project(), host: HOST, ...options })
const text = (vfs, path) => new TextDecoder().decode(vfs.readFile(path))
const mode = (vfs, path) => vfs.stat(path).mode

describe('buildYarn1Tree', () => {
  it('builds the tree yarn 1.22 installs', async () => {
    const calls = stubRegistry(TARBALLS)
    const { vfs, stats } = await build()
    assert.equal(calls.length, 7, 'every package, the one the host cannot run among them, as yarn fetches all before it checks any')
    assert.deepEqual(vfs.readdir('/node_modules'), ['a', 'b', 'd', 'my-c', 'p'])
    assert.deepEqual(vfs.readdir('/node_modules/a'), ['bin', 'node_modules', 'package.json', 'x.sh'])
    assert.deepEqual(vfs.readdir('/node_modules/a/node_modules'), ['b'])
    assert.equal(text(vfs, '/node_modules/a/node_modules/b/index.js'), 'b1')
    assert.equal(text(vfs, '/node_modules/b/index.js'), 'b2')
    assert.equal(mode(vfs, '/node_modules/a/bin/a.js'), 0o755)
    assert.equal(mode(vfs, '/node_modules/a/x.sh'), 0o744)
    assert.equal(mode(vfs, '/node_modules/my-c/cli.js'), 0o755)
    assert.equal(mode(vfs, '/node_modules/a/package.json'), 0o644)
    assert.ok(stats.bytes > 0)
    assert.deepEqual({ ...stats, bytes: 0 }, { packages: 7, skipped: 1, installed: 6, files: 11, bytes: 0, links: 0 })
  })

  it('builds the same tree from the files given', async () => {
    stubRegistry(TARBALLS)
    const read = await build()
    const given = await buildYarn1Tree({ lockfile: LOCKFILE, manifests: { '.': JSON.stringify(ROOT) }, project: projectOf({}), host: HOST })
    assert.deepEqual([...given.vfs.walk('/')].map(({ path }) => path), [...read.vfs.walk('/')].map(({ path }) => path))
  })

  it('links a workspace, and installs what yarn hoists beneath it in its own node_modules', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { b: '^2.0.0' } }
    const w = { name: 'w', version: '1.0.0', dependencies: { a: '1.0.0', b: '^1.0.0' } }
    const lock = lockfile(entry('a@1.0.0', 'a@1.0.0', '  dependencies:\n    b "^1.0.0"\n'), entry('b@^1.0.0', 'b@1.0.0'), entry('b@^2.0.0', 'b@2.0.0'))
    const files = projectOf({ 'yarn.lock': lock, 'package.json': root, 'packages/w/package.json': w, 'packages/w/index.js': 'w' })
    assert.deepEqual(findYarn1Workspaces({ project: files }), ['.', 'packages/w'])
    const { vfs, stats } = await buildYarn1Tree({ project: files, host: HOST, vfs: files })
    assert.equal(vfs.readlink('/node_modules/w'), '../packages/w')
    assert.equal(text(vfs, '/node_modules/w/index.js'), 'w')
    assert.equal(text(vfs, '/packages/w/node_modules/b/index.js'), 'b1')
    assert.equal(text(vfs, '/node_modules/a/node_modules/b/index.js'), 'b1')
    assert.equal(text(vfs, '/node_modules/b/index.js'), 'b2')
    assert.equal(stats.links, 1)
  })

  it('gives a dependency a resolution applies to the resolution\'s package', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', dependencies: { a: '^1.0.0', b: '^2.0.0' }, resolutions: { 'a/b': '2.0.0' } }
    const lock = lockfile(A, entry('b@2.0.0, b@^1.0.0, b@^2.0.0', 'b@2.0.0'))
    const { vfs } = await buildYarn1Tree({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }), host: HOST })
    assert.deepEqual(vfs.readdir('/node_modules/a'), ['bin', 'package.json', 'x.sh'])
  })

  it('passes over settings that only move where yarn fetches from', async () => {
    stubRegistry(TARBALLS)
    const files = { '.yarnrc': 'registry "https://registry.npmjs.org/"\n--install.frozen-lockfile true\n', '.npmrc': '//registry.npmjs.org/:_authToken=${TOKEN}\n' }
    await buildYarn1Tree({ project: project(files), host: HOST })
  })
})

describe('buildYarn1Tree refuses', () => {
  const refuses = (options, pattern) => assert.rejects(buildYarn1Tree({ host: HOST, ...options }), pattern)

  it('a tag at the top without the project, or where the project has a directory of its name', async () => {
    stubRegistry(TARBALLS)
    await refuses({ lockfile: LOCKFILE, manifests: { '.': JSON.stringify(ROOT) } }, /^DeptreeError: "d@latest": yarn installs the directory "latest" for it where the project has one, which is known only with the project read$/u)
    await refuses({ project: project({ 'latest/package.json': '{}' }) }, /^DeptreeError: "d@latest": yarn installs the directory "latest" for it, which is not supported$/u)
  })

  it('two tags yarn would resolve in the order the filesystem answers', async () => {
    stubRegistry(TARBALLS)
    const root = { name: 'root', version: '1.0.0', private: true, workspaces: ['packages/*'], dependencies: { d: 'latest' } }
    const w = { name: 'w', version: '1.0.0', dependencies: { p: 'latest' } }
    const lock = lockfile(entry('d@latest', 'd@1.0.0'), entry('p@latest', 'p@1.0.0'))
    const files = projectOf({ 'yarn.lock': lock, 'package.json': root, 'packages/w/package.json': w })
    await refuses({ project: files }, /^DeptreeError: yarn resolves these in the order the filesystem answers it, which is not set: "d@latest", "p@latest"$/u)
  })

  it('a package from anywhere but the registry, before fetching anything', async () => {
    const calls = stubRegistry(TARBALLS)
    const url = 'https://registry.yarnpkg.com/d/-/d-1.0.0.tgz'
    const root = { name: 'root', version: '1.0.0', dependencies: { d: url } }
    const lock = lockfile(entry(`"d@${url}"`, 'd@1.0.0'))
    await refuses({ project: projectOf({ 'yarn.lock': lock, 'package.json': root }) }, new RegExp(`^DeptreeError: "d@${url.replaceAll('.', '\\.')}": only a semver range, an npm: alias or a tag is supported$`, 'u'))
    assert.equal(calls.length, 0)
  })

  it('a tarball that is not the one the lockfile pins', async () => {
    stubRegistry(TARBALLS)
    const lock = LOCKFILE.replace(sha1(T['d@1.0.0'].bytes), sha1(T['p@1.0.0'].bytes))
    await refuses({ project: project({ 'yarn.lock': lock }) }, /^DeptreeError: "d@latest": the tarball's sha1 is not [\da-f]{40}$/u)
  })

  it('a package the host cannot run, where it is not optional', async () => {
    stubRegistry(TARBALLS)
    const root = { ...ROOT, dependencies: { ...ROOT.dependencies, mac: '1.0.0' }, optionalDependencies: undefined }
    await refuses({ project: project({ 'package.json': root }) }, /^DeptreeError: "mac@1\.0\.0": its os, \["darwin"\], does not take "linux", and it is not optional, which yarn fails on$/u)
  })

  it('a setting that may change what yarn installs', async () => {
    await refuses({ project: project({ '.yarnrc': '--install.production true\n' }) }, /^DeptreeError: \.yarnrc:1: "--install\.production" is a setting not supported here/u)
    await refuses({ project: project({ '.npmrc': 'ignore-optional=true\n' }) }, /^DeptreeError: \.npmrc:1: "ignore-optional" is a setting not supported here/u)
  })

  it('a yarn this does not build for, or another than the project pins', async () => {
    await refuses({ project: project(), host: { ...HOST, yarn: '1.21.1' } }, /^DeptreeError: host\.yarn: yarn "1\.21\.1" is not supported: only yarn 1\.22\.x is$/u)
    await refuses({ project: project(), host: { ...HOST, os: 'win32' } }, /^DeptreeError: host\.os: Windows is not supported/u)
    await refuses({ project: project({ 'package.json': { ...ROOT, packageManager: 'yarn@1.22.19' } }) }, /^DeptreeError: manifests\["\."\]\.packageManager: the project is installed by yarn 1\.22\.19, which corepack runs, not 1\.22\.22$/u)
    await assert.rejects(buildYarn1Tree({ project: project(), host: { ...HOST, yarn: undefined } }), TypeError)
  })

  it('a lockfile the lockfile reader refuses', async () => {
    await refuses({ project: project({ 'yarn.lock': LOCKFILE.replace('  version "2.0.0"', '  version "1.0.0"') }) }, LockfileError)
  })

  it('what yarn would read beyond the files given', async () => {
    await refuses({ project: project({ 'yarn.json': '{}' }) }, /^DeptreeError: yarn\.json: a yarn\.json, which yarn reads as a manifest too, is not supported$/u)
    await refuses({ project: project({ '.yarnrc.yml': 'yarnPath: .yarn/releases/yarn.cjs\n' }) }, /^DeptreeError: \.yarnrc\.yml: a \.yarnrc\.yml, whose yarnPath yarn 1\.22 runs in its stead, is not supported$/u)
    const root = { ...ROOT, private: true, workspaces: ['packages/*'] }
    await refuses({ project: project({ 'package.json': root, 'packages/node_modules/package.json': '{}' }) }, /^DeptreeError: "packages\/node_modules": yarn would read this node_modules as a workspace/u)
  })

  it('a root that is not the files of one install', async () => {
    await refuses({ project: project({ 'node_modules/x': '' }), vfs: projectOf({ 'node_modules/x': '' }) }, DeptreeError)
    await refuses({ project: project({ 'package.json': { ...ROOT, name: '.root' } }) }, /^DeptreeError: manifests\["\."\]\.name: "\.root" is a name yarn fails on$/u)
    await refuses({ project: project({ 'package.json': { ...ROOT, workspaces: { packages: [], nohoist: ['**'] } } }) }, /nohoist is not supported/u)
  })
})
