[package]
name = "lib"
version.workspace = true
edition.workspace = true

[features]
std = ["memchr?/std"]
extra = ["dep:extra"]

[dependencies]
memchr = { workspace = true, optional = true }
extra = { path = "../extra", optional = true }

[target.'cfg(unix)'.dependencies]
memchr = { workspace = true, features = ["alloc"] }
