import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { LockfileError, TomlError, parsePoetryLock } from '../../poetry.js'

const H = 'a'.repeat(64)
const C = 'c'.repeat(40)

// Of lock-version 2.1: a package from PyPI with its files, dependencies of
// each shape Poetry writes and extras; one from git, in two groups with a
// marker for one; and the project's extras.
const BASE = `# This file is automatically @generated by Poetry 2.3.3 and should not be changed by hand.

[[package]]
name = "a"
version = "1.0.0"
description = "A."
optional = false
python-versions = ">=3.8"
groups = ["main"]
files = [
    {file = "a-1.0.0-py3-none-any.whl", hash = "sha256:${H}"},
    {file = "a-1.0.0.tar.gz", hash = "sha256:${H}"},
]

[package.dependencies]
b = {git = "https://github.com/o/b", branch = "main"}
c = ">=1.0,<2.0 || >2.1"
PySocks = {version = ">=1.5.6", optional = true, markers = "extra == \\"socks\\""}
d = [
    {version = "1.0", markers = "python_version < \\"3.12\\""},
    {path = "../d", develop = true, markers = "python_version >= \\"3.12\\""},
]

[package.extras]
socks = ["PySocks (>=1.5.6,!=1.5.7)"]

[[package]]
name = "b"
version = "2.0.0"
description = ""
optional = true
python-versions = "*"
groups = ["main", "dev"]
markers = {dev = "sys_platform == \\"win32\\""}
files = []
develop = false

[package.source]
type = "git"
url = "https://github.com/o/b"
reference = "main"
resolved_reference = "${C}"

[extras]
git = ["b"]

[metadata]
lock-version = "2.1"
python-versions = ">=3.11"
content-hash = "${H}"
`

function edit(...edits) {
  let text = BASE
  for (const [from, to] of edits) {
    assert.ok(text.includes(from), `BASE has no ${JSON.stringify(from)}`)
    text = text.replace(from, to)
  }
  return text
}

const refuses = (text, message, where) => assert.throws(() => parsePoetryLock(text), (error) => {
  assert.ok(error instanceof LockfileError, error.stack)
  assert.equal(error.message, where === undefined ? message : `${where}: ${message}`)
  assert.equal(error.where, where)
  return true
})

const plain = (value) => JSON.parse(JSON.stringify(value))

describe('lock-version 2.1', () => {
  const lock = parsePoetryLock(BASE)

  it('the metadata, the project\'s extras, and each package in order', () => {
    assert.deepEqual([lock.lockVersion, lock.pythonVersions, lock.contentHash], ['2.1', '>=3.11', H])
    assert.deepEqual(plain(lock.extras), { git: ['b'] })
    assert.deepEqual(lock.packages.map((pkg) => `${pkg.name} ${pkg.version}`), ['a 1.0.0', 'b 2.0.0'])
  })

  it('the groups each is in, and the marker each needs it with', () => {
    assert.deepEqual(lock.packages[0].groups, ['main'])
    assert.deepEqual({ ...lock.packages[0].markers }, { main: undefined })
    assert.deepEqual({ ...lock.packages[1].markers }, { main: undefined, dev: 'sys_platform == "win32"' })
  })

  it('every shape of dependency Poetry writes', () => {
    assert.deepEqual(plain(lock.packages[0].dependencies), {
      b: [{ type: 'git', git: 'https://github.com/o/b', reference: { kind: 'branch', name: 'main' }, extras: [], optional: false }],
      c: [{ type: 'version', version: '>=1.0,<2.0 || >2.1', extras: [], optional: false }],
      PySocks: [{ type: 'version', version: '>=1.5.6', extras: [], optional: true, markers: 'extra == "socks"' }],
      d: [
        { type: 'version', version: '1.0', extras: [], optional: false, markers: 'python_version < "3.12"' },
        { type: 'path', path: '../d', develop: true, extras: [], optional: false, markers: 'python_version >= "3.12"' },
      ],
    })
  })

  it('files, extras, and a git source at its commit', () => {
    assert.deepEqual(plain(lock.packages[0].files[1]), { file: 'a-1.0.0.tar.gz', hash: `sha256:${H}` })
    assert.deepEqual(plain(lock.packages[0].extras), { socks: ['PySocks (>=1.5.6,!=1.5.7)'] })
    assert.deepEqual(plain(lock.packages[1].source), { type: 'git', url: 'https://github.com/o/b', reference: 'main', commit: C })
    assert.deepEqual([lock.packages[0].source, lock.packages[0].develop, lock.packages[1].develop], [undefined, undefined, false])
  })

  it('one marker for every group', () => {
    const one = parsePoetryLock(edit(['markers = {dev = "sys_platform == \\"win32\\""}', 'markers = "sys_platform == \\"win32\\""']))
    assert.deepEqual({ ...one.packages[1].markers }, { main: 'sys_platform == "win32"', dev: 'sys_platform == "win32"' })
  })
})

describe('the format', () => {
  it('lock-version 2.0, of Poetry 1.8, without groups or markers', () => {
    const text = edit(['lock-version = "2.1"', 'lock-version = "2.0"'], ['groups = ["main"]\n', ''], ['groups = ["main", "dev"]\nmarkers = {dev = "sys_platform == \\"win32\\""}\n', ''])
    const lock = parsePoetryLock(text)
    assert.deepEqual([lock.packages[0].groups, lock.packages[0].markers], [undefined, undefined])
    refuses(edit(['lock-version = "2.1"', 'lock-version = "2.0"']), 'unsupported key "groups"', 'package[0]')
  })

  it('refuses lock-version 1, its files in [metadata] and its categories, and a version after 2.1', () => {
    refuses(edit(['lock-version = "2.1"', 'lock-version = "1.1"']), 'lock-version 1.1 is Poetry 1.4\'s or older, which is not read here', 'metadata["lock-version"]')
    refuses(edit(['lock-version = "2.1"', 'lock-version = "2.2"']), 'unsupported lock-version: expected "2.0" or "2.1", found the string "2.2"', 'metadata["lock-version"]')
    refuses(edit(['content-hash', 'files = {}\ncontent-hash']), 'metadata.files is lock-version 1, which is not read here', 'metadata.files')
    refuses(edit(['optional = false', 'category = "main"\noptional = false']), '`category` is lock-version 1, which Poetry 1.4 and older write and is not read here', 'package[0].category')
    refuses(edit(['[metadata]', '[other]']).replace(/\nlock-version.*\n.*\n.*\n$/u, '\n'), 'unsupported key "other"')
  })

  it('refuses a key Poetry does not write, and a TypeError and a TomlError', () => {
    refuses(edit(['optional = false', 'optional = false\nyanked = true']), 'unsupported key "yanked"', 'package[0]')
    assert.throws(() => parsePoetryLock(null), TypeError)
    assert.throws(() => parsePoetryLock('[[package]'), TomlError)
  })
})

describe('packages', () => {
  it('refuses a name, a version or a marker PEP 508 and PEP 440 do not read', () => {
    refuses(edit(['name = "a"', 'name = "a b"']), '"a b" is not a package name', 'package[0].name')
    refuses(edit(['version = "1.0.0"', 'version = "1.0.0-final"']), '"1.0.0-final" is not a version', 'package[0].version')
    refuses(edit(['markers = {dev = "sys_platform', 'markers = {dev = "platform']), '"platform == \\"win32\\"" is not an environment marker', 'package[1].markers.dev')
  })

  it('refuses a marker of a group the package is not in, and no group', () => {
    refuses(edit(['markers = {dev', 'markers = {test']), '"test" is not one of the package\'s groups', 'package[1].markers.test')
    refuses(edit(['groups = ["main"]', 'groups = []']), 'expected a group at least', 'package[0].groups')
    refuses(edit(['groups = ["main"]', 'groups = ["main", "Main"]']), '"main" is listed twice', 'package[0].groups[1]')
  })

  it('refuses develop but of a directory or git, and its absence there', () => {
    refuses(edit(['groups = ["main"]', 'groups = ["main"]\ndevelop = true']), 'develop, which Poetry writes of a directory or a git source alone', 'package[0].develop')
    refuses(edit(['files = []\ndevelop = false', 'files = []']), 'expected develop, which Poetry writes of a directory or a git source', 'package[1]')
  })

  it('refuses a git source but at a full commit, and a source of a type Poetry does not write', () => {
    refuses(edit([`resolved_reference = "${C}"`, 'resolved_reference = "ccccccc"']), '"ccccccc" is not a full commit hash, as Poetry writes', 'package[1].source.resolved_reference')
    refuses(edit(['type = "git"', 'type = "hg"']), 'expected one of legacy, git, url, file, directory', 'package[1].source.type')
    refuses(edit(['reference = "main"', 'reference = "main"\npath = "x"']), 'unsupported key "path"', 'package[1].source')
  })

  it('refuses a file twice, a path for its name, and a hash out of hex', () => {
    refuses(edit(['{file = "a-1.0.0.tar.gz"', '{file = "a-1.0.0-py3-none-any.whl"']), '"a-1.0.0-py3-none-any.whl" is listed twice', 'package[0].files[1]')
    refuses(edit(['{file = "a-1.0.0.tar.gz"', '{file = "dist/a-1.0.0.tar.gz"']), '"dist/a-1.0.0.tar.gz" is not a file\'s name', 'package[0].files[1].file')
    refuses(edit([`{file = "a-1.0.0.tar.gz", hash = "sha256:${H}"}`, '{file = "a-1.0.0.tar.gz", hash = "sha256:abc"}']), '"abc" is not a sha256 digest in lowercase hex', 'package[0].files[1].hash')
  })

  it('refuses a dependency of two kinds, of none, or with a field not of its kind', () => {
    refuses(edit(['b = {git = "https://github.com/o/b", branch = "main"}', 'b = {git = "https://github.com/o/b", version = "1"}']), 'expected one of version, path, url, git, found version and git', 'package[0].dependencies.b')
    refuses(edit(['b = {git = "https://github.com/o/b", branch = "main"}', 'b = {optional = true}']), 'expected one of version, path, url, git, found none', 'package[0].dependencies.b')
    refuses(edit(['{path = "../d", develop = true,', '{path = "../d", branch = "x",']), 'a field Poetry does not write for a path dependency', 'package[0].dependencies.d[1].branch')
    refuses(edit(['branch = "main"}', 'branch = "main", tag = "v1"}']), 'branch and tag, of which Poetry writes one', 'package[0].dependencies.b')
  })

  it('refuses a name that is another\'s in normal form, and a package listed twice', () => {
    refuses(edit(['c = ">=1.0', 'pysocks = "1"\nc = ">=1.0']), '"PySocks" and "pysocks" are one name', 'package[0].dependencies.PySocks')
    const again = '[[package]]\nname = "A"\nversion = "1.0"\ndescription = ""\noptional = false\npython-versions = "*"\ngroups = ["main"]\nfiles = []\n\n[extras]'
    refuses(edit(['[extras]', again]), '"A 1.0" is listed twice, first as package[0]', 'package[2]')
  })

  it('refuses an extra\'s requirement PEP 508 does not read', () => {
    refuses(edit(['socks = ["PySocks (>=1.5.6,!=1.5.7)"]', 'socks = ["PySocks (>=1.5.6"]']), '"PySocks (>=1.5.6" is not a requirement', 'package[0].extras.socks[0]')
  })

  it('refuses a root extra of no package', () => {
    refuses(edit(['git = ["b"]', 'git = ["e"]']), '"e" names no package in the lockfile', 'extras.git[0]')
  })
})
