import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { describe, it } from 'node:test'
import { LockfileError } from '../../src/error.js'
import { readEntries } from '../../src/yarn1/syntax.js'
import { yarnParse } from './reference.js'
import { random } from '../random.js'

// yarn 1.22.22's own reader against this one, over documents made at
// random: the fixtures with edits, and documents put together from what
// yarn writes and what it does not. Every document read here yarn reads,
// by its own reader and not as YAML, to the same patterns and fields; so
// every one yarn does not read is refused here. The seeds are fixed, so a
// failure names its document and comes back on a rerun.

const FIXTURES = new URL('fixtures/', import.meta.url)
const FILES = readdirSync(FIXTURES).filter((name) => name.endsWith('.lock')).sort()
const text = (name) => readFileSync(new URL(name, FIXTURES), 'utf8')

const HEADER = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n'

// What yarn quotes, as its stringify.js has it.
const quoted = (value) => value.startsWith('true') || value.startsWith('false') || /[:\s\\",[\]]/u.test(value) || /^\d/u.test(value) || !/^[A-Za-z]/u.test(value)

const STRINGS = [
  '1.0.0', '^1.0.0', 'latest', 'a', 'A', 'Z9', 'null', 'true', 'truex', 'falsey', 'nullish', '', ' ', 'a b', 'a:b', 'a,b', 'a"b',
  'a\\', 'a\\"b', '\\"', '\\\\', '-a', '.a', '/a', '@a/b', 'a#b', "a'b", 'a{b}', 'a[b]', 'é', 'aé', '\u00A0a', 'a\u00A0', 'x\u0001',
  'x\u007F', 'a\tb', 'a\nb', 'x\u2028', 'x\uD800', 'sha512-abc==', 'https://x/y.tgz#abc', 'git+https://x.git#1', '>=1 <2', '1 || 2',
]
const KEYS = ['a@1', '@s/a@^1', 'a@', 'a@npm:b@1', 'true@1', 'null@1', 'a b@1', 'a@1 || 2', 'a@file:./x', 'b@git+https://x#y', 'x', '"q"@1']
const FIELDS = ['version', 'resolved', 'integrity', 'uid', 'name', 'x', 'null', 'true', '1', 'a b']

// A string as yarn writes it, or, now and then, as it does not.
function write({ next, pick }, value) {
  if (next() < 0.1) return pick([JSON.stringify(value), value, `"${value}"`, `'${value}'`])
  return quoted(value) ? JSON.stringify(value) : value
}

// Documents put together from the pieces of an entry.
function assemble(rand) {
  const { next, pick } = rand
  let doc = next() < 0.95 ? HEADER : pick(['', '# yarn lockfile v1\n', `${HEADER}# yarn lockfile v2\n`])
  if (next() < 0.2) doc += '# yarn v1.22.22\n# node v24.15.0\n'
  doc += pick(['\n\n', '\n', '', '\n\n\n'])
  const entries = Math.floor(next() * 4)
  for (let i = 0; i < entries; i++) {
    const keys = Array.from({ length: 1 + Math.floor(next() * 3) }, () => write(rand, next() < 0.7 ? pick(KEYS) : pick(STRINGS)))
    doc += `${keys.join(next() < 0.95 ? ', ' : pick([',', ' ,', ',  ']))}${next() < 0.95 ? ':' : pick(['', ' :', ': x'])}\n`
    const fields = 1 + Math.floor(next() * 4)
    for (let j = 0; j < fields; j++) {
      const indent = next() < 0.95 ? '  ' : pick([' ', '   ', '    ', ''])
      if (next() < 0.25) {
        doc += `${indent}${pick(['dependencies', 'optionalDependencies'])}:\n`
        const deps = Math.floor(next() * 3)
        for (let k = 0; k < deps; k++) doc += `${next() < 0.95 ? '    ' : pick(['  ', '     ', '      '])}${write(rand, pick(STRINGS))} ${write(rand, pick(STRINGS))}\n`
      } else {
        doc += `${indent}${write(rand, pick(FIELDS))}${next() < 0.95 ? ' ' : pick([': ', '  ', ':'])}${write(rand, pick(STRINGS))}${next() < 0.97 ? '' : pick([' ', ' # c', ','])}\n`
      }
      if (next() < 0.03) doc += pick(['\n', '# c\n', '  \n'])
    }
    doc += next() < 0.9 ? '\n' : pick(['', '\n\n'])
  }
  return next() < 0.1 ? doc.replaceAll('\n', '\r\n') : doc
}

const PIECES = ['"', '\\', ' ', ':', ',', '#', '\n', '\r', '\r\n', '\t', '1', 'true', 'null', '@', '-', '.', '/', '\u00A0', 'é', '\uFEFF', '<<<<<<<', '=======', '>>>>>>>', "'", '[', 'x']

// A fixture with an edit or three: to its lines, or its characters.
function edited(rand, source) {
  const { next, pick } = rand
  let doc = source
  for (let edits = 1 + Math.floor(next() * 3); edits > 0; edits--) {
    const lines = doc.split('\n')
    const at = Math.floor(next() * lines.length)
    const r = next()
    if (r < 0.1) lines.splice(at, 1)
    else if (r < 0.2) lines.splice(at, 0, lines[at])
    else if (r < 0.3) lines.splice(at, 0, pick(['', '# c', '  ', '  # c']))
    else if (r < 0.4) lines[at] = pick([' ', '  ', '']) + lines[at].replace(next() < 0.5 ? /^ {1,2}/u : /^$/u, '')
    else if (r < 0.5) lines[at] = lines[at].replaceAll(/"([^"\\]*)"/gu, (quote, inner) => (next() < 0.5 ? inner : quote))
    else if (r < 0.6) lines[at] = lines[at].replace(/ ([A-Za-z][^ ]*)$/u, (all, word) => ` "${word}"`)
    else {
      const pos = Math.floor(next() * doc.length)
      doc = next() < 0.5 ? doc.slice(0, pos) + pick(PIECES) + doc.slice(pos) : doc.slice(0, pos) + doc.slice(pos + 1 + Math.floor(next() * 3))
      continue
    }
    doc = lines.join('\n')
  }
  return doc
}

// What yarn's reader makes of the entries read here: each pattern a key of
// the fields of its entry.
function flatten(entries) {
  const value = Object.create(null)
  for (const { keys, fields } of entries) for (const key of keys) value[key] = fields
  return value
}

function check(doc) {
  let entries
  try {
    entries = readEntries(doc)
  } catch (error) {
    if (!(error instanceof LockfileError)) throw error
    return false
  }
  const yarn = yarnParse(doc)
  assert.equal(yarn.error, undefined, `yarn refuses ${JSON.stringify(doc)}: ${yarn.error}`)
  assert.deepEqual(structuredClone(yarn.value), structuredClone(flatten(entries)), JSON.stringify(doc))
  return true
}

describe('whatever is read here, yarn reads the same', () => {
  it('the fixtures', () => {
    for (const name of FILES) assert.equal(check(text(name)), true, name)
  })

  it('documents put together from pieces', () => {
    const rand = random(0x5EED)
    let read = 0
    for (let i = 0; i < 20_000; i++) if (check(assemble(rand))) read++
    assert.ok(read > 3000, `only ${read} documents were read`)
  })

  it('the fixtures, edited', () => {
    const rand = random(0xF1F0)
    let read = 0
    for (let i = 0; i < 20_000; i++) if (check(edited(rand, text(rand.pick(FILES))))) read++
    assert.ok(read > 1000, `only ${read} documents were read`)
  })
})
