import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { LockfileError, parseYarn1Lockfile } from '../../yarn1.js'
import { semver } from './semver.js'

// One small yarn.lock with a package of every kind — from the registry,
// with patterns merged, a sha1 integrity and an npm alias; a directory, a
// git repository, a tarball by URL and a link — in the form yarn writes,
// and the manifests of a project and its workspace; then one edit at a
// time, each of which is refused with a message that says where and why.

const I = 'sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg=='
const H = '0123456789abcdef0123456789abcdef01234567'
const I2 = `sha512-${Buffer.alloc(64, 1).toString('base64')}`
const H1 = `sha1-${Buffer.from(H, 'hex').toString('base64')}`
const C = 'fedcba9876543210fedcba9876543210fedcba98'

const HEADER = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n'

const BASE = `${HEADER}

"@s/c@^2.0.0":
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/@s/c/-/c-2.1.0.tgz#${H}"
  integrity ${I}

a@^1.0.0, a@^1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/a/-/a-1.1.0.tgz#${H}"
  integrity ${I}
  dependencies:
    "@s/c" "^2.0.0"
    b "1.0.0"

b@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"
  integrity ${H1}

"d@file:./d":
  version "0.1.0"
  dependencies:
    b "1.0.0"

"e@git+https://example.com/e.git#v3":
  version "3.0.0"
  resolved "git+https://example.com/e.git#${C}"

"f@https://example.com/f.tgz":
  version "4.0.0"
  resolved "https://example.com/f.tgz#${H}"

"l@link:./l":
  version "0.0.0"
  uid ""

"my-b@npm:b@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"
  integrity ${H1}
`

const MANIFESTS = {
  '.': {
    name: 'root',
    private: true,
    workspaces: ['w'],
    dependencies: { a: '^1.0.0', d: 'file:./d', e: 'git+https://example.com/e.git#v3', f: 'https://example.com/f.tgz', 'my-b': 'npm:b@1.0.0', w: '1.0.0' },
    devDependencies: { l: 'link:./l' },
  },
  w: { name: 'w', version: '1.0.0', dependencies: { a: '^1.1.0' } },
}

// A key as yarn writes it: quoted where yarn's maybeWrap quotes it.
const keyed = (key) => (/[:\s\\",[\]]/u.test(key) ? JSON.stringify(key) : key)

// BASE with each `[from, to]` replaced, once; `from` has to be there.
function edit(...edits) {
  let text = BASE
  for (const [from, to] of edits) {
    assert.ok(text.includes(from), `BASE has no ${JSON.stringify(from)}`)
    text = text.replace(from, to)
  }
  return text
}

// Read as by default, versions checked with semver.
const parse = (text, manifests) => parseYarn1Lockfile(text, { manifests, semver })

// `message` is the refusal's detail, which the message leads with `where`.
const refuses = (text, message, where, manifests, options) => assert.throws(() => parseYarn1Lockfile(text, { manifests, ...(options ?? { semver }) }), (error) => {
  assert.ok(error instanceof LockfileError, error.stack)
  assert.equal(error.message, where === undefined ? message : `${where}: ${message}`)
  assert.equal(error.where, where)
  return true
})

const plain = (value) => structuredClone(value)
const read = (...edits) => parse(edit(...edits)).packages

describe('the base lockfile', () => {
  const lock = parse(BASE, MANIFESTS)

  it('reads, each pattern to its package', () => {
    assert.deepEqual(Object.keys(lock.packages), [
      '@s/c@^2.0.0', 'a@^1.0.0', 'a@^1.1.0', 'b@1.0.0', 'd@file:./d', 'e@git+https://example.com/e.git#v3', 'f@https://example.com/f.tgz', 'l@link:./l', 'my-b@npm:b@1.0.0',
    ])
    assert.equal(lock.packages['a@^1.0.0'], lock.packages['a@^1.1.0'])
    assert.deepEqual(plain(lock.packages['a@^1.0.0']), {
      patterns: ['a@^1.0.0', 'a@^1.1.0'],
      name: 'a',
      version: '1.1.0',
      uid: undefined,
      resolution: { type: 'tarball', tarball: 'https://registry.yarnpkg.com/a/-/a-1.1.0.tgz', sha1: H, integrity: I },
      dependencies: { '@s/c': '@s/c@^2.0.0', b: 'b@1.0.0' },
      optionalDependencies: {},
    })
  })

  it('every kind of resolution', () => {
    const { packages } = lock
    assert.deepEqual(packages['b@1.0.0'].resolution.integrity, H1)
    assert.equal(packages['d@file:./d'].resolution, undefined)
    assert.deepEqual(packages['e@git+https://example.com/e.git#v3'].resolution, { type: 'git', repo: 'git+https://example.com/e.git', commit: C })
    assert.deepEqual(packages['f@https://example.com/f.tgz'].resolution, { type: 'tarball', tarball: 'https://example.com/f.tgz', sha1: H, integrity: undefined })
    assert.deepEqual([packages['l@link:./l'].version, packages['l@link:./l'].uid, packages['l@link:./l'].resolution], ['0.0.0', '', undefined])
    assert.equal(packages['my-b@npm:b@1.0.0'].name, 'my-b')
  })

  it('the importers, a workspace linked', () => {
    assert.deepEqual(plain(lock.importers), {
      '.': {
        dependencies: {
          a: 'a@^1.0.0', d: 'd@file:./d', e: 'e@git+https://example.com/e.git#v3', f: 'f@https://example.com/f.tgz', 'my-b': 'my-b@npm:b@1.0.0', w: 'link:w',
        },
        devDependencies: { l: 'l@link:./l' },
        optionalDependencies: {},
      },
      w: { dependencies: { a: 'a@^1.1.0' }, devDependencies: {}, optionalDependencies: {} },
    })
  })

  it('records have no prototype', () => {
    for (const record of [lock.packages, lock.importers, lock.importers['.'].dependencies, lock.packages['b@1.0.0'].dependencies]) {
      assert.equal(Object.getPrototypeOf(record), null)
    }
  })

  it('without the manifests, no importers', () => {
    const alone = parse(BASE)
    assert.equal(alone.importers, undefined)
    assert.deepEqual(plain(alone.packages), plain(lock.packages))
  })

  it('with CRLF line ends too, and without the last', () => {
    assert.deepEqual(plain(parse(BASE.replaceAll('\n', '\r\n'), MANIFESTS)), plain(lock))
    assert.deepEqual(plain(parse(BASE.trimEnd(), MANIFESTS)), plain(lock))
  })

  it('what yarn writes with nothing installed', () => {
    assert.deepEqual(plain(parse(`${HEADER}\n\n`, { '.': { name: 'e' } })), { packages: {}, importers: { '.': { dependencies: {}, devDependencies: {}, optionalDependencies: {} } } })
  })
})

describe('what else yarn writes is read', () => {
  it('the versions of yarn and Node below the header, and another tool\'s line', () => {
    const header = `${HEADER}# yarn v1.22.22\n# node v24.15.0\n# bun ./bun.lockb --hash: 5BBAC8D5E5D9B1E9-1\n`
    assert.deepEqual(plain(parse(BASE.replace(HEADER, header)).packages), plain(parse(BASE).packages))
  })

  it('an empty range, and a dependency on it', () => {
    const packages = read(['b@1.0.0:', 'b@, b@1.0.0:'], ['    b "1.0.0"', '    b ""'])
    assert.equal(packages['b@'], packages['b@1.0.0'])
    assert.equal(packages['a@^1.0.0'].dependencies.b, 'b@')
  })

  it('strings quoted for their spaces or escapes, and one bare with a quote in it', () => {
    const packages = read(['  uid ""', '  uid "a \\"b\\" \\\\"'], ['"@s/c@^2.0.0":', '"@s/c@^2.0.0", "@s/c@>= 2.0.0 <3":'])
    assert.equal(packages['l@link:./l'].uid, 'a "b" \\')
    assert.equal(packages['@s/c@>= 2.0.0 <3'].version, '2.1.0')
    assert.equal(read(['  uid ""', "  uid it's"])['l@link:./l'].uid, "it's")
  })

  it('an optional dependency, and more than one integrity', () => {
    const packages = read(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n  optionalDependencies:\n    f "https://example.com/f.tgz"\n\nb@'], [`  integrity ${H1}\n\n"d`, `  integrity "${H1} ${I}"\n\n"d`])
    assert.deepEqual(plain(packages['a@^1.0.0'].optionalDependencies), { f: 'f@https://example.com/f.tgz' })
    assert.equal(packages['b@1.0.0'].resolution.integrity, `${H1} ${I}`)
  })

  it('a tarball from a git host, with no sha1, and a local one', () => {
    const packages = read([`"f@https://example.com/f.tgz":\n  version "4.0.0"\n  resolved "https://example.com/f.tgz#${H}"`, `"f@github:u/f#v4":\n  version "4.0.0"\n  resolved "https://codeload.github.com/u/f/tar.gz/${C}"`], [
      '"l@link:./l":\n  version "0.0.0"\n  uid ""', `"l@file:vendor/l.tgz":\n  version "0.0.0"\n  resolved "file:vendor/l.tgz#${H}"`,
    ])
    assert.deepEqual(packages['f@github:u/f#v4'].resolution, { type: 'tarball', tarball: `https://codeload.github.com/u/f/tar.gz/${C}`, sha1: undefined, integrity: undefined })
    assert.equal(packages['l@file:vendor/l.tgz'].resolution.tarball, 'file:vendor/l.tgz')
  })

  it('a repository by an https URL, which yarn fetches with git', () => {
    for (const repo of ['https://example.com/x.git', 'https://github.com/u/x', 'ssh://git@example.com/x.git']) {
      const packages = read(['"e@git+https://example.com/e.git#v3":\n  version "3.0.0"\n  resolved "git+https://example.com/e.git#', `"e@${repo}#v3":\n  version "3.0.0"\n  resolved "${repo}#`])
      assert.deepEqual(packages[`e@${repo}#v3`].resolution, { type: 'git', repo, commit: C })
    }
  })

  it('a repository of a git host, by its tarball or by ssh, as yarn fetches it', () => {
    const resolved = [
      ['github:u/e#v3', `https://codeload.github.com/u/e/tar.gz/${C}`],
      ['u/e#v3', `https://codeload.github.com/u/e/tar.gz/${C}`],
      ['github:u/e.git#v3', `git+ssh://git@github.com/u/e.git#${C}`],
      ['gitlab:u/e#v3', `https://gitlab.com/u/e/repository/archive.tar.gz?ref=${C}`],
      ['bitbucket:u/e#v3', `https://bitbucket.org/u/e/get/${C}.tar.gz`],
      ['gist:abc#v3', `https://gist.github.com/abc.git#${C}`],
    ]
    for (const [range, url] of resolved) {
      const packages = read([`"e@git+https://example.com/e.git#v3":\n  version "3.0.0"\n  resolved "git+https://example.com/e.git#${C}"`, `${keyed(`e@${range}`)}:\n  version "3.0.0"\n  resolved "${url}"`])
      assert.ok(packages[`e@${range}`].resolution, range)
    }
  })

  it('a registry\'s tarball with an integrity alone, as other tools rewrite it, from another registry, or by an older spelling', () => {
    assert.equal(read([`b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `b-1.0.0.tgz"\n  integrity ${H1}\n\n"d`])['b@1.0.0'].resolution.sha1, undefined)
    assert.equal(read([`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"https://npm.example.com/b.tgz#${H}"\n  integrity ${H1}\n\n"d`])['b@1.0.0'].resolution.tarball, 'https://npm.example.com/b.tgz')
    assert.equal(read(['/@s/c/-/c-2.1.0.tgz', '/@s%2fc/-/c-2.1.0.tgz'])['@s/c@^2.0.0'].resolution.tarball, 'https://registry.yarnpkg.com/@s%2fc/-/c-2.1.0.tgz')
  })

  it('a tag or an alias beside another entry of its name and version, which yarn does not give either', () => {
    const tagged = read(['"f@https://example.com/f.tgz":', `f@latest:\n  version "4.0.0"\n  resolved "https://registry.yarnpkg.com/f/-/f-4.0.0.tgz#${H}"\n\n"f@https://example.com/f.tgz":`])
    assert.notEqual(tagged['f@latest'], tagged['f@https://example.com/f.tgz'])
    assert.ok(read(['"l@link:./l":', `"my-b@https://example.com/b.tgz":\n  version "1.0.0"\n  resolved "https://example.com/b.tgz#${H}"\n\n"l@link:./l":`])['my-b@https://example.com/b.tgz'])
  })

  it('a resolution nothing asks for, which yarn records all the same', () => {
    const text = edit(['b@1.0.0:', `z@1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/z/-/z-1.0.0.tgz#${H}"\n\nb@1.0.0:`])
    assert.equal(parse(text, { ...MANIFESTS, '.': { ...MANIFESTS['.'], resolutions: { z: '1.0.0' } } }).packages['z@1.0.0'].version, '1.0.0')
  })
})

describe('with the manifests', () => {
  const lock = (text, manifests) => parse(text, manifests)
  const root = MANIFESTS['.']
  const withRoot = (fields) => ({ ...MANIFESTS, '.': { ...root, ...fields } })

  it('a workspace\'s file: and link: are read from the lockfile\'s directory', () => {
    const manifests = { ...MANIFESTS, w: { name: 'w', version: '1.0.0', dependencies: { a: '^1.1.0', d: 'file:../d/', l: 'link:./../l' } } }
    const text = edit(['"d@file:./d":', '"d@file:./d", "d@file:d":'])
    assert.deepEqual(plain(lock(text, manifests).importers.w.dependencies), { a: 'a@^1.1.0', d: 'd@file:d', l: 'l@link:./l' })
  })

  it('a "//" in a list is a comment, as yarn drops it', () => {
    assert.equal('//' in lock(BASE, withRoot({ devDependencies: { '//': 'a note', l: 'link:./l' } })).importers['.'].devDependencies, false)
  })

  it('a resolution\'s own pattern, beside those it was applied to', () => {
    const text = edit(['a@^1.0.0, a@^1.1.0:', 'a@1.1.0, a@^1.0.0, a@^1.1.0:'])
    assert.equal(lock(text, withRoot({ resolutions: { '**/a': '1.1.0' } })).packages['a@1.1.0'].version, '1.1.0')
    refuses(text, 'nothing asks for it: no manifest, no package and no resolution', '["a@1.1.0"]', MANIFESTS)
    refuses(text, '"x/**/a/" is a path yarn ignores', 'manifests["."].resolutions["x/**/a/"]', withRoot({ resolutions: { 'x/**/a/': '1.1.0' } }))
    assert.equal(lock(text, withRoot({ resolutions: { 'x/**/a': '1.1.0', '@s/c/a': '1.1.0' } })).packages['a@1.1.0'].version, '1.1.0')
  })

  it('refuses a pattern nothing asks for', () => {
    const others = Object.fromEntries(Object.entries(root.dependencies).filter(([name]) => name !== 'w'))
    refuses(BASE, 'nothing asks for it: no manifest, no package and no resolution', '["a@^1.1.0"]', { '.': { ...root, dependencies: others } })
    refuses(edit(['"@s/c@^2.0.0":', '"@s/c@^1.0.0", "@s/c@^2.0.0":']), 'nothing asks for it: no manifest, no package and no resolution', '["@s/c@^1.0.0"]', MANIFESTS)
    refuses(edit(['"@s/c@^2.0.0":', '"@s/c@^1.0.0", "@s/c@^2.0.0":']), 'nothing asks for it: no manifest, no package and no resolution', '["@s/c@^1.0.0"]', MANIFESTS, { checkVersions: false })
  })

  it('a package\'s dependency on a workspace, which yarn links and writes no entry for', () => {
    const text = edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n    w "^1.0.0"\n\nb@'])
    assert.equal(lock(text, MANIFESTS).packages['a@^1.0.0'].dependencies.w, 'link:w')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n    x "^1.0.0"\n\nb@']), '"x@^1.0.0" is not a pattern of the lockfile', '["a@^1.0.0"].dependencies.x', MANIFESTS)
  })

  it('refuses a dependency the lockfile has no pattern for', () => {
    refuses(BASE, '"a@^1.2.0" is not a pattern of the lockfile', 'manifests.w.dependencies.a', { ...MANIFESTS, w: { name: 'w', version: '1.0.0', dependencies: { a: '^1.2.0' } } })
    refuses(BASE, '"x@1.0.0" is not a pattern of the lockfile', 'manifests["."].dependencies.x', withRoot({ dependencies: { x: '1.0.0' } }))
  })

  it('refuses an absolute path', () => {
    refuses(BASE, '"file:/d" is an absolute path', 'manifests["."].dependencies.d', withRoot({ dependencies: { ...root.dependencies, d: 'file:/d' } }))
    refuses(BASE, '"/d" is an absolute path', 'manifests["."].dependencies.d', withRoot({ dependencies: { ...root.dependencies, d: '/d' } }))
  })

  it('refuses manifests that are not a project and its workspaces', () => {
    refuses(BASE, 'expected the manifest beside the lockfile, "."', 'manifests', { w: MANIFESTS.w })
    refuses(BASE, 'expected workspaces, as there are manifests of workspaces', 'manifests["."].workspaces', withRoot({ workspaces: undefined }))
    refuses(BASE, 'the name of the workspace "w" too', 'manifests.v.name', { ...withRoot({ workspaces: ['w', 'v'] }), v: MANIFESTS.w })
    refuses(BASE, 'expected a string, found nothing', 'manifests.w.name', { ...MANIFESTS, w: { dependencies: { a: '^1.1.0' } } })
    refuses(BASE, 'expected a mapping, found the string "{}"', 'manifests', '{}')
    refuses(BASE, 'expected a string, found the number 1', 'manifests["."].dependencies.w', withRoot({ dependencies: { ...root.dependencies, w: 1 } }))
    refuses(BASE, '"a/./b" is not a relative path in normal form', 'manifests["a/./b"]', { ...MANIFESTS, 'a/./b': {} })
  })

  it('reads workspaces as yarn does, and refuses those it does not', () => {
    const ws = 'manifests["."].workspaces'
    for (const workspaces of [['./w/'], ['*'], ['**'], { packages: ['w'], nohoist: ['**/x'] }]) assert.ok(lock(BASE, withRoot({ workspaces })).importers.w)
    refuses(BASE, 'expected true, as yarn has workspaces in a private project alone', 'manifests["."].private', withRoot({ private: undefined }))
    refuses(BASE, 'expected a mapping, found the string "w"', ws, withRoot({ workspaces: 'w' }))
    refuses(BASE, 'unsupported field "x"', ws, withRoot({ workspaces: { packages: ['w'], x: [] } }))
    refuses(BASE, 'expected a string, found the number 1', `${ws}.nohoist[0]`, withRoot({ workspaces: { packages: ['w'], nohoist: [1] } }))
    refuses(BASE, '"{w,v}" is a glob not read here', `${ws}[0]`, withRoot({ workspaces: ['{w,v}'] }))
    const found = "not a workspace the root's `workspaces` finds"
    refuses(BASE, found, 'manifests.v', { ...MANIFESTS, v: { name: 'v', version: '1.0.0' } })
    refuses(BASE, found, 'manifests[".v"]', { ...withRoot({ workspaces: ['*'] }), '.v': { name: 'v', version: '1.0.0' } })
    refuses(BASE, found, 'manifests["node_modules/x"]', { ...withRoot({ workspaces: ['w', 'node_modules/x'] }), 'node_modules/x': { name: 'x', version: '1.0.0' } })
    refuses(BASE, 'expected a version, without which yarn ignores the workspace', 'manifests.w.version', { ...MANIFESTS, w: { name: 'w', dependencies: { a: '^1.1.0' } } })
    refuses(BASE, "a workspace's, which yarn does not read", 'manifests.w.resolutions', { ...MANIFESTS, w: { ...MANIFESTS.w, resolutions: {} } })
  })

  it('refuses an entry of a workspace\'s name and version, as yarn links the workspace', () => {
    const w = `w@1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/w/-/w-1.0.0.tgz#${H}"\n\n"l@link:./l":`
    const message = '"w@1.0.0" is satisfied by the workspace "w", which yarn links instead'
    refuses(edit(['"l@link:./l":', w]), message, 'manifests["."].dependencies.w', MANIFESTS)
    refuses(edit(['"l@link:./l":', w], ['    b "1.0.0"\n\nb@', '    b "1.0.0"\n    w "1.0.0"\n\nb@']), message, '["a@^1.0.0"].dependencies.w', MANIFESTS)
  })

  it('refuses a resolution\'s path of what is not a name, or a glob of one', () => {
    const text = edit(['a@^1.0.0, a@^1.1.0:', 'a@1.1.0, a@^1.0.0, a@^1.1.0:'])
    assert.equal(lock(text, withRoot({ resolutions: { '@s/*/a': '1.1.0', '**/?/a': '1.1.0' } })).packages['a@1.1.0'].version, '1.1.0')
    refuses(text, '"x y" is not a package name, or a glob of one', 'manifests["."].resolutions["x y/a"]', withRoot({ resolutions: { 'x y/a': '1.1.0' } }))
  })

  it('refuses a dependency in two lists, or a list yarn does not read', () => {
    refuses(BASE, 'listed under dependencies too', 'manifests["."].devDependencies.a', withRoot({ devDependencies: { l: 'link:./l', a: '^1.0.0' } }))
    refuses(BASE, 'a field yarn does not read, for "devDependencies"', 'manifests["."].devdependencies', withRoot({ devdependencies: {} }))
  })

  it('refuses a dependency not given what a resolution resolves it to', () => {
    const text = edit(['b@1.0.0:', `b@2.0.0:\n  version "2.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-2.0.0.tgz#${H}"\n\nb@1.0.0:`])
    refuses(text, '"b@1.0.0" is not given "b@2.0.0", which the resolution "**/b" resolves it to', '["d@file:./d"].dependencies.b', withRoot({ resolutions: { '**/b': '2.0.0' } }))
  })
})

describe('refuses what yarn does not write, with the line', () => {
  it('a header other than yarn\'s', () => {
    refuses('', 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
    refuses(BASE.replace(HEADER, '# yarn lockfile v1\n'), 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
    refuses(edit(['# yarn lockfile v1', '# yarn lockfile v2']), 'unsupported version: expected "1", found "2" at line 2')
    refuses(edit(['# yarn lockfile v1\n', '# yarn lockfile v1\n#  yarn lockfile v2 \n']), 'a second lockfile version at line 3')
    refuses(edit(['# yarn lockfile v1\n', '# yarn lockfile v1\n#\n']), 'a comment of "#" alone, which @yarnpkg/parsers does not read at line 3')
    refuses('# This file is generated by running "yarn install" inside your project.\n\n__metadata:\n  version: 8\n', 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
  })

  it('a comment below the header', () => {
    refuses(edit(['\nb@1.0.0:', '\n# b\nb@1.0.0:']), 'a comment, which yarn writes in the header alone at line 18')
    refuses(edit(['  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b', '  # v\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b']), 'expected a string, found "# v" at line 19')
    refuses(edit(['b@1.0.0:', 'b@1.0.0: # b']), 'expected the end of the line, found " # b" at line 18')
  })

  it('a string quoted where yarn writes it bare, or bare where it quotes it', () => {
    refuses(edit(['  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b', '  version 1.0.0\n  resolved "https://registry.yarnpkg.com/b']), 'expected a string, found "1.0.0" at line 19')
    refuses(edit(['b@1.0.0:', '"b@1.0.0":']), '"b@1.0.0" is quoted, where yarn writes it bare at line 18')
    refuses(edit(['  version "1.1.0"', '  "version" "1.1.0"']), '"version" is quoted, where yarn writes it bare at line 11')
    refuses(edit(['  uid ""', '  uid truex']), '"truex" is bare, where yarn quotes it at line 38')
    refuses(edit(['  uid ""', '  uid "a b"c']), 'expected the end of the line, found "c" at line 38')
    refuses(edit(['"@s/c@^2.0.0":', '@s/c@^2.0.0:']), 'expected a string, found "@s/c@^2.0.0:" at line 5')
  })

  it('a value some readers take as null, bare as yarn writes it or not', () => {
    refuses(edit(['  uid ""', '  uid null']), '"null" is bare, and read as null by some readers at line 38')
    refuses(edit(['  uid ""', '  uid nullish']), '"nullish" is bare, and read as null by some readers at line 38')
    refuses(edit(['  uid ""', '  uid "null"']), '"null" is quoted, where yarn writes it bare at line 38')
    const named = edit(['b@1.0.0:', `null@1:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/null/-/null-1.0.0.tgz#${H}"\n\nb@1.0.0:`])
    assert.equal(parse(named).packages['null@1'].name, 'null')
  })

  it('a quoted string not as JSON writes it, or that yarn ends elsewhere', () => {
    refuses(edit(['  uid ""', '  uid "\\u0061 b"']), '"\\"\\\\u0061 b\\"" is not written as JSON writes "a b" at line 38')
    refuses(edit(['  uid ""', '  uid "\\/ b"']), '"\\"\\\\/ b\\"" is not written as JSON writes "/ b" at line 38')
    refuses(edit(['  uid ""', '  uid "\\x"']), '"\\"\\\\x\\"" is not a string as JSON writes it at line 38')
    refuses(edit(['  uid ""', '  uid "a\\\\\\"b"']), '"a\\\\\\"b" is a string yarn reads to another quote at line 38')
    refuses(edit(['  uid ""', '  uid "a']), 'a string with no closing quote at line 38')
  })

  it('indentation other than two spaces a level', () => {
    refuses(edit(['  version "1.1.0"', '   version "1.1.0"']), 'expected 2 spaces of indentation, found 3 at line 11')
    refuses(edit(['  version "1.1.0"', ' version "1.1.0"']), 'expected 2 spaces of indentation, found 1 at line 11')
    refuses(edit(['    b "1.0.0"\n\nb@', '      b "1.0.0"\n\nb@']), 'expected 4 spaces of indentation, found 6 at line 16')
    refuses(edit(['"@s/c@^2.0.0":', '  "@s/c@^2.0.0":']), 'expected an entry, at column 0 at line 5')
    refuses(edit(['  dependencies:\n    "@s/c"', '  dependencies:\n  "@s/c"']), 'expected what "dependencies" holds below it at line 14')
  })

  it('a blank line within an entry, where yarn stops reading the file', () => {
    refuses(edit(['  version "1.1.0"\n', '  version "1.1.0"\n\n']), 'a blank line within an entry at line 12')
    refuses(edit(['  dependencies:\n', '  dependencies:\n\n']), 'expected what "dependencies" holds below it at line 14')
    refuses(edit(['a@^1.0.0, a@^1.1.0:\n', 'a@^1.0.0, a@^1.1.0:\n\n']), 'expected the fields of the entry below it at line 10')
  })

  it('a field written as yarn does not', () => {
    refuses(edit(['  version "1.1.0"', '  version: "1.1.0"']), 'expected the end of the line, found " \\"1.1.0\\"" at line 11')
    refuses(edit(['  version "1.1.0"', '  version  "1.1.0"']), 'expected a string, found " \\"1.1.0\\"" at line 11')
    refuses(edit(['  version "1.1.0"', '  version "1.1.0" ']), 'expected the end of the line, found " " at line 11')
    refuses(edit(['  version "1.1.0"', '  version']), 'expected a space and a value, or ":", after "version" at line 11')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b:\n\nb@']), 'expected a space and a range after "b" at line 16')
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0,a@^1.1.0:']), 'expected ", " and a pattern, or ":", after "a@^1.0.0" at line 10')
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0 a@^1.1.0:']), 'expected ", " and a pattern, or ":", after "a@^1.0.0" at line 10')
    refuses(edit(['b@1.0.0:', 'b@1.0.0 "x"']), 'expected ", " and a pattern, or ":", after "b@1.0.0" at line 18')
  })

  it('a key twice, or empty', () => {
    refuses(edit(['b@1.0.0:', 'b@1.0.0, b@1.0.0:']), '"b@1.0.0" is a key twice at line 18')
    refuses(edit(['b@1.0.0:', 'a@^1.0.0, b@1.0.0:']), '"a@^1.0.0" is a key at line 10 too at line 18')
    refuses(edit(['  version "1.1.0"', '  version "1.1.0"\n  version "1.1.0"']), 'the field "version" twice at line 12')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n    b "1.0.0"\n\nb@']), '"b" is in "dependencies" twice at line 17')
    refuses(edit(['b@1.0.0:', '"":']), 'an empty key, which yarn does not read at line 18')
  })

  it('what yarn reads otherwise, or not at all', () => {
    refuses(`\uFEFF${BASE}`, 'U+FEFF is not allowed at line 1')
    refuses(edit(['  version "1.1.0"', '  version\t"1.1.0"']), 'U+0009 is not allowed at line 11')
    refuses(edit(['  version "1.1.0"\n', '  version "1.1.0"\r']), 'U+000D is not allowed at line 11')
    refuses(`${BASE}\r`, 'U+000D is not allowed at line 44')
    refuses(BASE.replace('\n', '\r\n'), 'a LF line end, after CRLF ones at line 2')
    refuses(edit(['  version "1.1.0"\n', '  version "1.1.0"\r\n']), 'a CRLF line end, after LF ones at line 11')
    for (const [escape, char] of [['\\u0001', 'U+0001'], ['\\t', 'U+0009'], ['\\ud800', 'U+D800']]) {
      refuses(edit(['  uid ""', `  uid "a${escape}"`]), `an escape for ${char}, which is not allowed at line 38`)
    }
    refuses(edit(['  uid ""', '  uid "\u2028"']), 'U+2028 is not allowed at line 38')
    refuses(edit(['  uid ""', '  uid "<<<<<<< ======= >>>>>>>"']), 'yarn reads a file with "<<<<<<<", "=======", ">>>>>>>" in it as a merge conflict')
  })
})

describe('refuses an entry yarn does not write, or installs otherwise', () => {
  it('a field not read here', () => {
    for (const field of ['registry yarn', 'permissions:\n    a b', 'prebuiltVariants:\n    a b', 'peerDependencies:\n    a b', 'x y']) {
      const name = field.split(/[ :]/u)[0]
      refuses(edit(['  version "0.1.0"', `  version "0.1.0"\n  ${field}`]), `unsupported field "${name}"`, '["d@file:./d"]')
    }
  })

  it('a pattern that is not name@range', () => {
    refuses(edit(['b@1.0.0:', 'b:']), '"b" is not a pattern of the form name@range', 'b')
    refuses(edit(['b@1.0.0:', 'B!@1.0.0:']), '"B!" is not a package name', '["B!@1.0.0"]')
    refuses(edit(['b@1.0.0:', '"@s@1.0.0":']), '"@s" is not a package name', '["@s@1.0.0"]')
  })

  it('a version that is not SemVer, or none', () => {
    refuses(edit(['  version "1.1.0"', '  version "1.1"']), '"1.1" is not a version semver reads', '["a@^1.0.0"].version')
    refuses(edit(['  version "1.1.0"\n', '']), 'expected a string, found nothing', '["a@^1.0.0"].version')
    refuses(edit(['  version "1.1.0"', '  version:\n    a "1"']), 'expected a string, found a mapping', '["a@^1.0.0"].version')
  })

  it('a name other than its patterns give it, or two, or the one they give', () => {
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0, a@^1.1.0:\n  name a']), 'the name its patterns give, which yarn does not write', '["a@^1.0.0"].name')
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0, a@^1.1.0:\n  name b']), 'yarn installs this as "b", and leaves "a" out, which its patterns ask for', '["a@^1.0.0"].name')
    refuses(edit(['"my-b@npm:b@1.0.0":', '"my-b@npm:b@1.0.0", b@^1.0.0:']), '"my-b@npm:b@1.0.0" and "b@^1.0.0" give it two names, of which yarn installs it under one alone', '["my-b@npm:b@1.0.0"]')
    refuses(edit(['"f@https://example.com/f.tgz":', '"f@https://example.com/f.tgz", "g@https://example.com/f.tgz":']), '"f@https://example.com/f.tgz" and "g@https://example.com/f.tgz" give it two names, of which yarn installs it under one alone', '["f@https://example.com/f.tgz"]')
  })

  it('patterns asking for two packages of the registry, or an alias of no package', () => {
    refuses(edit(['"my-b@npm:b@1.0.0":', '"my-b@npm:b@1.0.0", "my-b@npm:c@1.0.0":']), '"my-b@npm:b@1.0.0" and "my-b@npm:c@1.0.0" ask for two packages, "b" and "c"', '["my-b@npm:b@1.0.0"]')
    refuses(edit(['"my-b@npm:b@1.0.0":', 'my-b@1.0.0, "my-b@npm:b@1.0.0":']), '"my-b@1.0.0" and "my-b@npm:b@1.0.0" ask for two packages, "my-b" and "b"', '["my-b@1.0.0"]')
    refuses(edit(['"my-b@npm:b@1.0.0":', '"my-b@npm:B!@1.0.0":']), '"B!" is not a package name', '["my-b@npm:B!@1.0.0"]')
  })

  it('a pattern naming a source, resolved from another', () => {
    const strays = (text, key) => refuses(text, `"${key}" resolves to another source than it names`, `["${key}"].resolved`)
    strays(edit(['  uid ""', `  uid ""\n  resolved "https://example.com/l.tgz#${H}"`]), 'l@link:./l')
    strays(edit(['  version "0.1.0"', `  version "0.1.0"\n  resolved "file:d.tgz#${H}"`]), 'd@file:./d')
    strays(edit(['  resolved "git+https://example.com/e.git#', '  resolved "git+https://example.com/x.git#']), 'e@git+https://example.com/e.git#v3')
    strays(edit([`  resolved "https://example.com/f.tgz#${H}"`, `  resolved "https://example.com/g.tgz#${H}"`]), 'f@https://example.com/f.tgz')
    strays(edit(['  version "0.1.0"', `  version "0.1.0"\n  resolved "file:./d#${H}"`]), 'd@file:./d')
    strays(edit(['"l@link:./l":\n  version "0.0.0"\n  uid ""', '"l@file:vendor/l.tgz":\n  version "0.0.0"']), 'l@file:vendor/l.tgz')
    const host = (range, url) => strays(edit([`"e@git+https://example.com/e.git#v3":\n  version "3.0.0"\n  resolved "git+https://example.com/e.git#${C}"`, `${keyed(`e@${range}`)}:\n  version "3.0.0"\n  resolved "${url}"`]), `e@${range}`)
    host('github:u/e#v3', `https://codeload.github.com/u/f/tar.gz/${C}`)
    host('github:u/e#v3', 'https://codeload.github.com/u/e/tar.gz/v3')
    host('u/e#v3', `git+ssh://git@github.com/v/e.git#${C}`)
    host('gitlab:u/e#v3', `https://codeload.github.com/u/e/tar.gz/${C}`)
    host('gist:abc#v3', `https://gist.github.com/xyz.git#${C}`)
  })

  it('patterns of directories yarn writes an entry for each of', () => {
    refuses(edit(['"d@file:./d":', '"d@file:./d", "d@file:./e":']), '"d@file:./d" and "d@file:./e" share an entry, where yarn writes one for each', '["d@file:./d"]')
    refuses(edit(['"l@link:./l":', '"l@link:./l", "l@link:l":']), '"l@link:./l" and "l@link:l" share an entry, where yarn writes one for each', '["l@link:./l"]')
    refuses(edit(['"d@file:./d":', '"d@file:./d", "d@link:./d":']), '"d@file:./d" and "d@link:./d" share an entry, where yarn writes one for each', '["d@file:./d"]')
    refuses(edit(['"e@git', '"d@file:d":\n  version "0.1.0"\n\n"e@git']), 'resolves as "d@file:./d" does, which yarn writes as one entry', '["d@file:d"]')
  })

  it('a tarball of the registry for another package or version, or of no hash', () => {
    refuses(edit([`b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `c/-/c-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`]), '"https://registry.yarnpkg.com/c/-/c-1.0.0.tgz" is not the registry\'s tarball of b@1.0.0', '["b@1.0.0"].resolved')
    refuses(edit(['  version "1.1.0"', '  version "1.2.0"']), '"https://registry.yarnpkg.com/a/-/a-1.1.0.tgz" is not the registry\'s tarball of a@1.2.0', '["a@^1.0.0"].resolved')
    refuses(edit(['/@s/c/-/c-2.1.0.tgz', '/@s/c/-/s-c-2.1.0.tgz']), '"https://registry.yarnpkg.com/@s/c/-/s-c-2.1.0.tgz" is not the registry\'s tarball of @s/c@2.1.0', '["@s/c@^2.0.0"].resolved')
    const none = 'a tarball with no hash, neither a sha1 after "#" nor an integrity, where yarn writes the sha1'
    refuses(edit([`b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, 'b-1.0.0.tgz"\n\n"d']), none, '["b@1.0.0"].resolved')
    refuses(edit([`f.tgz#${H}"`, 'f.tgz"']), none, '["f@https://example.com/f.tgz"].resolved')
  })

  it('two entries of one name and version, of which yarn gives a range of the registry whichever it resolves first', () => {
    const b = `"b@https://example.com/b.tgz":\n  version "1.0.0"\n  resolved "https://example.com/b.tgz#${H}"\n\n"l@link:./l":`
    refuses(edit(['"l@link:./l":', b]), 'is b 1.0.0, as "b@1.0.0" is, and yarn gives "b@1.0.0" whichever it resolves first', '["b@https://example.com/b.tgz"]')
    const f = `f@^4.0.0:\n  version "4.0.0"\n  resolved "https://registry.yarnpkg.com/f/-/f-4.0.0.tgz#${H}"\n\n"f@https://example.com/f.tgz":`
    refuses(edit(['"f@https://example.com/f.tgz":', f]), 'is f 4.0.0, as "f@^4.0.0" is, and yarn gives "f@^4.0.0" whichever it resolves first', '["f@https://example.com/f.tgz"]')
  })

  it('entries of one tarball, of another version or hash', () => {
    const g = (version, hash) => edit(['"l@link:./l":', `"g@https://example.com/f.tgz":\n  version "${version}"\n  resolved "https://example.com/f.tgz#${hash}"\n\n"l@link:./l":`])
    refuses(g('4.0.1', H), 'another version than "f@https://example.com/f.tgz", of the same tarball', '["g@https://example.com/f.tgz"].version')
    refuses(g('4.0.0', C), 'another sha1 than "f@https://example.com/f.tgz", of the same tarball', '["g@https://example.com/f.tgz"].resolved')
    refuses(edit([`  integrity ${H1}\n\n"d`, `  integrity "${H1} ${I}"\n\n"d`], [`  integrity ${H1}\n`, `  integrity "${H1} ${I2}"\n`]), 'another sha512 integrity than "b@1.0.0", of the same tarball', '["my-b@npm:b@1.0.0"].integrity')
    const e = edit(['"f@https://example.com/f.tgz":', `"e2@git+https://example.com/e.git#v3":\n  version "3.0.1"\n  resolved "git+https://example.com/e.git#${C}"\n\n"f@https://example.com/f.tgz":`])
    refuses(e, 'another version than "e@git+https://example.com/e.git#v3", of the same commit', '["e2@git+https://example.com/e.git#v3"].version')
  })

  it('two entries of one name and resolved, which yarn writes as one, but not as it spells a path', () => {
    const text = edit(['b@1.0.0:', `b@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n\nb@1.0.0:`])
    refuses(text, 'resolves as "b@^1.0.0" does, which yarn writes as one entry', '["b@1.0.0"]')
    const tarball = `"f@https://example.com/f.tgz":\n  version "4.0.0"\n  resolved "https://example.com/f.tgz#${H}"`
    const local = (path) => `"l@file:${path}":\n  version "0.0.0"\n  resolved "file:${path}#${H}"`
    assert.ok(read([tarball, `${local('./v/l.tgz')}\n\n${local('v/l.tgz')}`])['l@file:v/l.tgz'])
  })

  it('a uid that is the version, which yarn leaves out', () => {
    refuses(edit(['  uid ""', '  uid "0.0.0"']), 'the version, which yarn does not write as a uid', '["l@link:./l"].uid')
  })

  it('a pattern asking for the registry given another source, which only the manifests may say a resolution does', () => {
    const only = 'which only a resolution may, as the manifests would say'
    refuses(edit(['"f@https://example.com/f.tgz":', 'f@4.0.0, "f@https://example.com/f.tgz":']), `"f@4.0.0" asks for the registry, and is given what "f@https://example.com/f.tgz" names, ${only}`, '["f@4.0.0"]')
    refuses(edit(['"d@file:./d":', 'd@^0.1.0, "d@file:./d":']), `"d@^0.1.0" asks for the registry, and is given what "d@file:./d" names, ${only}`, '["d@^0.1.0"]')
    refuses(edit(['"e@git+https://example.com/e.git#v3":', 'e@3.0.0:']), '"e@3.0.0" asks for the registry, and resolves to a git repository', '["e@3.0.0"]')
    refuses(edit(['"d@file:./d":', 'd@0.1.0:']), '"d@0.1.0" asks for the registry, and resolves to nothing, as for a directory', '["d@0.1.0"]')
    refuses(edit([`"https://example.com/f.tgz#${H}"`, `"file:vendor/f.tgz#${H}"`], ['"f@https://example.com/f.tgz":', 'f@4.0.0:']), '"f@4.0.0" asks for the registry, and resolves to a file: tarball', '["f@4.0.0"]')
  })

  it('a dependency whose pattern is not there, or listed twice', () => {
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "^1.0.0"\n\nb@']), '"b@^1.0.0" is not a pattern of the lockfile, nor a workspace\'s, as only the manifests may say', '["a@^1.0.0"].dependencies.b')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n  optionalDependencies:\n    b "1.0.0"\n\nb@']), 'listed under dependencies too', '["a@^1.0.0"].optionalDependencies.b')
    refuses(edit(['    b "1.0.0"\n\nb@', '    B! "1.0.0"\n\nb@']), '"B!" is not a package name', '["a@^1.0.0"].dependencies["B!"]')
  })

  it('a resolution not as yarn writes it', () => {
    const at = (key) => `["${key}"].resolved`
    refuses(edit([`#${C}"`, '"']), 'expected a full commit hash after the "#" of "git+https://example.com/e.git"', at('e@git+https://example.com/e.git#v3'))
    refuses(edit([`#${C}"`, '#v3"']), 'expected a full commit hash after the "#" of "git+https://example.com/e.git"', at('e@git+https://example.com/e.git#v3'))
    refuses(edit(['"git+https://example.com/e.git#', '"git+https://exa mple.com/e.git#']), '"git+https://exa mple.com/e.git" is not a repository URL', at('e@git+https://example.com/e.git#v3'))
    refuses(edit([`f.tgz#${H}"`, `f.tgz#${H}#x"`]), 'more than one "#", of which yarn reads the first alone', at('f@https://example.com/f.tgz'))
    refuses(edit([`f.tgz#${H}"`, 'f.tgz#abc"']), '"abc" is not the hex sha1 of a tarball', at('f@https://example.com/f.tgz'))
    refuses(edit([`f.tgz#${H}"`, 'f.tgz#"']), '"" is not the hex sha1 of a tarball', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"ftp://example.com/f.tgz"']), '"ftp://example.com/f.tgz" is not an http(s) URL, a file: path or a git URL', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"file:/vendor/f.tgz"']), '"/vendor/f.tgz" is not a relative path in normal form', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"file:vendor/../f.tgz"']), '"vendor/../f.tgz" is not a relative path in normal form', at('f@https://example.com/f.tgz'))
    refuses(edit(['  resolved "https://example.com/f.tgz', '  resolved "https://example.com:x/f.tgz']), '"https://example.com:x/f.tgz" is not an http(s) URL, a file: path or a git URL', at('f@https://example.com/f.tgz'))
    refuses(edit(['  resolved "https://example.com/f.tgz', '  resolved "https://example.com/f .tgz']), '"https://example.com/f .tgz" is not an http(s) URL, a file: path or a git URL', at('f@https://example.com/f.tgz'))
  })

  it('an integrity yarn does not check, or that names another sha1', () => {
    refuses(edit(['  uid ""', `  uid ""\n  integrity ${I}`]), 'an integrity, with nothing resolved', '["l@link:./l"].integrity')
    refuses(edit([`#${C}"`, `#${C}"\n  integrity ${I}`]), 'an integrity, which yarn does not check for a git repository', '["e@git+https://example.com/e.git#v3"].integrity')
    refuses(edit([`b-1.0.0.tgz#${H}"`, `b-1.0.0.tgz#${C}"`]), `"${H1}" is not the sha1 after the "#" of resolved`, '["b@1.0.0"].integrity')
    refuses(edit([`  integrity ${I}\n\na@`, '  integrity sha512-x\n\na@']), '"sha512-x" is not a sha1, sha256, sha384 or sha512 integrity', '["@s/c@^2.0.0"].integrity')
    refuses(edit([`  integrity ${I}\n\na@`, `  integrity "${I}  ${I}"\n\na@`]), 'expected a non-empty string', '["@s/c@^2.0.0"].integrity')
    refuses(edit([`  integrity ${I}\n\na@`, `  integrity "${I} ${I}"\n\na@`]), 'two sha512 integrities', '["@s/c@^2.0.0"].integrity')
  })

  it('anything but a string', () => {
    assert.throws(() => parseYarn1Lockfile(Buffer.from(BASE)), TypeError)
  })
})

describe('a resolution to a source, where it applies to every request', () => {
  const URL = 'https://example.com/b.tgz'
  // b@1.0.0, which a and d ask for, and the resolution's own pattern, both
  // given the tarball the resolution names.
  const RESOLVED = edit(['b@1.0.0:', `b@1.0.0, "b@${URL}":`], [`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"${URL}#${H}"\n  integrity ${H1}\n\n"d`])
  const resolving = (resolutions, fields = {}) => ({ ...MANIFESTS, '.': { ...MANIFESTS['.'], resolutions, ...fields } })
  const resolved = (resolutions, text = RESOLVED) => parse(text, resolving(resolutions)).packages
  const applies = 'which yarn does not apply to it here'

  it('reads one that applies everywhere, or along every path it is asked for by', () => {
    for (const resolutions of [{ b: URL }, { '**/b': URL }, { '**/a/b': URL, 'd/b': URL }, { '**/?/b': URL }, { '**/*/b': URL }]) {
      const packages = resolved(resolutions)
      assert.equal(packages['b@1.0.0'], packages[`b@${URL}`], JSON.stringify(resolutions))
      assert.deepEqual(packages['b@1.0.0'].resolution, { type: 'tarball', tarball: URL, sha1: H, integrity: H1 })
    }
  })

  it('reads one to a repository of a git host, whose tarball has no hash', () => {
    const tarball = `https://codeload.github.com/u/b/tar.gz/${C}`
    const text = edit(['b@1.0.0:', 'b@1.0.0, "b@github:u/b#v1":'], [`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"${tarball}"\n\n"d`])
    assert.equal(parse(text, resolving({ b: 'github:u/b#v1' })).packages['b@1.0.0'].resolution.tarball, tarball)
  })

  it('refuses one that does not apply along a path it is asked for by', () => {
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "d/b" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ 'd/b': URL }))
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "**/a/b" resolves to, ${applies}`, '["d@file:./d"].dependencies.b', resolving({ '**/a/b': URL }))
    // a is asked for by the root, as a/b, and by the workspace through
    // yarn's aggregator, as workspace-aggregator-…/w/a/b.
    for (const path of ['a/b', '*/b']) {
      refuses(RESOLVED, `"b@1.0.0" is given what the resolution "${path}" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ [path]: URL, 'd/b': URL }))
    }
    // And as w/a/b, as the root asks for the workspace too.
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "*/w/a/b" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ '*/w/a/b': URL, 'a/b': URL, 'd/b': URL }))
    assert.equal(resolved({ '**/w/a/b': URL, 'a/b': URL, 'd/b': URL })['b@1.0.0'].resolution.tarball, URL)
  })

  it('refuses one that another resolution comes before, as the first to match applies', () => {
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "**/b" resolves to, ${applies}`, '["d@file:./d"].dependencies.b', resolving({ 'd/b': '1.0.0', '**/b': URL }))
    assert.equal(resolved({ '**/b': URL, 'd/b': '1.0.0' })['b@1.0.0'].resolution.tarball, URL)
  })

  it('refuses the root\'s own dependency given it, which no resolution applies to', () => {
    const manifests = resolving({ '**/b': URL }, { dependencies: { ...MANIFESTS['.'].dependencies, b: '1.0.0' } })
    refuses(RESOLVED, '"b@1.0.0" is given what the resolution "**/b" resolves to, which yarn applies to no dependency of the root\'s own', 'manifests["."].dependencies.b', manifests)
  })

  it('refuses a dependency on what it resolves to, or another entry of that tarball', () => {
    refuses(edit(['b@1.0.0:', `b@1.0.0, "b@${URL}":`], [`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"${URL}#${H}"\n  integrity ${H1}\n\n"d`], ['  version "0.1.0"\n  dependencies:\n    b "1.0.0"', `  version "0.1.0"\n  dependencies:\n    b "${URL}"`]), `"b@${URL}" asks for what the resolution "**/b" resolves to, as a dependency of its own`, '["d@file:./d"].dependencies.b', resolving({ '**/b': URL }))
    const shared = RESOLVED.replace(`"my-b@npm:b@1.0.0":\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"`, `"my-b@npm:b@1.0.0":\n  version "1.0.0"\n  resolved "${URL}#${H}"`)
    refuses(shared, 'asks for what the resolution "**/b" resolves to, as a dependency of its own', '["my-b@npm:b@1.0.0"]', resolving({ '**/b': URL }))
  })

  it('refuses a source no resolution names, and a glob not read here', () => {
    const text = RESOLVED
    refuses(text, `"b@1.0.0" asks for the registry, and is given what "b@${URL}" names, which no resolution does`, '["b@1.0.0"]', resolving(undefined, { dependencies: { ...MANIFESTS['.'].dependencies, b: URL } }))
    refuses(text, '"**/{a,d}/b" is a glob not read here', 'manifests["."].resolutions["**/{a,d}/b"]', resolving({ '**/{a,d}/b': URL }))
    refuses(text, '"b@https://example.com/other.tgz" is not a pattern of the lockfile, where yarn records every resolution\'s', 'manifests["."].resolutions["**/b"]', resolving({ '**/b': 'https://example.com/other.tgz' }))
  })
})

describe('options', () => {
  it('semver, which checking versions, the default, needs; and nothing else', () => {
    assert.throws(() => parseYarn1Lockfile(BASE), { name: 'TypeError', message: 'checkVersions needs semver: pass it as semver, or set checkVersions to false' })
    assert.throws(() => parseYarn1Lockfile(BASE, { validateVersions: false }), { name: 'TypeError', message: 'unknown option "validateVersions", of manifests, checkVersions, semver' })
    assert.throws(() => parseYarn1Lockfile(BASE, MANIFESTS), { name: 'TypeError', message: 'unknown option ".", of manifests, checkVersions, semver' })
    assert.throws(() => parseYarn1Lockfile(BASE, { semver: { valid: semver.valid } }), { name: 'TypeError', message: 'semver: expected the semver package, with clean, satisfies, valid, validRange' })
    assert.throws(() => parseYarn1Lockfile(BASE, { checkVersions: 'no' }), { name: 'TypeError', message: 'checkVersions: expected a boolean' })
    assert.throws(() => parseYarn1Lockfile(BASE, null), { name: 'TypeError', message: 'expected an options object' })
  })

  it('without semver, the same packages and importers', () => {
    assert.deepEqual(plain(parseYarn1Lockfile(BASE, { manifests: MANIFESTS, checkVersions: false })), plain(parse(BASE, MANIFESTS)))
  })
})

describe('versions, crudely without semver, and as semver reads them with it', () => {
  const crude = { checkVersions: false }
  const version = (to) => edit(['  version "4.0.0"', `  version ${to}`])
  const at = '["f@https://example.com/f.tgz"].version'

  it('without semver, of the characters semver reads, at most 256 of them', () => {
    for (const to of ['"4.0"', 'v4.0.0', '"4.0.0-01"', '" 4.0.0 "', '"=4.0.0"', '"4.0.0+build"']) assert.ok(parseYarn1Lockfile(version(to), crude).packages['f@https://example.com/f.tgz'], to)
    for (const to of ['"4.0.0_1"', '"4.0.0~1"', '"^4.0.0"', '"4.0.0é"']) refuses(version(to), `${to} is not a version`, at, undefined, crude)
    refuses(version(`"${'4'.repeat(257)}"`), `"${'4'.repeat(200)}…" is not a version`, at, undefined, crude)
  })

  it('with semver, what semver.valid reads, as written', () => {
    for (const to of ['v4.0.0', '"4.0.0+build"', '" 4.0.0"']) assert.equal(parse(version(to)).packages['f@https://example.com/f.tgz'].version, JSON.parse(to.startsWith('"') ? to : `"${to}"`), to)
    for (const to of ['"4.0"', '"4.0.0-01"', '"04.0.0"', '"=4.0.0"']) refuses(version(to), `${to} is not a version semver reads`, at)
  })

  it('a workspace\'s, as yarn cleans it first, loosely', () => {
    const ws = (to) => ({ ...MANIFESTS, w: { ...MANIFESTS.w, version: to } })
    assert.equal(parse(BASE, ws('v1.0.0')).importers['.'].dependencies.w, 'link:w')
    refuses(BASE, '"1.0" is not a version semver reads', 'manifests.w.version', ws('1.0'))
    assert.equal(parse(BASE, ws('=1.0.0')).importers['.'].dependencies.w, 'link:w')
    refuses(BASE, '"1.0_0" is not a version', 'manifests.w.version', ws('1.0_0'), crude)
  })
})

describe('with semver, each request resolved as yarn resolves it', () => {
  // b@1.0.0, which a and d ask for, given 2.0.0 as `b@2.0.0`.
  const b2 = edit(['b@1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#', 'b@1.0.0, b@2.0.0:\n  version "2.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-2.0.0.tgz#'])
  const resolving = (resolutions) => ({ ...MANIFESTS, '.': { ...MANIFESTS['.'], resolutions } })

  it('a version that does not satisfy a range, where a resolution gives it to every request', () => {
    assert.equal(parse(b2, resolving({ '**/b': '2.0.0' })).packages['b@1.0.0'].version, '2.0.0')
  })

  it('refuses one some request is given with no resolution', () => {
    refuses(b2, '2.0.0 does not satisfy "1.0.0", which only a resolution may excuse, as the manifests would say', '["b@1.0.0"]')
    refuses(b2, '2.0.0 does not satisfy "1.0.0", and no resolution gives it', '["b@1.0.0"]', resolving({ 'd/b': '2.0.0' }))
    refuses(edit(['"my-b@npm:b@1.0.0":', '"my-b@npm:b@^2.0.0":']), '1.0.0 does not satisfy "^2.0.0", which only a resolution may excuse, as the manifests would say', '["my-b@npm:b@^2.0.0"]')
    assert.ok(parseYarn1Lockfile(b2, { checkVersions: false }).packages['b@1.0.0'])
  })

  it('a workspace linked where its version satisfies the range, and otherwise refused', () => {
    const asking = (range) => ({ ...MANIFESTS, '.': { ...MANIFESTS['.'], dependencies: { ...MANIFESTS['.'].dependencies, w: range } } })
    assert.equal(parse(BASE, asking('^1.0.0')).importers['.'].dependencies.w, 'link:w')
    refuses(BASE, '"w@^2.0.0" is not a pattern of the lockfile, nor satisfied by the workspace "w", 1.0.0', 'manifests["."].dependencies.w', asking('^2.0.0'))
    const w = edit(['"l@link:./l":', `w@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/w/-/w-1.0.0.tgz#${H}"\n\n"l@link:./l":`])
    refuses(w, '"w@^1.0.0" is satisfied by the workspace "w", which yarn links instead', 'manifests["."].dependencies.w', asking('^1.0.0'))
    // Without semver, a range is known to be satisfied by its very version alone.
    assert.equal(parseYarn1Lockfile(BASE, { manifests: asking('^2.0.0'), checkVersions: false }).importers['.'].dependencies.w, 'link:w')
    assert.equal(parseYarn1Lockfile(w, { manifests: asking('^1.0.0'), checkVersions: false }).importers['.'].dependencies.w, 'w@^1.0.0')
  })

  it('a tag aside, and an alias, beside another entry of the name and version, by semver or without it', () => {
    const f = (range) => edit(['"f@https://example.com/f.tgz":', `f@${range}:\n  version "4.0.0"\n  resolved "https://registry.yarnpkg.com/f/-/f-4.0.0.tgz#${H}"\n\n"f@https://example.com/f.tgz":`])
    for (const options of [{ semver }, { checkVersions: false }]) {
      assert.ok(parseYarn1Lockfile(f('latest'), options).packages['f@latest'])
      refuses(f('4.x'), 'is f 4.0.0, as "f@4.x" is, and yarn gives "f@4.x" whichever it resolves first', '["f@https://example.com/f.tgz"]', undefined, options)
    }
  })
})
