import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { LockfileError, parseYarnLockfile } from '../../yarn.js'

// One small yarn.lock with a package of every kind — from the registry,
// with patterns merged, a sha1 integrity and an npm alias; a directory, a
// git repository, a tarball by URL and a link — in the form yarn writes,
// and the manifests of a project and its workspace; then one edit at a
// time, each of which is refused with a message that says where and why.

const I = 'sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg=='
const H = '0123456789abcdef0123456789abcdef01234567'
const H1 = `sha1-${Buffer.from(H, 'hex').toString('base64')}`
const C = 'fedcba9876543210fedcba9876543210fedcba98'

const HEADER = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n'

const BASE = `${HEADER}

"@s/c@^2.0.0":
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/@s/c/-/c-2.1.0.tgz#${H}"
  integrity ${I}

a@^1.0.0, a@^1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/a/-/a-1.1.0.tgz#${H}"
  integrity ${I}
  dependencies:
    "@s/c" "^2.0.0"
    b "1.0.0"

b@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"
  integrity ${H1}

"d@file:./d":
  version "0.1.0"
  dependencies:
    b "1.0.0"

"e@git+https://example.com/e.git#v3":
  version "3.0.0"
  resolved "git+https://example.com/e.git#${C}"

"f@https://example.com/f.tgz":
  version "4.0.0"
  resolved "https://example.com/f.tgz#${H}"

"l@link:./l":
  version "0.0.0"
  uid ""

"my-b@npm:b@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"
  integrity ${H1}
`

const MANIFESTS = {
  '.': {
    name: 'root',
    private: true,
    workspaces: ['w'],
    dependencies: { a: '^1.0.0', d: 'file:./d', e: 'git+https://example.com/e.git#v3', f: 'https://example.com/f.tgz', 'my-b': 'npm:b@1.0.0', w: '1.0.0' },
    devDependencies: { l: 'link:./l' },
  },
  w: { name: 'w', version: '1.0.0', dependencies: { a: '^1.1.0' } },
}

// BASE with each `[from, to]` replaced, once; `from` has to be there.
function edit(...edits) {
  let text = BASE
  for (const [from, to] of edits) {
    assert.ok(text.includes(from), `BASE has no ${JSON.stringify(from)}`)
    text = text.replace(from, to)
  }
  return text
}

// `message` is the refusal's detail, which the message leads with `where`.
const refuses = (text, message, where, manifests) => assert.throws(() => parseYarnLockfile(text, manifests), (error) => {
  assert.ok(error instanceof LockfileError, error.stack)
  assert.equal(error.message, where === undefined ? message : `${where}: ${message}`)
  assert.equal(error.where, where)
  return true
})

const plain = (value) => structuredClone(value)
const read = (...edits) => parseYarnLockfile(edit(...edits)).packages

describe('the base lockfile', () => {
  const lock = parseYarnLockfile(BASE, MANIFESTS)

  it('reads, each pattern to its package', () => {
    assert.deepEqual(Object.keys(lock.packages), [
      '@s/c@^2.0.0', 'a@^1.0.0', 'a@^1.1.0', 'b@1.0.0', 'd@file:./d', 'e@git+https://example.com/e.git#v3', 'f@https://example.com/f.tgz', 'l@link:./l', 'my-b@npm:b@1.0.0',
    ])
    assert.equal(lock.packages['a@^1.0.0'], lock.packages['a@^1.1.0'])
    assert.deepEqual(plain(lock.packages['a@^1.0.0']), {
      patterns: ['a@^1.0.0', 'a@^1.1.0'],
      name: 'a',
      version: '1.1.0',
      uid: undefined,
      resolution: { type: 'tarball', tarball: 'https://registry.yarnpkg.com/a/-/a-1.1.0.tgz', sha1: H, integrity: I },
      dependencies: { '@s/c': '@s/c@^2.0.0', b: 'b@1.0.0' },
      optionalDependencies: {},
    })
  })

  it('every kind of resolution', () => {
    const { packages } = lock
    assert.deepEqual(packages['b@1.0.0'].resolution.integrity, H1)
    assert.equal(packages['d@file:./d'].resolution, undefined)
    assert.deepEqual(packages['e@git+https://example.com/e.git#v3'].resolution, { type: 'git', repo: 'git+https://example.com/e.git', commit: C })
    assert.deepEqual(packages['f@https://example.com/f.tgz'].resolution, { type: 'tarball', tarball: 'https://example.com/f.tgz', sha1: H, integrity: undefined })
    assert.deepEqual([packages['l@link:./l'].version, packages['l@link:./l'].uid, packages['l@link:./l'].resolution], ['0.0.0', '', undefined])
    assert.equal(packages['my-b@npm:b@1.0.0'].name, 'my-b')
  })

  it('the importers, a workspace linked', () => {
    assert.deepEqual(plain(lock.importers), {
      '.': {
        dependencies: {
          a: 'a@^1.0.0', d: 'd@file:./d', e: 'e@git+https://example.com/e.git#v3', f: 'f@https://example.com/f.tgz', 'my-b': 'my-b@npm:b@1.0.0', w: 'link:w',
        },
        devDependencies: { l: 'l@link:./l' },
        optionalDependencies: {},
      },
      w: { dependencies: { a: 'a@^1.1.0' }, devDependencies: {}, optionalDependencies: {} },
    })
  })

  it('records have no prototype', () => {
    for (const record of [lock.packages, lock.importers, lock.importers['.'].dependencies, lock.packages['b@1.0.0'].dependencies]) {
      assert.equal(Object.getPrototypeOf(record), null)
    }
  })

  it('without the manifests, no importers', () => {
    const alone = parseYarnLockfile(BASE)
    assert.equal(alone.importers, undefined)
    assert.deepEqual(plain(alone.packages), plain(lock.packages))
  })

  it('with CRLF line ends too, and without the last', () => {
    assert.deepEqual(plain(parseYarnLockfile(BASE.replaceAll('\n', '\r\n'), MANIFESTS)), plain(lock))
    assert.deepEqual(plain(parseYarnLockfile(BASE.trimEnd(), MANIFESTS)), plain(lock))
  })

  it('what yarn writes with nothing installed', () => {
    assert.deepEqual(plain(parseYarnLockfile(`${HEADER}\n\n`, { '.': { name: 'e' } })), { packages: {}, importers: { '.': { dependencies: {}, devDependencies: {}, optionalDependencies: {} } } })
  })
})

describe('what else yarn writes is read', () => {
  it('the versions of yarn and Node below the header, and another tool\'s line', () => {
    const header = `${HEADER}# yarn v1.22.22\n# node v24.15.0\n# bun ./bun.lockb --hash: 5BBAC8D5E5D9B1E9-1\n`
    assert.deepEqual(plain(parseYarnLockfile(BASE.replace(HEADER, header)).packages), plain(parseYarnLockfile(BASE).packages))
  })

  it('an empty range, and a dependency on it', () => {
    const packages = read(['b@1.0.0:', 'b@, b@1.0.0:'], ['    b "1.0.0"', '    b ""'])
    assert.equal(packages['b@'], packages['b@1.0.0'])
    assert.equal(packages['a@^1.0.0'].dependencies.b, 'b@')
  })

  it('strings quoted for their spaces or escapes, and one bare with a quote in it', () => {
    const packages = read(['  uid ""', '  uid "a \\"b\\" \\\\ \\u0001"'], ['"@s/c@^2.0.0":', '"@s/c@^2.0.0", "@s/c@>= 2.0.0 <3":'])
    assert.equal(packages['l@link:./l'].uid, 'a "b" \\ \u0001')
    assert.equal(packages['@s/c@>= 2.0.0 <3'].version, '2.1.0')
    assert.equal(read(['  uid ""', "  uid it's"])['l@link:./l'].uid, "it's")
  })

  it('an optional dependency, and more than one integrity', () => {
    const packages = read(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n  optionalDependencies:\n    f "https://example.com/f.tgz"\n\nb@'], [`  integrity ${H1}\n\n"d`, `  integrity "${H1} ${I}"\n\n"d`])
    assert.deepEqual(plain(packages['a@^1.0.0'].optionalDependencies), { f: 'f@https://example.com/f.tgz' })
    assert.equal(packages['b@1.0.0'].resolution.integrity, `${H1} ${I}`)
  })

  it('a tarball from a git host, with no sha1, and a local one', () => {
    const packages = read(['"https://example.com/f.tgz#' + H + '"', '"https://codeload.github.com/u/f/tar.gz/' + C + '"'], [
      '"l@link:./l":\n  version "0.0.0"\n  uid ""', `"l@file:vendor/l.tgz":\n  version "0.0.0"\n  resolved "file:vendor/l.tgz#${H}"`,
    ])
    assert.deepEqual(packages['f@https://example.com/f.tgz'].resolution, { type: 'tarball', tarball: `https://codeload.github.com/u/f/tar.gz/${C}`, sha1: undefined, integrity: undefined })
    assert.equal(packages['l@file:vendor/l.tgz'].resolution.tarball, 'file:vendor/l.tgz')
  })

  it('a name the patterns give already', () => {
    assert.equal(read(['a@^1.0.0, a@^1.1.0:\n', 'a@^1.0.0, a@^1.1.0:\n  name a\n'])['a@^1.0.0'].name, 'a')
  })
})

describe('with the manifests', () => {
  const lock = (text, manifests) => parseYarnLockfile(text, manifests)
  const root = MANIFESTS['.']
  const withRoot = (fields) => ({ ...MANIFESTS, '.': { ...root, ...fields } })

  it('a workspace\'s file: and link: are read from the lockfile\'s directory', () => {
    const manifests = { ...MANIFESTS, w: { name: 'w', dependencies: { a: '^1.1.0', d: 'file:../d/', l: 'link:./../l' } } }
    const text = edit(['"d@file:./d":', '"d@file:./d", "d@file:d":'])
    assert.deepEqual(plain(lock(text, manifests).importers.w.dependencies), { a: 'a@^1.1.0', d: 'd@file:d', l: 'l@link:./l' })
  })

  it('a "//" in a list is a comment, as yarn drops it', () => {
    assert.equal('//' in lock(BASE, withRoot({ devDependencies: { '//': 'a note', l: 'link:./l' } })).importers['.'].devDependencies, false)
  })

  it('a resolution\'s own pattern, beside those it was applied to', () => {
    const text = edit(['a@^1.0.0, a@^1.1.0:', 'a@1.1.0, a@^1.0.0, a@^1.1.0:'])
    assert.equal(lock(text, withRoot({ resolutions: { '**/a': '1.1.0' } })).packages['a@1.1.0'].version, '1.1.0')
    refuses(text, 'nothing asks for it: no manifest, no package and no resolution', '["a@1.1.0"]', MANIFESTS)
    refuses(text, 'nothing asks for it: no manifest, no package and no resolution', '["a@1.1.0"]', withRoot({ resolutions: { 'x/**/a/': '1.1.0' } }))
    assert.equal(lock(text, withRoot({ resolutions: { 'x/**/a': '1.1.0', '@s/c/a': '2.0.0' } })).packages['a@1.1.0'].version, '1.1.0')
  })

  it('refuses a pattern nothing asks for', () => {
    const others = Object.fromEntries(Object.entries(root.dependencies).filter(([name]) => name !== 'w'))
    refuses(BASE, 'nothing asks for it: no manifest, no package and no resolution', '["a@^1.1.0"]', { '.': { ...root, dependencies: others } })
    refuses(edit(['"@s/c@^2.0.0":', '"@s/c@^1.0.0", "@s/c@^2.0.0":']), 'nothing asks for it: no manifest, no package and no resolution', '["@s/c@^1.0.0"]', MANIFESTS)
  })

  it('refuses a dependency the lockfile has no pattern for', () => {
    refuses(BASE, '"a@^1.2.0" is not a pattern of the lockfile', 'manifests.w.dependencies.a', { ...MANIFESTS, w: { name: 'w', dependencies: { a: '^1.2.0' } } })
    refuses(BASE, '"x@1.0.0" is not a pattern of the lockfile', 'manifests["."].dependencies.x', withRoot({ dependencies: { x: '1.0.0' } }))
  })

  it('refuses an absolute path', () => {
    refuses(BASE, '"file:/d" is an absolute path', 'manifests["."].dependencies.d', withRoot({ dependencies: { ...root.dependencies, d: 'file:/d' } }))
    refuses(BASE, '"/d" is an absolute path', 'manifests["."].dependencies.d', withRoot({ dependencies: { ...root.dependencies, d: '/d' } }))
  })

  it('refuses manifests that are not a project and its workspaces', () => {
    refuses(BASE, 'expected the manifest beside the lockfile, "."', 'manifests', { w: MANIFESTS.w })
    refuses(BASE, 'expected workspaces, as there are manifests of workspaces', 'manifests["."].workspaces', withRoot({ workspaces: undefined }))
    refuses(BASE, 'the name of the workspace "w" too', 'manifests.v.name', { ...MANIFESTS, v: MANIFESTS.w })
    refuses(BASE, 'expected a string, found nothing', 'manifests.w.name', { ...MANIFESTS, w: { dependencies: { a: '^1.1.0' } } })
    refuses(BASE, 'expected a mapping, found the string "{}"', 'manifests', '{}')
    refuses(BASE, 'expected a string, found the number 1', 'manifests["."].dependencies.w', withRoot({ dependencies: { ...root.dependencies, w: 1 } }))
    refuses(BASE, '"a/./b" is not a relative path in normal form', 'manifests["a/./b"]', { ...MANIFESTS, 'a/./b': {} })
  })
})

describe('refuses what yarn does not write, with the line', () => {
  it('a header other than yarn\'s', () => {
    refuses('', 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
    refuses(BASE.replace(HEADER, '# yarn lockfile v1\n'), 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
    refuses(edit(['# yarn lockfile v1', '# yarn lockfile v2']), 'unsupported version: expected "1", found "2" at line 2')
    refuses(edit(['# yarn lockfile v1\n', '# yarn lockfile v1\n#  yarn lockfile v2 \n']), 'a second lockfile version at line 3')
    refuses(edit(['# yarn lockfile v1\n', '# yarn lockfile v1\n#\n']), 'a comment of "#" alone, which @yarnpkg/parsers does not read at line 3')
    refuses('# This file is generated by running "yarn install" inside your project.\n\n__metadata:\n  version: 8\n', 'expected yarn\'s header, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." at line 1')
  })

  it('a comment below the header', () => {
    refuses(edit(['\nb@1.0.0:', '\n# b\nb@1.0.0:']), 'a comment, which yarn writes in the header alone at line 18')
    refuses(edit(['  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b', '  # v\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b']), 'expected a string, found "# v" at line 19')
    refuses(edit(['b@1.0.0:', 'b@1.0.0: # b']), 'expected the end of the line, found " # b" at line 18')
  })

  it('a string quoted where yarn writes it bare, or bare where it quotes it', () => {
    refuses(edit(['  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b', '  version 1.0.0\n  resolved "https://registry.yarnpkg.com/b']), 'expected a string, found "1.0.0" at line 19')
    refuses(edit(['b@1.0.0:', '"b@1.0.0":']), '"b@1.0.0" is quoted, where yarn writes it bare at line 18')
    refuses(edit(['  version "1.1.0"', '  "version" "1.1.0"']), '"version" is quoted, where yarn writes it bare at line 11')
    refuses(edit(['  uid ""', '  uid truex']), '"truex" is bare, where yarn quotes it at line 38')
    refuses(edit(['  uid ""', '  uid "a b"c']), 'expected the end of the line, found "c" at line 38')
    refuses(edit(['"@s/c@^2.0.0":', '@s/c@^2.0.0:']), 'expected a string, found "@s/c@^2.0.0:" at line 5')
  })

  it('a value some readers take as null, bare as yarn writes it or not', () => {
    refuses(edit(['  uid ""', '  uid null']), '"null" is bare, and read as null by some readers at line 38')
    refuses(edit(['  uid ""', '  uid nullish']), '"nullish" is bare, and read as null by some readers at line 38')
    refuses(edit(['  uid ""', '  uid "null"']), '"null" is quoted, where yarn writes it bare at line 38')
    const named = edit(['b@1.0.0:', 'null@1:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/null/-/null-1.0.0.tgz"\n\nb@1.0.0:'])
    assert.equal(parseYarnLockfile(named).packages['null@1'].name, 'null')
  })

  it('a quoted string not as JSON writes it, or that yarn ends elsewhere', () => {
    refuses(edit(['  uid ""', '  uid "\\u0061 b"']), '"\\"\\\\u0061 b\\"" is not written as JSON writes "a b" at line 38')
    refuses(edit(['  uid ""', '  uid "\\/ b"']), '"\\"\\\\/ b\\"" is not written as JSON writes "/ b" at line 38')
    refuses(edit(['  uid ""', '  uid "\\x"']), '"\\"\\\\x\\"" is not a string as JSON writes it at line 38')
    refuses(edit(['  uid ""', '  uid "a\\\\\\"b"']), '"a\\\\\\"b" is a string yarn reads to another quote at line 38')
    refuses(edit(['  uid ""', '  uid "a']), 'a string with no closing quote at line 38')
  })

  it('indentation other than two spaces a level', () => {
    refuses(edit(['  version "1.1.0"', '   version "1.1.0"']), 'expected 2 spaces of indentation, found 3 at line 11')
    refuses(edit(['  version "1.1.0"', ' version "1.1.0"']), 'expected 2 spaces of indentation, found 1 at line 11')
    refuses(edit(['    b "1.0.0"\n\nb@', '      b "1.0.0"\n\nb@']), 'expected 4 spaces of indentation, found 6 at line 16')
    refuses(edit(['"@s/c@^2.0.0":', '  "@s/c@^2.0.0":']), 'expected an entry, at column 0 at line 5')
    refuses(edit(['  dependencies:\n    "@s/c"', '  dependencies:\n  "@s/c"']), 'expected what "dependencies" holds below it at line 14')
  })

  it('a blank line within an entry, where yarn stops reading the file', () => {
    refuses(edit(['  version "1.1.0"\n', '  version "1.1.0"\n\n']), 'a blank line within an entry at line 12')
    refuses(edit(['  dependencies:\n', '  dependencies:\n\n']), 'expected what "dependencies" holds below it at line 14')
    refuses(edit(['a@^1.0.0, a@^1.1.0:\n', 'a@^1.0.0, a@^1.1.0:\n\n']), 'expected the fields of the entry below it at line 10')
  })

  it('a field written as yarn does not', () => {
    refuses(edit(['  version "1.1.0"', '  version: "1.1.0"']), 'expected the end of the line, found " \\"1.1.0\\"" at line 11')
    refuses(edit(['  version "1.1.0"', '  version  "1.1.0"']), 'expected a string, found " \\"1.1.0\\"" at line 11')
    refuses(edit(['  version "1.1.0"', '  version "1.1.0" ']), 'expected the end of the line, found " " at line 11')
    refuses(edit(['  version "1.1.0"', '  version']), 'expected a space and a value, or ":", after "version" at line 11')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b:\n\nb@']), 'expected a space and a range after "b" at line 16')
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0,a@^1.1.0:']), 'expected ", " and a pattern, or ":", after "a@^1.0.0" at line 10')
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0 a@^1.1.0:']), 'expected ", " and a pattern, or ":", after "a@^1.0.0" at line 10')
    refuses(edit(['b@1.0.0:', 'b@1.0.0 "x"']), 'expected ", " and a pattern, or ":", after "b@1.0.0" at line 18')
  })

  it('a key twice, or empty', () => {
    refuses(edit(['b@1.0.0:', 'b@1.0.0, b@1.0.0:']), '"b@1.0.0" is a key twice at line 18')
    refuses(edit(['b@1.0.0:', 'a@^1.0.0, b@1.0.0:']), '"a@^1.0.0" is a key at line 10 too at line 18')
    refuses(edit(['  version "1.1.0"', '  version "1.1.0"\n  version "1.1.0"']), 'the field "version" twice at line 12')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n    b "1.0.0"\n\nb@']), '"b" is in "dependencies" twice at line 17')
    refuses(edit(['b@1.0.0:', '"":']), 'an empty key, which yarn does not read at line 18')
  })

  it('what yarn reads otherwise, or not at all', () => {
    refuses(`\uFEFF${BASE}`, 'U+FEFF is not allowed at line 1')
    refuses(edit(['  version "1.1.0"', '  version\t"1.1.0"']), 'U+0009 is not allowed at line 11')
    refuses(edit(['  version "1.1.0"\n', '  version "1.1.0"\r']), 'U+000D is not allowed at line 11')
    refuses(`${BASE}\r`, 'U+000D is not allowed at line 44')
    refuses(edit(['  uid ""', '  uid "\u2028"']), 'U+2028 is not allowed at line 38')
    refuses(edit(['  uid ""', '  uid "<<<<<<< ======= >>>>>>>"']), 'yarn reads a file with "<<<<<<<", "=======", ">>>>>>>" in it as a merge conflict')
  })
})

describe('refuses an entry yarn does not write, or installs otherwise', () => {
  it('a field not read here', () => {
    for (const field of ['registry yarn', 'permissions:\n    a b', 'prebuiltVariants:\n    a b', 'peerDependencies:\n    a b', 'x y']) {
      const name = field.split(/[ :]/u)[0]
      refuses(edit(['  version "0.1.0"', `  version "0.1.0"\n  ${field}`]), `unsupported field "${name}"`, '["d@file:./d"]')
    }
  })

  it('a pattern that is not name@range', () => {
    refuses(edit(['b@1.0.0:', 'b:']), '"b" is not a pattern of the form name@range', 'b')
    refuses(edit(['b@1.0.0:', 'B!@1.0.0:']), '"B!" is not a package name', '["B!@1.0.0"]')
    refuses(edit(['b@1.0.0:', '"@s@1.0.0":']), '"@s" is not a package name', '["@s@1.0.0"]')
  })

  it('a version that is not SemVer, or none', () => {
    refuses(edit(['  version "1.1.0"', '  version "1.1"']), '"1.1" is not a version', '["a@^1.0.0"].version')
    refuses(edit(['  version "1.1.0"\n', '']), 'expected a string, found nothing', '["a@^1.0.0"].version')
    refuses(edit(['  version "1.1.0"', '  version:\n    a "1"']), 'expected a string, found a mapping', '["a@^1.0.0"].version')
  })

  it('a name other than its patterns give it, or two', () => {
    refuses(edit(['a@^1.0.0, a@^1.1.0:', 'a@^1.0.0, a@^1.1.0:\n  name b']), 'yarn installs this as "b", and leaves "a" out, which its patterns ask for', '["a@^1.0.0"].name')
    refuses(edit(['"my-b@npm:b@1.0.0":', '"my-b@npm:b@1.0.0", b@^1.0.0:']), '"my-b@npm:b@1.0.0" and "b@^1.0.0" give it two names, of which yarn installs it under one alone', '["my-b@npm:b@1.0.0"]')
    refuses(edit(['"f@https://example.com/f.tgz":', '"f@https://example.com/f.tgz", "g@https://example.com/f.tgz":']), '"f@https://example.com/f.tgz" and "g@https://example.com/f.tgz" give it two names, of which yarn installs it under one alone', '["f@https://example.com/f.tgz"]')
  })

  it('a pattern asking for the registry given another source, which only the manifests may say a resolution does', () => {
    const only = 'which only a resolution may, as the manifests would say'
    refuses(edit(['"f@https://example.com/f.tgz":', 'f@4.0.0, "f@https://example.com/f.tgz":']), `"f@4.0.0" asks for the registry, and is given what "f@https://example.com/f.tgz" names, ${only}`, '["f@4.0.0"]')
    refuses(edit(['"d@file:./d":', 'd@^0.1.0, "d@file:./d":']), `"d@^0.1.0" asks for the registry, and is given what "d@file:./d" names, ${only}`, '["d@^0.1.0"]')
    refuses(edit(['"e@git+https://example.com/e.git#v3":', 'e@3.0.0:']), '"e@3.0.0" asks for the registry, and resolves to a git repository', '["e@3.0.0"]')
    refuses(edit(['"d@file:./d":', 'd@0.1.0:']), '"d@0.1.0" asks for the registry, and resolves to nothing, as for a directory', '["d@0.1.0"]')
    refuses(edit([`"https://example.com/f.tgz#${H}"`, `"file:vendor/f.tgz#${H}"`], ['"f@https://example.com/f.tgz":', 'f@4.0.0:']), '"f@4.0.0" asks for the registry, and resolves to a file: tarball', '["f@4.0.0"]')
  })

  it('a dependency whose pattern is not there, or listed twice', () => {
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "^1.0.0"\n\nb@']), '"b@^1.0.0" is not a pattern of the lockfile', '["a@^1.0.0"].dependencies.b')
    refuses(edit(['    b "1.0.0"\n\nb@', '    b "1.0.0"\n  optionalDependencies:\n    b "1.0.0"\n\nb@']), 'listed under dependencies too', '["a@^1.0.0"].optionalDependencies.b')
    refuses(edit(['    b "1.0.0"\n\nb@', '    B! "1.0.0"\n\nb@']), '"B!" is not a package name', '["a@^1.0.0"].dependencies["B!"]')
  })

  it('a resolution not as yarn writes it', () => {
    const at = (key) => `["${key}"].resolved`
    refuses(edit([`#${C}"`, '"']), 'expected a full commit hash after the "#" of "git+https://example.com/e.git"', at('e@git+https://example.com/e.git#v3'))
    refuses(edit([`#${C}"`, '#v3"']), 'expected a full commit hash after the "#" of "git+https://example.com/e.git"', at('e@git+https://example.com/e.git#v3'))
    refuses(edit(['"git+https://example.com/e.git#', '"git+https://exa mple.com/e.git#']), '"git+https://exa mple.com/e.git" is not a repository URL', at('e@git+https://example.com/e.git#v3'))
    refuses(edit([`f.tgz#${H}"`, `f.tgz#${H}#x"`]), 'more than one "#", of which yarn reads the first alone', at('f@https://example.com/f.tgz'))
    refuses(edit([`f.tgz#${H}"`, 'f.tgz#abc"']), '"abc" is not the hex sha1 of a tarball', at('f@https://example.com/f.tgz'))
    refuses(edit([`f.tgz#${H}"`, 'f.tgz#"']), '"" is not the hex sha1 of a tarball', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"ftp://example.com/f.tgz"']), '"ftp://example.com/f.tgz" is not an http(s) URL, a file: path or a git URL', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"file:/vendor/f.tgz"']), '"/vendor/f.tgz" is not a relative path in normal form', at('f@https://example.com/f.tgz'))
    refuses(edit([`"https://example.com/f.tgz#${H}"`, '"file:vendor/../f.tgz"']), '"vendor/../f.tgz" is not a relative path in normal form', at('f@https://example.com/f.tgz'))
    refuses(edit(['  resolved "https://example.com/f.tgz', '  resolved "https://example.com:x/f.tgz']), '"https://example.com:x/f.tgz" is not an http(s) URL, a file: path or a git URL', at('f@https://example.com/f.tgz'))
  })

  it('an integrity yarn does not check, or that names another sha1', () => {
    refuses(edit(['  uid ""', `  uid ""\n  integrity ${I}`]), 'an integrity, with nothing resolved', '["l@link:./l"].integrity')
    refuses(edit([`#${C}"`, `#${C}"\n  integrity ${I}`]), 'an integrity, which yarn does not check for a git repository', '["e@git+https://example.com/e.git#v3"].integrity')
    refuses(edit([`b-1.0.0.tgz#${H}"`, `b-1.0.0.tgz#${C}"`]), `"${H1}" is not the sha1 after the "#" of resolved`, '["b@1.0.0"].integrity')
    refuses(edit([`  integrity ${I}\n\na@`, '  integrity sha512-x\n\na@']), '"sha512-x" is not a sha1, sha256, sha384 or sha512 integrity', '["@s/c@^2.0.0"].integrity')
    refuses(edit([`  integrity ${I}\n\na@`, `  integrity "${I}  ${I}"\n\na@`]), 'expected a non-empty string', '["@s/c@^2.0.0"].integrity')
  })

  it('anything but a string', () => {
    assert.throws(() => parseYarnLockfile(Buffer.from(BASE)), TypeError)
  })
})

describe('a resolution to a source, where it applies to every request', () => {
  const URL = 'https://example.com/b.tgz'
  // b@1.0.0, which a and d ask for, and the resolution's own pattern, both
  // given the tarball the resolution names.
  const RESOLVED = edit(['b@1.0.0:', `b@1.0.0, "b@${URL}":`], [`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"${URL}#${H}"\n  integrity ${H1}\n\n"d`])
  const resolving = (resolutions, fields = {}) => ({ ...MANIFESTS, '.': { ...MANIFESTS['.'], resolutions, ...fields } })
  const resolved = (resolutions, text = RESOLVED) => parseYarnLockfile(text, resolving(resolutions)).packages
  const applies = 'which yarn does not apply to it here'

  it('reads one that applies everywhere, or along every path it is asked for by', () => {
    for (const resolutions of [{ b: URL }, { '**/b': URL }, { '**/a/b': URL, 'd/b': URL }, { '**/?/b': URL }, { '**/*/b': URL }]) {
      const packages = resolved(resolutions)
      assert.equal(packages['b@1.0.0'], packages[`b@${URL}`], JSON.stringify(resolutions))
      assert.deepEqual(packages['b@1.0.0'].resolution, { type: 'tarball', tarball: URL, sha1: H, integrity: H1 })
    }
  })

  it('refuses one that does not apply along a path it is asked for by', () => {
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "d/b" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ 'd/b': URL }))
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "**/a/b" resolves to, ${applies}`, '["d@file:./d"].dependencies.b', resolving({ '**/a/b': URL }))
    // a is asked for by the root, as a/b, and by the workspace through
    // yarn's aggregator, as workspace-aggregator-…/w/a/b.
    for (const path of ['a/b', '*/b']) {
      refuses(RESOLVED, `"b@1.0.0" is given what the resolution "${path}" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ [path]: URL, 'd/b': URL }))
    }
    // And as w/a/b, as the root asks for the workspace too.
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "*/w/a/b" resolves to, ${applies}`, '["a@^1.0.0"].dependencies.b', resolving({ '*/w/a/b': URL, 'a/b': URL, 'd/b': URL }))
    assert.equal(resolved({ '**/w/a/b': URL, 'a/b': URL, 'd/b': URL })['b@1.0.0'].resolution.tarball, URL)
  })

  it('refuses one that another resolution comes before, as the first to match applies', () => {
    refuses(RESOLVED, `"b@1.0.0" is given what the resolution "**/b" resolves to, ${applies}`, '["d@file:./d"].dependencies.b', resolving({ 'd/b': '1.0.0', '**/b': URL }))
    assert.equal(resolved({ '**/b': URL, 'd/b': '1.0.0' })['b@1.0.0'].resolution.tarball, URL)
  })

  it('refuses the root\'s own dependency given it, which no resolution applies to', () => {
    const manifests = resolving({ '**/b': URL }, { dependencies: { ...MANIFESTS['.'].dependencies, b: '1.0.0' } })
    refuses(RESOLVED, '"b@1.0.0" is given what the resolution "**/b" resolves to, which yarn applies to no dependency of the root\'s own', 'manifests["."].dependencies.b', manifests)
  })

  it('refuses a dependency on what it resolves to, or another entry of that tarball', () => {
    refuses(edit(['b@1.0.0:', `b@1.0.0, "b@${URL}":`], [`"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"\n  integrity ${H1}\n\n"d`, `"${URL}#${H}"\n  integrity ${H1}\n\n"d`], ['  version "0.1.0"\n  dependencies:\n    b "1.0.0"', `  version "0.1.0"\n  dependencies:\n    b "${URL}"`]), `"b@${URL}" asks for what the resolution "**/b" resolves to, as a dependency of its own`, '["d@file:./d"].dependencies.b', resolving({ '**/b': URL }))
    const shared = RESOLVED.replace(`"my-b@npm:b@1.0.0":\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#${H}"`, `"my-b@npm:b@1.0.0":\n  version "1.0.0"\n  resolved "${URL}#${H}"`)
    refuses(shared, 'asks for what the resolution "**/b" resolves to, as a dependency of its own', '["my-b@npm:b@1.0.0"]', resolving({ '**/b': URL }))
  })

  it('refuses a source no resolution names, and a glob not read here', () => {
    const text = RESOLVED
    refuses(text, `"b@1.0.0" asks for the registry, and is given what "b@${URL}" names, which no resolution does`, '["b@1.0.0"]', resolving(undefined, { dependencies: { ...MANIFESTS['.'].dependencies, b: URL } }))
    refuses(text, '"**/{a,d}/b" is a glob not read here', 'manifests["."].resolutions["**/{a,d}/b"]', resolving({ '**/{a,d}/b': URL }))
    refuses(text, 'nothing asks for it: no manifest, no package and no resolution', `["b@${URL}"]`, resolving({ '**/b': 'https://example.com/other.tgz' }))
  })
})
